import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {generateKeyPairSync,createHash} from 'node:crypto';
import {validateRecoveryWindow,validatedOwnerConnection,assertRestoredInventory,boundedOwnerJSON,runCurrentPostgresRecovery,isolatedRestoreSQL,isolatedOriginalChecks} from '../scripts/current-postgres-recovery.mjs';
import {backupRecipientFingerprint} from '../scripts/recovery-backup-envelope.mjs';
import {storageExportV2Contract,storageExportV2Collections,v2MarkerIdentity} from '../hosted/storage-export-v2-contract.js';
const sha=x=>createHash('sha256').update(x).digest('hex');
const now=Date.parse('2026-10-04T06:00:00Z'),head='a'.repeat(40),toolSHA='b'.repeat(64);
const {publicKey}=generateKeyPairSync('rsa',{modulusLength:3072,publicKeyEncoding:{type:'spki',format:'pem'}});
const claim={active:true,live_work:true,issue_number:51,claim_id:'fixture',worker_id:'fixture-holder',branch:'engineering/fixture',expires_at:new Date(now+3600000).toISOString()};
function window(){const marker={version:2,backend:'postgres',read_only:true,revision:1,contract:storageExportV2Contract,counts:Object.fromEntries(storageExportV2Collections.map(k=>[k,0])),catalog_sha256:storageExportV2Contract.postgres_catalog_sha256,geographic_releases_sha256:'c'.repeat(64),footprint_versions_sha256:'d'.repeat(64)};marker.fingerprint=sha(JSON.stringify(v2MarkerIdentity(marker)));return {version:1,issue:51,queue:714,operator_worker_id:'engineering-central-publication-20261003',primary_main_commit:head,capture_tool_sha256:toolSHA,method:'readonly-native-pg-dump-and-isolated-restore',backup_recipient_public_key:publicKey,backup_recipient_sha256:backupRecipientFingerprint(publicKey),observed_at_utc:new Date(now).toISOString(),expires_at_utc:new Date(now+1800000).toISOString(),claim_id:claim.claim_id,holder_worker_id:claim.worker_id,claim_branch:claim.branch,site:{project_id:'appgprj_6abdf87277c08191bce4a22b8dfb25db',version:24,deployment_id:'appgdep_fixture'},read_only:true,drain_verified:true,restore_writes_operator:'engineering-central-publication-20261003',rollback_receipt_url:'https://github.com/ChengshuLi/WorldAtlas/issues/714',source_marker:marker};}
const validate=(value,c=claim,n=now)=>validateRecoveryWindow(value,c,{head,toolSHA,now:n});
test('accepts only pinned live publisher read window',()=>assert.equal(validate(window()).issue,51));
for(const [label,change] of [
 ['writable source',w=>w.source_marker.read_only=false],['legacy projection',w=>w.source_marker.legacy_projection=true],['wrong main',w=>w.primary_main_commit='e'.repeat(40)],['wrong tool',w=>w.capture_tool_sha256='e'.repeat(64)],['wrong publisher',w=>w.operator_worker_id='other'],['undrained requests',w=>w.drain_verified=false],['unpinned recipient',w=>w.backup_recipient_sha256='e'.repeat(64)],['missing count',w=>delete w.source_marker.counts[storageExportV2Collections[0]]],['changed fingerprint',w=>w.source_marker.fingerprint='e'.repeat(64)],['expired window',w=>w.expires_at_utc=new Date(now).toISOString()],['old observation',w=>w.observed_at_utc=new Date(now-660000).toISOString()],['future observation',w=>w.observed_at_utc=new Date(now+1).toISOString()],['unbounded window',w=>w.expires_at_utc=new Date(now+1800001).toISOString()]
])test(`rejects ${label}`,()=>{const w=window();change(w);assert.throws(()=>validate(w));});
for(const [field,value] of [['active',false],['live_work',false],['issue_number',22],['claim_id','other'],['worker_id','other'],['branch','other'],['expires_at',new Date(now).toISOString()]])test(`rejects canonical claim ${field} mismatch`,()=>assert.throws(()=>validate(window(),{...claim,[field]:value})));
test('end validation permits elapsed capture time within original window',()=>assert.doesNotThrow(()=>validateRecoveryWindow(window(),claim,{head,toolSHA,now:now+1200000,phase:'end'})));
const host='ep-fixture.us-east-2.aws.neon.tech',uri=`postgresql://neondb_owner:fixture-password@${host}/neondb?sslmode=require`;
test('owner secret parsed without including connection URI in result',()=>assert.deepEqual(validatedOwnerConnection(uri,host),{host,password:'fixture-password'}));
for(const bad of [uri.replace('neondb_owner','worldatlas_app'),uri.replace('/neondb?','/other?'),uri.replace('sslmode=require','sslmode=disable'),uri.replace('fixture-password','bad%0Asecret'),uri.replace(host,'ep-other.us-east-2.aws.neon.tech'),uri+'#fragment'])test('rejects unsafe owner endpoint or identity '+bad.replace('fixture-password','redacted'),()=>assert.throws(()=>validatedOwnerConnection(bad,host)));
const inventory=()=>({identity:{database_name:'neondb'},collections:{locations:{count:1,ordered_rows_sha256:'a'}},owner_registry:[{migration_id:'original',applied_at:'original timestamp'}],permissions:[{owner:'neondb_owner',app_select:false}],sequence:[{last_value:5,is_called:true}]});
test('isolated database identity can differ while original bytes and state remain exact',()=>{const before=inventory(),target=inventory();target.identity.database_name='postgres';assert.doesNotThrow(()=>assertRestoredInventory(before,target,inventory()));});
for(const field of ['collections','owner_registry','permissions','sequence'])test(`detects restored ${field} corruption`,()=>{const target=inventory();target[field]=[];assert.throws(()=>assertRestoredInventory(inventory(),target,inventory()));});
test('detects source change during backup',()=>{const after=inventory();after.sequence[0].last_value++;assert.throws(()=>assertRestoredInventory(inventory(),inventory(),after));});
test('bounded owner API accepts valid object',async()=>assert.deepEqual(await boundedOwnerJSON(new Response('{"endpoints":[]}')),{endpoints:[]}));
for(const body of ['[]','null','invalid',JSON.stringify({oversized:'a'.repeat(2*1024*1024)})])test('bounded owner API rejects malformed or oversized response '+body.length,async()=>assert.rejects(()=>boundedOwnerJSON(new Response(body))));
test('owner API rejects HTTP failures',async()=>assert.rejects(()=>boundedOwnerJSON(new Response('{}',{status:403}))));
test('untrusted execution fails before any provider access and writes sanitized failure receipt',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'atlas-recovery-test-')),output=path.join(dir,'receipt');let calls=0;try{const result=await runCurrentPostgresRecovery({env:{NEON_API_KEY:'fixture-secret'},fetcher:()=>{calls++;throw Error('unexpected network');},output});assert.equal(calls,0);assert.equal(result.status,'failed');assert.equal(result.failure_stage,'authorize');assert.equal(fs.readFileSync(path.join(output,'public-receipts/receipt.json'),'utf8').includes('fixture-secret'),false);await assert.rejects(()=>runCurrentPostgresRecovery({env:{},output}),/preserve-existing/);}finally{fs.rmSync(dir,{recursive:true,force:true});}});

const restoreHeader="-- PostgreSQL database dump\nSELECT pg_catalog.set_config('search_path', '', false);\n-- Name: synthetic; Type: TABLE DATA\nCOPY original FROM stdin;\nSELECT pg_catalog.set_config('search_path', '', false);\n\\.\n";
test('restore session header adjustment preserves every factual COPY byte',()=>{const source=Buffer.from(restoreHeader),result=isolatedRestoreSQL(source),at=source.indexOf(Buffer.from('\n-- Name: '));assert.deepEqual(result.subarray(result.indexOf(Buffer.from('\n-- Name: '))),source.subarray(at));assert.match(result.toString(),/public,pg_catalog/);});
test('restore header fails closed on missing or duplicate session setup',()=>{assert.throws(()=>isolatedRestoreSQL(Buffer.from('-- Name: missing')));assert.throws(()=>isolatedRestoreSQL(Buffer.from(restoreHeader.replace('-- PostgreSQL database dump',"SELECT pg_catalog.set_config('search_path', '', false);"))));});
test('local constraint revalidation requires exact immutable original schema',()=>{const schema=fs.readFileSync('postgres/schema.sql');assert.equal(isolatedOriginalChecks(schema).match(/ADD CONSTRAINT/g).length,4);assert.throws(()=>isolatedOriginalChecks(Buffer.concat([schema,Buffer.from(' ')])));});
