import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {gzipSync} from 'node:zlib';
import {createLocalPostgres} from '../scripts/verify-postgres-schema.mjs';
import {importBatch,registerMedia} from '../hosted/records.js';
import {stageGeographicRelease,finalizeGeographicRelease,geographicMembershipHash,geographicLocationIdsHash,geographicChangesHash} from '../hosted/geographic-releases.js';
import {packOwnership} from '../src/pixel-ownership.js';
import {footprintDigest,footprintCanonicalJson,stageFootprintVersion,publishFootprintVersion,importFootprintSelections,footprintSelectionAt,footprintWithdrawalsPage,footprintEvidence,footprintVersionPage,footprintAttributeEligibility,validateFootprintManifest,verifiedFootprintObject} from '../hosted/footprint-versions.js';
class D1{constructor(){this.engine=new DatabaseSync(':memory:');this.engine.exec('PRAGMA foreign_keys=ON');for(const f of fs.readdirSync(new URL('../drizzle/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())this.engine.exec(fs.readFileSync(new URL('../drizzle/'+f,import.meta.url),'utf8'));}prepare(sql){let args=[];const db=this.engine;return {bind(...v){args=v;return this;},async first(){return db.prepare(sql).get(...args)??null;},async all(){return {results:db.prepare(sql).all(...args)};},run(){return {meta:{changes:Number(db.prepare(sql).run(...args).changes)}};}};}async batch(stmts){this.engine.exec('BEGIN IMMEDIATE');try{const rows=stmts.map(s=>s.run());this.engine.exec('COMMIT');return rows;}catch(e){this.engine.exec('ROLLBACK');throw e;}}}
const kinds=['continent','subcontinent','region','area','province','location'],pins={release_id:'reference',hierarchy_sha256:'a'.repeat(64),footprints_sha256:'b'.repeat(64)};
const source=(id,status)=>({id,name:`Synthetic ${id}`,url:'https://example.org/test-only',license:'CC0',vintage:'2026',supported_from:status==='reference'?2026:-3000,supported_to:2027,status,metadata:{synthetic_fixture:true}});
async function fixture(backend){const pg=backend==='postgres'?await createLocalPostgres():null,db=pg?.db??new D1();if(pg){await pg.engine.exec("CREATE ROLE worldatlas_app");for(const f of ['0001_temporal_geography.sql','0002_footprint_versions.sql'])await pg.engine.exec(fs.readFileSync(new URL('../postgres/migrations/'+f,import.meta.url),'utf8'));}
 await importBatch(db,JSON.parse(fs.readFileSync(new URL('../data/hosted-type-catalog.json',import.meta.url))));const entities=Array.from({length:6},(_,n)=>kinds.map((kind,i)=>({id:`${kind}-${n}`,kind,name:`Synthetic ${kind} ${n}`,parent_id:i?`${kinds[i-1]}-${n}`:null}))).flat();await importBatch(db,{sources:[source('history','historical'),source('reference','reference'),source('example','example')],entities});const memberships=entities.map(e=>({entity_id:e.id,kind:e.kind,parent_id:e.parent_id,reference_name:e.name,active:1,source_id:'reference',evidence:{test:true}}));await stageGeographicRelease(db,{release:{id:'reference',source_id:'reference',version:1,reference_date:'2026-10-02',hierarchy_sha256:pins.hierarchy_sha256,footprints_sha256:pins.footprints_sha256,membership_sha256:await geographicMembershipHash(memberships),location_ids_sha256:await geographicLocationIdsHash(memberships),changes_sha256:await geographicChangesHash([]),expected_counts:Object.fromEntries(kinds.map(k=>[k,6]))},memberships});await finalizeGeographicRelease(db,'reference');
 const storage=new Map(),bucket={async get(key){const data=storage.get(key);if(!data)return null;let n=0;return {body:new ReadableStream({pull(controller){if(n>=data.length){controller.close();return;}controller.enqueue(data.slice(n,n+=7));}})};}};
 let counter=0;async function media(data){data=typeof data==='string'?new TextEncoder().encode(data):new Uint8Array(data);const sha256=await footprintDigest(data),id=`media-${counter++}`;await registerMedia(db,{id,object_key:`media/${sha256}`,sha256,bytes:data.length,mime:'application/octet-stream',name:id,license:'CC0',attribution:'Synthetic test only',source_id:'history'});storage.set(`media/${sha256}`,data);return {media_id:id,sha256,bytes:data.length};}
 const archive=await media('synthetic original source archive'),geometry=await media('synthetic reconciled geometry'),mask=await media('synthetic source land mask');const rows=Array.from({length:256},(_,y)=>y===0?Uint32Array.from(Array.from({length:6},(_,i)=>[i,i+1,i+1]).flat()):new Uint32Array()),packed=packOwnership({size:256,rows}),little=arr=>{const b=new Uint8Array(arr.length*4),v=new DataView(b.buffer);arr.forEach((n,i)=>v.setUint32(i*4,n,true));return b;};
 const gridParts=[];for(const [role,arr]of [['rows',packed.rows],['runs',packed.runs]]){const raw=little(arr),a=await media(gzipSync(raw));gridParts.push({...a,role,offset:0,words:arr.length,encoding:'gzip-u32le',decoded_sha256:await footprintDigest(raw),decoded_bytes:raw.length});}
 const locations=Array.from({length:6},(_,i)=>({id:`location-${i}`,pixel_index:i+1,footprint_sha256:String(i+1).repeat(64),source_media_ids:[archive.media_id,geometry.media_id],status:'represented',cells:1,land_area_m2:1,represented_area_m2:1})),objects=[{...archive,role:'source_archive'},{...geometry,role:'reconciled_geometry'},{...mask,role:'coverage_mask'},...gridParts],grid={format:'packed-ownership-v2-u32le',projection:'EPSG:3857',latitude_limit:85.05112878,antimeridian:'split-at-180',zoom:0,size:256,coordinate_bits:8,run_words:packed.runs.length},dictionary_sha256=await footprintDigest(footprintCanonicalJson(locations.map(l=>l.id))),manifest={format:'worldatlas-footprint-v1',id:'footprint-1',release_id:'reference',source_id:'history',supported_from:1000,supported_to:1100,footprint_hash_algorithm:'sha256-canonical-json-location-geometry-sha256-v1',locations,objects,grid,dictionary_sha256,location_ids_sha256:await geographicLocationIdsHash(locations.map(l=>({...l,kind:'location'}))),footprints_sha256:await footprintDigest(footprintCanonicalJson(locations.map(l=>[l.id,l.footprint_sha256]))),grid_sha256:await footprintDigest(footprintCanonicalJson({grid,dictionary_sha256,parts:gridParts}))};
 const keys=await crypto.subtle.generateKey('Ed25519',true,['sign','verify']),code='c'.repeat(64),trust={'synthetic-producer':{code_sha256:code,public_key_jwk:await crypto.subtle.exportKey('jwk',keys.publicKey)}};
 async function packageVersion(m=manifest,{signatureBad=false}={}){const manifestMedia=await media(footprintCanonicalJson(m)),proof={format:'worldatlas-footprint-proof-v1',manifest_sha256:manifestMedia.sha256,release_id:m.release_id,footprints_sha256:m.footprints_sha256,producer:{code_sha256:code,algorithm:'synthetic-test-only'},checks:Object.fromEntries(['valid_geometries','antimeridian','no_inter_location_overlaps','coverage_explained','all_locations_represented','exclusive_grid'].map(k=>[k,true])),coverage:{landmask_media_id:mask.media_id,uncovered_statuses:['water','source-gap'],approved_exception_source_ids:[]}},signature=await crypto.subtle.sign('Ed25519',keys.privateKey,new TextEncoder().encode(footprintCanonicalJson(proof)));proof.signature={key_id:'synthetic-producer',algorithm:'Ed25519',value:Buffer.from(signatureBad?new Uint8Array(64):signature).toString('base64')};const receiptMedia=await media(footprintCanonicalJson(proof));return {manifest_media_id:manifestMedia.media_id,receipt_media_id:receiptMedia.media_id,producer_key_id:'synthetic-producer',metadata:{test:true}};}
 const payload=await packageVersion();const context={maintainer:true,trustedProducers:trust};return {db,pg,bucket,storage,manifest,payload,context,media,packageVersion,close:()=>pg?pg.close():db.engine.close()};}
async function both(fn){for(const backend of ['sqlite','postgres']){const f=await fixture(backend);try{await fn(f,backend);}finally{await f.close();}}}
const claim=(id,extra={})=>({id,version_id:'footprint-1',source_id:'history',valid_from:1000,valid_to:1100,...extra});const payload=extra=>({expected_geography:pins,...extra});
test('maintainer gate publishes complete signed, byte-verified products on both databases',()=>both(async(f,backend)=>{
 await assert.rejects(stageFootprintVersion(f.db,f.bucket,f.payload),e=>e.status===403);await stageFootprintVersion(f.db,f.bucket,f.payload,f.context);await assert.rejects(importFootprintSelections(f.db,payload({footprints:[claim('unpublished')]})));const result=await publishFootprintVersion(f.db,f.bucket,'footprint-1',f.context);assert.equal(result.status,'published');assert.equal((await publishFootprintVersion(f.db,f.bucket,'footprint-1',f.context)).duplicate,true);assert.equal((await stageFootprintVersion(f.db,f.bucket,f.payload,f.context)).duplicate,true);
 await importFootprintSelections(f.db,payload({footprints:[claim('selected')]}));const selected=await footprintSelectionAt(f.db,1000);assert.equal(selected.historical,true);assert.equal(selected.version.grid_sha256,f.manifest.grid_sha256);assert.equal(selected.source.name,'Synthetic history');assert.equal((await footprintSelectionAt(f.db,1100)).status,'reference');assert.equal((await footprintVersionPage(f.db)).records.length,1);await assert.rejects(footprintSelectionAt(f.db,0));await assert.rejects(footprintSelectionAt(f.db,1000,{expectedRevision:0}));await assert.rejects(f.db.batch([f.db.prepare("UPDATE atlas_footprint_versions SET status='staged',verified_receipt_sha256=NULL,published_at=NULL WHERE id='footprint-1'")]));
 if(backend==='postgres'){const grants=await f.pg.engine.query("SELECT has_table_privilege('worldatlas_app','atlas_footprint_versions','SELECT') AS read,has_table_privilege('worldatlas_app','atlas_footprint_versions','INSERT') AS write,has_table_privilege('worldatlas_app','atlas_geographic_footprint_records','INSERT') AS select_claim");assert.deepEqual(grants.rows[0],{read:true,write:false,select_claim:true});}
}));
test('forged signatures, altered R2 bytes and incomplete inventories cannot publish',()=>both(async f=>{
 let m=structuredClone(f.manifest);m.locations.pop();m.id='incomplete';const p=await f.packageVersion(m);await stageFootprintVersion(f.db,f.bucket,p,f.context);await assert.rejects(publishFootprintVersion(f.db,f.bucket,'incomplete',f.context),/complete/);
 m=structuredClone(f.manifest);m.id='forged';const bad=await f.packageVersion(m,{signatureBad:true});await stageFootprintVersion(f.db,f.bucket,bad,f.context);await assert.rejects(publishFootprintVersion(f.db,f.bucket,'forged',f.context),/signature/);
 await stageFootprintVersion(f.db,f.bucket,f.payload,f.context);const object=f.manifest.objects[0],old=f.storage.get('media/'+object.sha256);f.storage.set('media/'+object.sha256,new Uint8Array(old.length));await assert.rejects(publishFootprintVersion(f.db,f.bucket,'footprint-1',f.context),/hash/);assert.equal((await footprintVersionPage(f.db)).records.length,0);
}));
test('selection corrections are source bounded, sealed, retirement-aware and preserve original bytes',()=>both(async f=>{
 await stageFootprintVersion(f.db,f.bucket,f.payload,f.context);await publishFootprintVersion(f.db,f.bucket,'footprint-1',f.context);
 await importFootprintSelections(f.db,payload({footprints:[claim('derived',{method:'derived'}),claim('uncertain',{version_id:null,metadata:' { "reason" : "source unavailable" } '}),claim('example',{source_id:'example',is_example:1})]}));assert.equal((await footprintSelectionAt(f.db,1000)).status,'unknown');assert.equal((await footprintSelectionAt(f.db,1000,{examples:true})).status,'unknown');const corrections=payload({ingestion_id:'correction',retirements:[{id:'withdraw',target_id:'uncertain',replacement_id:'direct',source_id:'history',reason:'Synthetic correction'}],footprints:[claim('direct')]});await importFootprintSelections(f.db,corrections);assert.equal((await importFootprintSelections(f.db,corrections)).duplicate,true);assert.equal((await footprintSelectionAt(f.db,1000)).claim.id,'direct');assert.equal((await footprintEvidence(f.db,'uncertain')).status,'superseded');assert.equal((await footprintWithdrawalsPage(f.db)).records[0].target_id,'uncertain');assert.equal((await f.db.prepare('SELECT metadata FROM atlas_geographic_footprint_records WHERE id=?').bind('uncertain').first()).metadata,' { "reason" : "source unavailable" } ');
 for(const row of [claim('zero',{valid_from:0}),claim('fraction',{valid_from:1000.5}),claim('outside',{valid_from:999}),claim('wrong-source',{source_id:'reference'}),claim('example-leak',{source_id:'example'}),claim('overlap')])await assert.rejects(importFootprintSelections(f.db,payload({footprints:[row]})));
 await assert.rejects(importFootprintSelections(f.db,payload({retirements:[{id:'missing',target_id:'direct',replacement_id:'missing',source_id:'history',reason:'Missing replacement'}]})));assert.equal((await footprintSelectionAt(f.db,1000)).claim.id,'direct');await assert.rejects(importFootprintSelections(f.db,{...payload({footprints:[claim('wrong-pins')]}),expected_geography:{...pins,footprints_sha256:'f'.repeat(64)}}));
 const sealed=f.db.prepare("INSERT INTO atlas_geographic_footprint_records(id,version_id,release_id,valid_from,valid_to,source_id,method,status,is_example,validation_id,metadata) VALUES('sealed-append',NULL,'reference',-1,1,'history','direct','unknown',0,'correction','{}')");await assert.rejects(f.db.batch([sealed]));
 const raw=f.db.prepare("INSERT INTO atlas_geographic_footprint_records(id,version_id,release_id,valid_from,valid_to,source_id,method,status,is_example,validation_id,metadata) VALUES('dangling',NULL,'reference',-1,1,'history','direct','unknown',0,'missing-validation','{}')");await assert.rejects(f.db.batch([raw]));assert.equal((await footprintSelectionAt(f.db,-1)).status,'reference');
}));
test('manifest and streamed object limits reject arbitrary classifications, duplicate IDs and registry byte tampering',()=>both(async f=>{
 for(const change of [m=>{m.locations[1].id=m.locations[0].id;},m=>{m.locations[0].cells=0;},m=>{m.grid.projection='arbitrary';},m=>{m.objects[3].decoded_bytes=2**30;},m=>{m.footprint_hash_algorithm='old-wkb';}]){const m=structuredClone(f.manifest);change(m);assert.throws(()=>validateFootprintManifest(m));}
 const object=f.manifest.objects[0];await assert.rejects(verifiedFootprintObject(f.db,f.bucket,object.media_id,{limit:1}));f.storage.delete('media/'+object.sha256);await assert.rejects(verifiedFootprintObject(f.db,f.bucket,object.media_id),/missing/);
}));
test('obsolete known evidence is removed before precedence while explicit unknown and sourced continuity remain eligible',()=>{
 const context={historical:true,versionId:'v2',footprintsSha256:'a'.repeat(64),locationSha256:'b'.repeat(64)},old={value:'Owner',location_id:'location',method:'direct',metadata:{territorial_scope:{footprints_sha256:'c'.repeat(64)}}};assert.equal(footprintAttributeEligibility(old,context).eligible,false);assert.equal(footprintAttributeEligibility({...old,value:null},context).eligible,true);assert.equal(footprintAttributeEligibility({...old,method:'derived',metadata:{territorial_scope:{location_sha256:context.locationSha256}}},context).eligible,true);assert.equal(footprintAttributeEligibility({...old,metadata:{territorial_scope:{continuity:{version_id:'v2',source_id:'source',evidence_sha256:'d'.repeat(64)}}}},{...context,continuityProofs:[{version_id:'v2',source_id:'source',location_id:'location',evidence_sha256:'d'.repeat(64)}]}).eligible,true);assert.equal(footprintAttributeEligibility({...old,method:'derived',metadata:{territorial_scope:{continuity:{version_id:'v2',source_id:'source',evidence_sha256:'d'.repeat(64)}}}},context).eligible,false);assert.equal(footprintAttributeEligibility({value:42,metadata:{}},{...context,historical:false,legacyReferenceSha256:context.footprintsSha256}).eligible,true);
});
test('even a trusted signed receipt cannot publish overlapping grid runs or wrong decoded bytes',()=>both(async f=>{
 const m=structuredClone(f.manifest),part=m.objects.find(o=>o.role==='runs'),raw=new Uint8Array(part.decoded_bytes),view=new DataView(raw.buffer);for(let i=0;i<6;i++){view.setUint32(i*8,(i+1)*256+i,true);view.setUint32(i*8+4,i,true);}view.setUint32(8,2*256,true);const media=await f.media(gzipSync(raw));Object.assign(part,media,{decoded_sha256:await footprintDigest(raw)});m.grid_sha256=await footprintDigest(footprintCanonicalJson({grid:m.grid,dictionary_sha256:m.dictionary_sha256,parts:m.objects.filter(o=>['rows','runs'].includes(o.role))}));m.id='overlapping-grid';const p=await f.packageVersion(m);await stageFootprintVersion(f.db,f.bucket,p,f.context);await assert.rejects(publishFootprintVersion(f.db,f.bucket,m.id,f.context),/exactly one/);
 const changed=structuredClone(f.manifest);changed.id='decoded-mismatch';changed.objects.find(o=>o.role==='runs').decoded_sha256='f'.repeat(64);changed.grid_sha256=await footprintDigest(footprintCanonicalJson({grid:changed.grid,dictionary_sha256:changed.dictionary_sha256,parts:changed.objects.filter(o=>['rows','runs'].includes(o.role))}));await stageFootprintVersion(f.db,f.bucket,await f.packageVersion(changed),f.context);await assert.rejects(publishFootprintVersion(f.db,f.bucket,changed.id,f.context),/Decoded.*hash/);
}));
