import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {importBatch,attributesAt,entityProfile} from '../hosted/records.js';
import {stageGeographicRelease,finalizeGeographicRelease,geographicRelease,geographicMembershipPage,referenceMembership,geographicChangePage,geographicMembershipHash,geographicLocationIdsHash,geographicChangesHash} from '../hosted/geographic-releases.js';
class D1{
 constructor(){this.sqlite=new DatabaseSync(':memory:');this.sqlite.exec('PRAGMA foreign_keys=ON');for(const f of readdirSync(new URL('../drizzle/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())this.sqlite.exec(readFileSync(new URL(`../drizzle/${f}`,import.meta.url),'utf8'));}
 prepare(sql){const sqlite=this.sqlite;let args=[];return {bind(...values){args=values;return this;},async all(){return {results:sqlite.prepare(sql).all(...args)};},async first(){return sqlite.prepare(sql).get(...args)??null;},run(){return {meta:{changes:Number(sqlite.prepare(sql).run(...args).changes)}};}};}
 async batch(statements){this.sqlite.exec('BEGIN IMMEDIATE');try{const result=statements.map(s=>s.run());this.sqlite.exec('COMMIT');return result;}catch(error){this.sqlite.exec('ROLLBACK');throw error;}}
}
const kinds=['continent','subcontinent','region','area','province','location'];
const source=(id,status='reference')=>({id,name:id,url:'https://example.org/pinned-source',license:'CC0',vintage:'2026 publication; original vintages retained',supported_from:status==='reference'?2026:-3000,supported_to:2027,status});
async function fixture(){const db=new D1();await importBatch(db,JSON.parse(readFileSync(new URL('../data/hosted-type-catalog.json',import.meta.url))));const entities=[];for(let c=0;c<6;c++)for(let i=0;i<6;i++)entities.push({id:`${kinds[i]}-${c}`,kind:kinds[i],name:`Original ${kinds[i]} ${c}`,parent_id:i?`${kinds[i-1]}-${c}`:null,source_id:'reference'});await importBatch(db,{sources:[source('reference'),source('history','historical'),source('examples','example')],entities});return {db,entities};}
const memberships=entities=>entities.map(e=>({entity_id:e.id,kind:e.kind,parent_id:e.parent_id,reference_name:e.name,active:1,source_id:'reference',evidence:{method:'pinned-reference',source_version:'test'}}));
async function manifest(id,version,ms,changes=[]){return {id,source_id:'reference',version,reference_date:'2026-10-01',hierarchy_sha256:'a'.repeat(64),footprints_sha256:'b'.repeat(64),membership_sha256:await geographicMembershipHash(ms),location_ids_sha256:await geographicLocationIdsHash(ms),changes_sha256:await geographicChangesHash(changes),expected_counts:Object.fromEntries([...kinds].reverse().map(k=>[k,ms.filter(m=>m.kind===k&&m.active).length])),metadata:{reference_only:true,pinned_asset:'test source'}};}
async function stage(db,r,ms,changes=[]){return stageGeographicRelease(db,{release:r,memberships:ms,changes});}

test('staging is invisible; publication requires complete pinned membership and preserves original registry',async()=>{const {db,entities}=await fixture(),ms=memberships(entities),r=await manifest('first',1,ms);const imported=await stage(db,r,ms);assert.equal((await stage(db,r,ms)).duplicate,true);assert.equal(await geographicRelease(db),null);assert.equal((await geographicMembershipPage(db)).records.length,0);assert.equal(await referenceMembership(db,'location-0'),null);assert.equal((await geographicRelease(db,'first',{includeStaged:true})).status,'staged');assert.equal((await finalizeGeographicRelease(db,'first')).status,'published');assert.equal((await finalizeGeographicRelease(db,'first')).duplicate,true);assert.equal((await referenceMembership(db,'location-0')).membership.resolved_reference_name,'Original location 0');assert.equal(imported.counts.memberships,36);assert.equal(db.sqlite.prepare("SELECT parent_id FROM atlas_entities WHERE id='location-0'").get().parent_id,'province-0');});

test('rename/reparent releases and same-tier merge crosswalk preserve historical evidence and archived releases',async()=>{const {db,entities}=await fixture(),old=memberships(entities);await stage(db,await manifest('old',1,old),old);await finalizeGeographicRelease(db,'old');await importBatch(db,{records:[{id:'population-evidence',location_id:'location-0',attribute:'population',value:42,valid_from:1000,valid_to:1100,source_id:'history'}],names:[{id:'ancient-name',entity_id:'location-0',name:'Historical Name',valid_from:1000,valid_to:1100,source_id:'history'}],entities:[{id:'replacement-province',kind:'province',name:'Reference replacement',parent_id:'area-0',source_id:'reference'}]});const ms=old.map(m=>m.entity_id==='province-0'?{...m,active:0}:m.entity_id==='location-0'?{...m,parent_id:'replacement-province',reference_name:'Modern corrected name'}:m);ms.push({entity_id:'replacement-province',kind:'province',parent_id:'area-0',reference_name:'Reference replacement',active:1,source_id:'reference',evidence:{method:'named-source-parent'}});const changes=[{id:'new:location-parent',old_entity_id:'location-0',new_entity_id:'location-0',change_type:'reparent',source_id:'reference',evidence:{reason:'Whole original source-parent membership'}},{id:'new:merge',old_entity_id:'province-0',new_entity_id:'replacement-province',change_type:'merge',source_id:'reference',evidence:{reason:'Duplicate same-tier parent identity'}}];await stage(db,await manifest('new',2,ms,changes),ms,changes);await finalizeGeographicRelease(db,'new');const ref=await referenceMembership(db,'location-0');assert.equal(ref.membership.parent_id,'replacement-province');assert.equal(ref.membership.resolved_reference_name,'Modern corrected name');assert.equal(ref.membership.original_parent_id,'province-0');assert.equal((await referenceMembership(db,'location-0',{releaseId:'old'})).membership.parent_id,'province-0');assert.equal((await entityProfile(db,'location-0',1000)).display_name,'Historical Name');assert.equal((await attributesAt(db,1000)).records[0].value,42);assert.equal(db.sqlite.prepare("SELECT name,parent_id FROM atlas_entities WHERE id='location-0'").get().name,'Original location 0');assert.equal((await geographicChangePage(db,{releaseId:'new'})).records.length,2);assert.equal((await geographicMembershipPage(db,{releaseId:'new',active:false})).records[0].entity_id,'province-0');});

test('manifest counts, complete same-release chains, no-year-zero calendar labels and hashes are real gates',async()=>{const {db,entities}=await fixture(),ms=memberships(entities);await assert.rejects(stage(db,{...await manifest('invalid-date',1,ms),reference_date:'2026-02-30'},ms),/calendar date/);await assert.rejects(stage(db,{...await manifest('invalid-count',1,ms),expected_counts:{location:6}},ms),/six tier/);const r=await manifest('incomplete',1,ms);await stage(db,r,ms.filter(m=>m.entity_id!=='area-0'));await assert.rejects(finalizeGeographicRelease(db,'incomplete'),/parent chain/);assert.equal(await geographicRelease(db),null);await stageGeographicRelease(db,{release_id:r.id,memberships:[ms.find(m=>m.entity_id==='area-0')]});await finalizeGeographicRelease(db,r.id);const bad={...await manifest('bad-hash',2,ms),membership_sha256:'c'.repeat(64)};await stage(db,bad,ms);await assert.rejects(finalizeGeographicRelease(db,'bad-hash'),/content hash/);assert.equal((await geographicRelease(db)).id,'incomplete');const badCounts={...await manifest('bad-counts',3,ms),expected_counts:{...r.expected_counts,location:7}};await stage(db,badCounts,ms);await assert.rejects(finalizeGeographicRelease(db,'bad-counts'),/node counts/);});

test('bounded atomic staging rejects unknown/nongeographic/example identities and wrong-tier parents',async()=>{const {db,entities}=await fixture(),ms=memberships(entities),r=await manifest('r',1,ms);await assert.rejects(stage(db,r,[{...ms[0],entity_id:'missing'}]),/FOREIGN KEY/);assert.equal(await geographicRelease(db,'r',{includeStaged:true}),null,'failed release definition and ledger roll back');await stage(db,r,[]);await assert.rejects(stageGeographicRelease(db,{release_id:r.id,memberships:[{...ms.at(-1),parent_id:'continent-0'}]}),/adjacent-tier/);await importBatch(db,{entities:[{id:'person',kind:'person',name:'Person'},{id:'fiction',kind:'location',name:'Fiction',parent_id:'province-0',is_example:1,source_id:'examples'}]});for(const id of ['person','fiction'])await assert.rejects(stageGeographicRelease(db,{release_id:r.id,memberships:[{...ms.at(-1),entity_id:id}]}),/non-example geographic/);await assert.rejects(stageGeographicRelease(db,{release_id:r.id,memberships:Array.from({length:251},(_,i)=>({...ms[0],entity_id:`x-${i}`}))}),/250/);await assert.rejects(stageGeographicRelease(db,{release_id:r.id,memberships:[ms[0],ms[0]]}),/Duplicate/);await assert.rejects(stageGeographicRelease(db,{release_id:r.id,memberships:[{...ms[0],source_id:'history'}]}),/reference source/);});

test('immutable staged contents and ingestion collisions reject atomically; raw SQL blocks cycles and publication bypass',async()=>{const {db,entities}=await fixture(),ms=memberships(entities),r=await manifest('r',1,ms);await stageGeographicRelease(db,{release:r,ingestion_id:'explicit',memberships:[ms[0]]});await assert.rejects(stageGeographicRelease(db,{release_id:r.id,ingestion_id:'explicit',memberships:[ms[1]]}),/Ingestion ID/);await assert.rejects(stageGeographicRelease(db,{release_id:r.id,memberships:[ms[1],{...ms[0],reference_name:'Conflicting'}]}),/collision/);assert.equal(db.sqlite.prepare('SELECT count(*) n FROM atlas_geographic_memberships').get().n,1);assert.throws(()=>db.sqlite.exec("UPDATE atlas_geographic_memberships SET parent_id='location-0'"),/immutable/);assert.throws(()=>db.sqlite.exec("UPDATE atlas_geographic_releases SET membership_sha256='c'"),/immutable/);assert.throws(()=>db.sqlite.exec("UPDATE atlas_geographic_releases SET status='published',published_at=1 WHERE id='r'"),/count mismatch/);assert.throws(()=>db.sqlite.prepare('INSERT INTO atlas_geographic_memberships(release_id,entity_id,parent_id,source_id) VALUES(?,?,?,?)').run('r','location-0','location-0','reference'),/adjacent-tier/);assert.throws(()=>db.sqlite.exec('DELETE FROM atlas_geographic_releases'),/retained/);});

test('crosswalk evidence, tier identity and retired membership must match the published release',async()=>{const {db,entities}=await fixture(),ms=memberships(entities);const badChange={id:'bad',old_entity_id:'province-0',new_entity_id:'location-0',change_type:'merge',source_id:'reference',evidence:{reason:'Invalid'}};await assert.rejects(stage(db,await manifest('bad',1,ms,[badChange]),ms,[badChange]),/stay in tier/);const self={...badChange,new_entity_id:'province-0',change_type:'reparent',evidence:{}};await assert.rejects(stage(db,await manifest('blank',1,ms,[self]),ms,[self]),/explicit source evidence/);const merge={...badChange,new_entity_id:'province-1'};await stage(db,await manifest('invalid-retire',1,ms,[merge]),ms,[merge]);await assert.rejects(finalizeGeographicRelease(db,'invalid-retire'),/crosswalk/);assert.equal(await geographicRelease(db),null);});

test('published pages use indexed keyset queries and older releases remain inspectable',async()=>{const {db,entities}=await fixture(),ms=memberships(entities);await stage(db,await manifest('first',1,ms),ms);await finalizeGeographicRelease(db,'first');const page=await geographicMembershipPage(db,{limit:3});assert.equal(page.records.length,3);assert.ok(page.next_cursor);const next=await geographicMembershipPage(db,{cursor:page.next_cursor,limit:3});assert.ok(next.records.every(r=>r.entity_id>page.next_cursor));assert.equal((await geographicMembershipPage(db,{parentId:'province-0'})).records[0].entity_id,'location-0');const plan=db.sqlite.prepare('EXPLAIN QUERY PLAN SELECT entity_id FROM atlas_geographic_memberships WHERE release_id=? AND active=1 AND parent_id=? AND entity_id>? ORDER BY entity_id LIMIT 250').all('first','province-0','');assert.match(plan.map(p=>p.detail).join(' '),/geographic_membership_parent/);await assert.rejects(stageGeographicRelease(db,{release_id:'first',memberships:[]}),/immutable/);assert.throws(()=>db.sqlite.exec("UPDATE atlas_geographic_releases SET published_at=2 WHERE id='first'"),/immutable/);});

test('streamed publication hashing matches exported UTF-8 canonical hashes across page boundaries',async()=>{const {db,entities}=await fixture(),more=Array.from({length:501},(_,i)=>({id:`location-extra-${String(i).padStart(3,'0')}`,kind:'location',name:'Extra',parent_id:'province-0',source_id:'reference'}));more.push({id:'location-\ue000',kind:'location',name:'BMP',parent_id:'province-0',source_id:'reference'},{id:'location-😀',kind:'location',name:'Non BMP',parent_id:'province-0',source_id:'reference'});for(let i=0;i<more.length;i+=200)await importBatch(db,{entities:more.slice(i,i+200)});const ms=memberships([...entities,...more]),r=await manifest('paged',1,ms);await stage(db,r,[]);for(let i=0;i<ms.length;i+=200)await stageGeographicRelease(db,{release_id:r.id,memberships:ms.slice(i,i+200)});assert.equal((await finalizeGeographicRelease(db,r.id)).status,'published');assert.equal((await geographicRelease(db)).expected_counts.location,509);});

test('source-backed new territory publishes with a null predecessor and no invented historical attributes',async()=>{
 const {db,entities}=await fixture(),original=memberships(entities),first=await manifest('before-create',1,original);await stage(db,first,original);await finalizeGeographicRelease(db,first.id);
 await importBatch(db,{records:[{id:'original-history',location_id:'location-0',attribute:'population',value:42,valid_from:1000,valid_to:1001,source_id:'history',method:'direct',status:'sourced'}]});
 const added={id:'location-new-island',kind:'location',name:'Synthetic new island',parent_id:'province-0',source_id:'reference',metadata:{reference_only:true,history_transfer:'none'}};await importBatch(db,{entities:[added]});
 const creation={old_entity_id:null,new_entity_id:added.id,history_transfer:'none',creation_proof:{location_id:added.id,parent_chain:['province-0','area-0','region-0','subcontinent-0','continent-0'],source:{url:'https://example.org/synthetic',sha256:'c'.repeat(64),identity:'synthetic-source-island',license:'Synthetic fixture',attribution:'Synthetic test',supported_from:2026,supported_to:2027}}};
 const ms=memberships([...entities,added]),change={id:'create-island',old_entity_id:null,new_entity_id:added.id,change_type:'create',source_id:'reference',evidence:{reference_only:true,history_transfer:'none',geometry_creation:creation}};
 for(const kind of ['license','interval','history','parent']){const bad=structuredClone(change);bad.id='bad-create-'+kind;if(kind==='license')delete bad.evidence.geometry_creation.creation_proof.source.license;else if(kind==='interval')bad.evidence.geometry_creation.creation_proof.source.supported_from=0;else if(kind==='history')bad.evidence.geometry_creation.history_transfer='transfer';else bad.evidence.geometry_creation.creation_proof.parent_chain.pop();await assert.rejects(stage(db,await manifest('bad-release-'+kind,2,ms,[bad]),ms,[bad]));}
 const release=await manifest('after-create',2,ms,[change]);await stage(db,release,ms,[change]);await finalizeGeographicRelease(db,release.id);
 assert.equal((await referenceMembership(db,added.id)).membership.parent_id,'province-0');assert.equal((await geographicChangePage(db,{releaseId:release.id})).records[0].old_entity_id,null);
 assert.equal((await attributesAt(db,1000,{locationIds:[added.id]})).records.length,0);assert.equal((await attributesAt(db,1000,{locationIds:['location-0']})).records[0].value,42);assert.equal((await geographicRelease(db,first.id)).expected_counts.location,6);
 assert.throws(()=>db.sqlite.prepare('INSERT INTO atlas_geographic_changes(id,release_id,old_entity_id,new_entity_id,change_type,source_id,evidence) VALUES(?,?,?,?,?,?,?)').run('invalid-create',release.id,'location-0',added.id,'create','reference','{"source":"test"}'),/immutable|endpoints|CHECK/);
});
