import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {importBatch,attributesAt,namesAt,entityProfile,registerMedia,validateMedia,storageOverview,evidenceHistory} from '../hosted/records.js';

class D1 {
 constructor(){this.sqlite=new DatabaseSync(':memory:');this.sqlite.exec('PRAGMA foreign_keys=ON');for(const f of readdirSync(new URL('../drizzle/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())this.sqlite.exec(readFileSync(new URL(`../drizzle/${f}`,import.meta.url),'utf8'));if(!this.sqlite.prepare("SELECT 1 FROM sqlite_master WHERE type='trigger' AND name='atlas_entities_immutable'").get())this.sqlite.exec(readFileSync(new URL('../hosted/records-constraints.sql',import.meta.url),'utf8'));}
 prepare(sql){const sqlite=this.sqlite;let args=[];return {bind(...values){args=values;return this;},async all(){return {results:sqlite.prepare(sql).all(...args)};},async first(){return sqlite.prepare(sql).get(...args)??null;},run(){return {meta:{changes:Number(sqlite.prepare(sql).run(...args).changes)}};}};}
 async batch(statements){this.sqlite.exec('BEGIN IMMEDIATE');try{const result=statements.map(s=>s.run());this.sqlite.exec('COMMIT');return result;}catch(e){this.sqlite.exec('ROLLBACK');throw e;}}
}
const source=(id='historical',from=-3000,to=2027,status='historical')=>({id,name:`Source ${id}`,url:'https://example.org/evidence',license:'CC0-1.0',vintage:'2026',supported_from:from,supported_to:to,status});
const record=(id,attribute,value,extra={})=>({id,location_id:'location',attribute,value,valid_from:1000,valid_to:1100,source_id:'historical',...extra});
async function fixture(){const db=new D1();await importBatch(db,JSON.parse(readFileSync(new URL('../data/hosted-type-catalog.json',import.meta.url))));const kinds=['continent','subcontinent','region','area','province','location'];await importBatch(db,{sources:[source(),source('modern',2026,2027,'reference'),source('examples',-3000,2027,'example')],entities:kinds.map((kind,i)=>({id:kind,kind,name:kind,parent_id:i?kinds[i-1]:null})).reverse(),categories:[{id:'owner-a',kind:'owner',name:'Owner A',source_id:'historical'},{id:'culture-a',kind:'culture',name:'Culture A',source_id:'historical'}]});return db;}

test('profile titles prefer direct dated evidence over English reference attestations and opt-in examples',async()=>{
 const db=await fixture();try{
  await importBatch(db,{sources:[source('annual',2020,2021,'reference')],names:[
   {id:'a-reference',entity_id:'location',name:'Reference English name',language:'en',valid_from:2020,valid_to:2021,source_id:'annual'},
   {id:'z-direct',entity_id:'location',name:'Supported local name',language:'zh',valid_from:2020,valid_to:2021,source_id:'historical'},
   {id:'a-example',entity_id:'location',name:'Example English name',language:'en',valid_from:2020,valid_to:2021,source_id:'examples',is_example:1}
  ]});
  assert.equal((await entityProfile(db,'location',2020,{examples:true})).display_name,'Supported local name');
  assert.equal((await entityProfile(db,'location',2021)).display_name,null);
  assert.equal((await entityProfile(db,'location',2026)).display_name,'location');
 }finally{db.sqlite.close();}
});

test('hosted imports preserve whole-location raw values, precedence evidence and exact intervals',async()=>{const db=await fixture();await importBatch(db,{records:[record('owner-derived','owner','Owner A',{category_id:'owner-a',method:'majority-area',metadata:{winning_share:.61,competing_coverage:[['B',.39]]}}),record('owner-direct','owner',null),record('pop','population',42054)]});const result=await attributesAt(db,1000);assert.equal(result.records.length,3);assert.equal(result.records.find(r=>r.id==='owner-direct').value,null);assert.equal(result.records.find(r=>r.id==='owner-derived').metadata.winning_share,.61);assert.equal(result.records.find(r=>r.id==='pop').value,42054);assert.equal(result.records[0].source,'Source historical');assert.equal((await attributesAt(db,1100)).records.length,0);await assert.rejects(attributesAt(db,0),/year/);});

test('stable ID collisions roll back the entire batch and identical evidence stays idempotent',async()=>{const db=await fixture();const r=record('same','population',1);await importBatch(db,{ingestion_id:'first',records:[r]});assert.equal((await importBatch(db,{ingestion_id:'first',records:[r]})).duplicate,true);await importBatch(db,{ingestion_id:'identical-new-ingestion',records:[r]});await assert.rejects(importBatch(db,{ingestion_id:'collision',sources:[source('must-rollback')],records:[{...r,value:2}]}),/Stable ID collision/);assert.equal(db.sqlite.prepare("SELECT count(*) n FROM atlas_sources WHERE id='must-rollback'").get().n,0);assert.equal(db.sqlite.prepare("SELECT count(*) n FROM atlas_ingestions WHERE id='collision'").get().n,0);assert.equal((await attributesAt(db,1050)).records[0].value,1);await assert.rejects(importBatch(db,{entities:[{id:'dupe',kind:'person',name:'A'},{id:'dupe',kind:'person',name:'B'}]}),/Duplicate stable/);});

test('all tiers and nongeographic graph entities obey parent contracts',async()=>{const db=await fixture();await assert.rejects(importBatch(db,{entities:[{id:'bad',kind:'location',name:'Bad',parent_id:'continent'}]}),/adjacent/);await assert.rejects(importBatch(db,{entities:[{id:'person-bad',kind:'person',name:'Person',parent_id:'location'}]}),/adjacent/);await importBatch(db,{entities:[{id:'rome',kind:'settlement',name:'Rome',parent_id:'location'},{id:'person',kind:'person',name:'Person'}]});assert.equal((await entityProfile(db,'rome',2026)).parent_id,'location');await assert.rejects(importBatch(db,{entity_types:[{id:'location',name:'location',geographic_level:5}]}),/fixed tier/);assert.throws(()=>db.sqlite.exec("INSERT INTO atlas_entity_types(id,name,geographic_level) VALUES('custom-geography','Custom',0)"),/CHECK/);});

test('source intervals, category identity, typed scalars and habitation contradictions reject imports',async()=>{const db=await fixture();for(const r of [record('cat','owner','Owner A',{category_id:'culture-a'}),record('modern-ancient','climate','oceanic',{source_id:'modern',method:'reference'}),record('bad-pop','population',1.5),record('numeric','climate',2),record('zero','climate','oceanic',{valid_from:0})])await assert.rejects(importBatch(db,{records:[r]}));await importBatch(db,{records:[record('empty-land','habitation','uninhabited')]});await assert.rejects(importBatch(db,{records:[record('inhabited-pop','population',1)]}),/Uninhabited/);await assert.rejects(importBatch(db,{records:[record('inhabited-rank','rank','rural settlement')]}),/Uninhabited/);await importBatch(db,{records:[record('unknown-rank','rank',null)]});});

test('raw SQL protects typed records, Unicode blank evidence, no-year-zero and retained identity',async()=>{const db=await fixture();const insert=(id,attribute,value,from=1000,to=1100)=>db.sqlite.prepare("INSERT INTO atlas_attribute_records(id,location_id,attribute,value,valid_from,valid_to,method,status,source_id) VALUES(?,'location',?,?,?,?,'direct','sourced','historical')").run(id,attribute,value,from,to);assert.throws(()=>insert('numeric','climate','2'),/CHECK/);assert.throws(()=>insert('blank','climate',JSON.stringify('\u2003\t')),/blank/);assert.throws(()=>insert('zero','climate','"oceanic"',0,1),/CHECK/);assert.throws(()=>insert('fraction','climate','"oceanic"',1000.5,1100),/CHECK/);assert.throws(()=>db.sqlite.exec("UPDATE atlas_entities SET parent_id='continent' WHERE id='location'"),/sourced migration/);assert.throws(()=>db.sqlite.exec("DELETE FROM atlas_entities WHERE id='location'"),/retained/);assert.throws(()=>db.sqlite.prepare('INSERT INTO atlas_sources(id,name,license,vintage,supported_from,supported_to,status) VALUES(?,?,?,?,?,?,?)').run('blank-source','\u2003','CC0','2026',2026,2027,'reference'),/Empty/);});

test('dated names and graph claims are sourced, pageable and never silently become ancient names',async()=>{const db=await fixture();await importBatch(db,{entities:[{id:'person',kind:'person',name:'Modern Person',valid_from:900,valid_to:1200,source_id:'historical'},{id:'event',kind:'event',name:'Event'}],names:[{id:'name-1',entity_id:'location',name:'Old Location',valid_from:1000,valid_to:1100,source_id:'historical'},{id:'name-2',entity_id:'person',name:'Old Person',valid_from:1000,valid_to:1100,source_id:'historical'}],relationships:[{id:'claim',source_entity_id:'person',target_entity_id:'location',relationship_type:'visited',valid_from:1000,valid_to:1001,source_id:'historical'},{id:'undated',source_entity_id:'event',target_entity_id:'location',relationship_type:'associated_with',source_id:'historical'}]});const page=await namesAt(db,1000,{limit:1});assert.equal(page.records.length,1);assert.ok(page.next_cursor);assert.equal((await namesAt(db,1000,{cursor:page.next_cursor})).records.length,1);assert.equal(page.records[0].field,'name');assert.equal((await entityProfile(db,'location',1000)).display_name,'Old Location');assert.equal((await entityProfile(db,'location',1100)).display_name,null);const profile=await entityProfile(db,'location',1001);assert.deepEqual(profile.relationships.map(r=>[r.id,r.date_status]),[['undated','unknown']]);await assert.rejects(importBatch(db,{names:[{id:'outside-life',entity_id:'person',name:'Too Early',valid_from:800,valid_to:900,source_id:'historical'}]}),/lifetime/);});

test('examples remain opt-in and bounded attribute pages preserve every location record',async()=>{const db=await fixture();await assert.rejects(importBatch(db,{records:[record('bad-example','climate','oceanic',{source_id:'examples'})]}),/opt-in/);await importBatch(db,{records:[record('example','climate','oceanic',{source_id:'examples',is_example:1}),record('pop','population',2),record('veg','vegetation','farmlands')]});const page=await attributesAt(db,1000,{limit:1});assert.equal(page.records.length,1);assert.ok(page.next_cursor);assert.equal((await attributesAt(db,1000,{cursor:page.next_cursor})).records.length,1);assert.equal((await attributesAt(db,1000,{examples:true})).records.length,3);assert.equal((await attributesAt(db,1000,{locationIds:[]})).records.length,0);await assert.rejects(importBatch(db,{entities:Array.from({length:251},(_,i)=>({id:`person-${i}`,kind:'person',name:'Person'}))}),/250/);});

test('media metadata is immutable and content-addressed with retained sourced links',async()=>{const db=await fixture(),sha='a'.repeat(64),input={id:'image',object_key:`media/${sha}`,sha256:sha,bytes:42,mime:'image/png',name:'Map',license:'CC0',attribution:'Author',source_id:'historical'};assert.equal((await validateMedia(db,input)).existing,false);await registerMedia(db,input);assert.equal((await validateMedia(db,input)).existing,true);await assert.rejects(validateMedia(db,{...input,bytes:43}),/immutable/);await assert.rejects(validateMedia(db,{...input,id:'duplicate-digest'}),/registered identity/);await importBatch(db,{media_links:[{id:'image-link',media_id:'image',entity_id:'location',role:'reference-map',source_id:'historical'}]});const profile=await entityProfile(db,'location',1000);assert.equal(profile.media[0].object_key,input.object_key);assert.equal(profile.media[0].date_status,'unknown');assert.throws(()=>db.sqlite.exec("UPDATE atlas_media SET bytes=43 WHERE id='image'"),/immutable/);assert.throws(()=>db.sqlite.prepare('INSERT INTO atlas_media(id,object_key,sha256,bytes,mime,name,license,attribution,source_id) VALUES(?,?,?,?,?,?,?,?,?)').run('bad',`media/${'g'.repeat(64)}`,'g'.repeat(64),1,'image/png','Bad','CC0','Author','historical'),/CHECK/);assert.equal((await storageOverview(db)).media_bytes,42);});

test('raw SQL rejects half-dated graph and media links',async()=>{const db=await fixture();assert.throws(()=>db.sqlite.exec("INSERT INTO atlas_relationships(id,source_entity_id,target_entity_id,relationship_type,valid_from,source_id) VALUES('partial','location','region','in',1000,'historical')"),/CHECK/);});

test('dated graph assertions cannot exceed known endpoint lifetimes',async()=>{const db=await fixture();await importBatch(db,{entities:[{id:'person',kind:'person',name:'Person',valid_from:900,valid_to:1200,source_id:'historical'}]});await assert.rejects(importBatch(db,{relationships:[{id:'outside',source_entity_id:'person',target_entity_id:'location',relationship_type:'visited',valid_from:800,valid_to:1000,source_id:'historical'}]}),/lifetime/);await importBatch(db,{relationships:[{id:'unknown',source_entity_id:'person',target_entity_id:'location',relationship_type:'associated_with',source_id:'historical'}]});assert.equal((await entityProfile(db,'person',800)).display_name,null);});

test('category IDs are shared graph identities and fictional entities remain opt-in',async()=>{const db=await fixture();assert.equal((await entityProfile(db,'owner-a',2026)).kind,'polity');await importBatch(db,{entities:[{id:'fictional',kind:'person',name:'Fictional Person',source_id:'examples',is_example:1}],names:[{id:'fictional-name',entity_id:'fictional',name:'Example',valid_from:1000,valid_to:1100,source_id:'examples',is_example:1}],relationships:[{id:'fictional-link',source_entity_id:'fictional',target_entity_id:'location',relationship_type:'visited',source_id:'examples',is_example:1}]});assert.equal(await entityProfile(db,'fictional',1000),null);assert.equal((await entityProfile(db,'fictional',1000,{examples:true})).display_name,'Example');assert.equal((await namesAt(db,1000)).records.length,0);assert.equal((await namesAt(db,1000,{examples:true})).records.length,1);assert.equal((await entityProfile(db,'location',1000)).relationships.length,0);assert.equal((await entityProfile(db,'location',1000,{examples:true})).relationships.length,1);await assert.rejects(importBatch(db,{entities:[{id:'hidden-example',kind:'person',name:'Example',source_id:'examples'}]}),/opt-in/);const payload={ingestion_id:'new-category',categories:[{id:'new-culture',kind:'culture',name:'Culture',source_id:'historical'}]};await importBatch(db,payload);assert.equal((await importBatch(db,payload)).duplicate,true);await importBatch(db,{entities:[{id:'wrong-kind',kind:'person',name:'Person'}]});await assert.rejects(importBatch(db,{categories:[{id:'wrong-kind',kind:'owner',name:'Wrong',source_id:'historical'}]}),/matching graph/);});

test('example media on real locations stays opt-in regardless of link source',async()=>{const db=await fixture(),sha='b'.repeat(64);await registerMedia(db,{id:'example-image',object_key:`media/${sha}`,sha256:sha,bytes:1,mime:'image/png',name:'Example',license:'CC0',attribution:'Author',source_id:'examples'});const link={id:'example-link',media_id:'example-image',entity_id:'location',role:'illustration',source_id:'historical'};await assert.rejects(importBatch(db,{media_links:[link]}),/opt-in/);await importBatch(db,{media_links:[{...link,is_example:1}]});assert.equal((await entityProfile(db,'location',1000)).media.length,0);assert.equal((await entityProfile(db,'location',1000,{examples:true})).media.length,1);});

test('reference and estimate source classes cannot masquerade as direct evidence',async()=>{const db=await fixture();await importBatch(db,{sources:[source('estimates',-3000,2027,'estimate')]});await assert.rejects(importBatch(db,{records:[record('bad-reference','climate','oceanic',{valid_from:2026,valid_to:2027,source_id:'modern'})]}),/Source class/);await assert.rejects(importBatch(db,{records:[record('bad-estimate','population',12,{source_id:'estimates'})]}),/Source class/);await importBatch(db,{records:[record('reference','climate','oceanic',{valid_from:2026,valid_to:2027,source_id:'modern',method:'reference'}),record('estimate','population',12,{source_id:'estimates',method:'estimate'})]});assert.equal((await attributesAt(db,2026)).records[0].status,'reference');assert.equal((await attributesAt(db,1000)).records[0].status,'estimate');});

const retire=(id,collection,target_id,replacement_id=null,extra={})=>({id,collection,target_id,replacement_id,source_id:'modern',reason:'Source review corrected this claim',...extra});

test('sourced corrections supersede attributes atomically while preserving old evidence',async()=>{const db=await fixture();await importBatch(db,{records:[record('old-pop','population',42)]});const payload={ingestion_id:'correct-population',retirements:[retire('retire-pop','records','old-pop','new-pop')],records:[record('new-pop','population',43)]};const imported=await importBatch(db,payload);assert.equal(imported.counts.retirements,1);assert.deepEqual((await attributesAt(db,1000)).records.map(r=>[r.id,r.value]),[['new-pop',43]]);const history=await evidenceHistory(db,'records','old-pop');assert.equal(history.claim.value,42);assert.equal(history.status,'superseded');assert.equal(history.retirement.source_from,2026,'audit source date is independent of ancient claim interval');assert.equal(history.replacement.value,43);assert.equal((await importBatch(db,payload)).duplicate,true);await importBatch(db,{records:[record('old-pop','population',42)]});assert.deepEqual((await attributesAt(db,1000)).records.map(r=>r.id),['new-pop'],'idempotent old evidence reimport never reactivates it');assert.equal(db.sqlite.prepare('SELECT count(*) n FROM atlas_attribute_records').get().n,2);});

test('dated name corrections and habitation withdrawal update every reader and conflict check',async()=>{const db=await fixture();await importBatch(db,{names:[{id:'old-name',entity_id:'location',name:'Old',valid_from:1000,valid_to:1100,source_id:'historical'}],records:[record('uninhabited','habitation','uninhabited')]});await importBatch(db,{retirements:[retire('rename','names','old-name','new-name'),retire('habitation-review','records','uninhabited')],names:[{id:'new-name',entity_id:'location',name:'Corrected',valid_from:1000,valid_to:1100,source_id:'historical'}],records:[record('inhabited','habitation','inhabited'),record('new-pop','population',10),record('rank','rank','town')]});assert.equal((await namesAt(db,1000)).records[0].value,'Corrected');assert.equal((await entityProfile(db,'location',1000)).display_name,'Corrected');assert.equal((await evidenceHistory(db,'names','old-name')).claim.name,'Old');assert.equal((await evidenceHistory(db,'records','uninhabited')).status,'withdrawn');assert.equal((await attributesAt(db,1000)).records.length,3);});

test('withdrawn relationships and media links disappear from profiles but remain inspectable',async()=>{const db=await fixture(),sha='c'.repeat(64);await registerMedia(db,{id:'map',object_key:`media/${sha}`,sha256:sha,bytes:3,mime:'image/png',name:'Map',license:'CC0',attribution:'Author',source_id:'historical'});await importBatch(db,{relationships:[{id:'claim',source_entity_id:'location',target_entity_id:'region',relationship_type:'associated_with',source_id:'historical'}],media_links:[{id:'media-claim',media_id:'map',entity_id:'location',role:'map',source_id:'historical'}]});await importBatch(db,{retirements:[retire('withdraw-link','relationships','claim'),retire('withdraw-media','media_links','media-claim')]});const profile=await entityProfile(db,'location',1000);assert.equal(profile.relationships.length,0);assert.equal(profile.media.length,0);assert.equal((await evidenceHistory(db,'relationships','claim')).status,'withdrawn');assert.equal((await evidenceHistory(db,'media_links','media-claim')).claim.media_id,'map');assert.equal((await storageOverview(db)).counts.media,1,'retiring a link never retires immutable media content');});

test('failed replacements roll back retirements and the ingestion ledger together',async()=>{const db=await fixture();await importBatch(db,{records:[record('old','population',1)]});await assert.rejects(importBatch(db,{ingestion_id:'failed-correction',retirements:[retire('retire-old','records','old','broken')],records:[record('broken','population',2,{source_id:'missing-source'})]}),/FOREIGN KEY/);assert.equal((await attributesAt(db,1000)).records[0].id,'old');assert.equal(db.sqlite.prepare('SELECT count(*) n FROM atlas_evidence_retirements').get().n,0);assert.equal(db.sqlite.prepare("SELECT count(*) n FROM atlas_ingestions WHERE id='failed-correction'").get().n,0);await assert.rejects(importBatch(db,{retirements:[retire('missing-replacement','records','old','absent')]}),/Replacement claim/);await assert.rejects(importBatch(db,{retirements:[retire('missing-target','records','absent')]}),/must exist/);});

test('raw SQL keeps retirement provenance sourced, immutable, unique and atomically finalized',async()=>{const db=await fixture();await importBatch(db,{records:[record('old','population',1)]});const insert=(id,target,source_id='modern',reason='Review',replacement_id=null)=>db.sqlite.prepare('INSERT INTO atlas_evidence_retirements(id,collection,target_id,source_id,reason,replacement_id) VALUES(?,?,?,?,?,?)').run(id,'records',target,source_id,reason,replacement_id);assert.throws(()=>insert('missing','old','absent'),/FOREIGN KEY/);assert.throws(()=>insert('blank','old','modern','\u2003'),/Empty/);assert.throws(()=>insert('fake-audit','old','examples'),/Example sources/);db.sqlite.exec('BEGIN');insert('incomplete','old','modern','Review','missing-replacement');assert.throws(()=>db.sqlite.prepare('INSERT INTO atlas_ingestions(id,fingerprint,counts,created_at) VALUES(?,?,?,?)').run('incomplete-import','d'.repeat(64),JSON.stringify({_retirement_ids:['incomplete']}),Date.now()),/Replacement claim is missing/);db.sqlite.exec('ROLLBACK');assert.equal((await attributesAt(db,1000)).records[0].id,'old');insert('withdraw','old');assert.throws(()=>insert('withdraw','old','modern','Different reason'),/Stable ID collision/);assert.throws(()=>insert('other-withdraw','old'),/already retired/);assert.throws(()=>db.sqlite.exec("UPDATE atlas_evidence_retirements SET reason='Different' WHERE id='withdraw'"),/immutable/);assert.throws(()=>db.sqlite.exec("DELETE FROM atlas_evidence_retirements WHERE id='withdraw'"),/retained/);});

test('supersession chains remain traceable and cannot form cycles',async()=>{const db=await fixture();await importBatch(db,{records:[record('first','population',1)]});await importBatch(db,{retirements:[retire('first-retirement','records','first','second')],records:[record('second','population',2)]});await assert.rejects(importBatch(db,{retirements:[retire('cycle','records','second','first')]}),/cycle/);await importBatch(db,{retirements:[retire('second-retirement','records','second','third')],records:[record('third','population',3)]});assert.equal((await attributesAt(db,1000)).records[0].value,3);assert.equal((await evidenceHistory(db,'records','first')).replacement.id,'second');assert.equal((await evidenceHistory(db,'records','second')).replacement.id,'third');});

test('evidence history keeps fictional claims opt-in after retirement',async()=>{const db=await fixture();await importBatch(db,{records:[record('example-claim','climate','oceanic',{source_id:'examples',is_example:1})]});await importBatch(db,{retirements:[retire('example-retirement','records','example-claim')]});assert.equal(await evidenceHistory(db,'records','example-claim'),null);assert.equal((await evidenceHistory(db,'records','example-claim',{examples:true})).status,'withdrawn');assert.equal((await attributesAt(db,1000,{examples:true})).records.length,0);});

test('map name paging excludes future graph names while default queries retain them',async()=>{const db=await fixture();await importBatch(db,{entities:[{id:'person',kind:'person',name:'Person'},{id:'settlement',kind:'settlement',name:'Settlement',parent_id:'location'}],names:[{id:'a-person-name',entity_id:'person',name:'Person Name',valid_from:1000,valid_to:1100,source_id:'historical'},{id:'b-location-name',entity_id:'location',name:'Location Name',valid_from:1000,valid_to:1100,source_id:'historical'},{id:'c-settlement-name',entity_id:'settlement',name:'Settlement Name',valid_from:1000,valid_to:1100,source_id:'historical'}]});assert.deepEqual((await namesAt(db,1000)).records.map(r=>r.entity_id),['person','location','settlement']);const page=await namesAt(db,1000,{mapOnly:true,limit:1});assert.deepEqual(page.records.map(r=>r.entity_id),['location']);assert.equal(page.next_cursor,'b-location-name');assert.deepEqual((await namesAt(db,1000,{mapOnly:true,cursor:page.next_cursor})).records.map(r=>r.entity_id),['settlement']);});
