import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {gzipSync} from 'node:zlib';
import {install,validate,hash,safe,verifySourceGeometry} from '../scripts/install-reviewed-geography.mjs';import {stageLandCreations} from '../scripts/stage-land-creations.mjs';import {footprintHash} from '../scripts/check-prepared.mjs';import {packOwnership} from '../src/pixel-ownership.js';import {shuffleOwnershipBytes} from '../src/ownership-codec.js';
const put=(file,data)=>{fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,typeof data==='string'?data:JSON.stringify(data));return hash(fs.readFileSync(file));};
const zip=(file,data)=>{fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,gzipSync(JSON.stringify(data)));return {path:path.basename(file),sha256:hash(fs.readFileSync(file))};};
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'atlas-install-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const data=path.join(dir,'data'),candidate=path.join(dir,'geography'),ownership=path.join(dir,'ownership'),runtime=path.join(dir,'runtime'),references=path.join(dir,'references'),grid=path.join(dir,'grid');for(const d of [data,candidate,ownership,runtime,references,grid])fs.mkdirSync(d);
 const features=Array.from({length:6},(_,i)=>({type:'Feature',id:'loc'+i,properties:{id:'loc'+i,name:'Location '+i,parent_id:'prov'+i,reference_owner:'Owner '+i},geometry:{type:'Polygon',coordinates:[[[i*2,0],[i*2+1,0],[i*2+1,1],[i*2,1],[i*2,0]]]}}));
 const units=features.flatMap((f,i)=>['province','area','region','subcontinent','continent'].map((level,j)=>({id:['prov','area','region','sub','continent'][j]+i,name:j===4?['Africa','Asia','Europe','North America','Oceania','South America'][i]:level+i,level,parent_id:j===4?null:['prov','area','region','sub','continent'][j+1]+i,metadata:{}})));const after=structuredClone(features);after[0].geometry.coordinates[0][1][0]=1.1;
 for(const [directory,fsx] of [[data,features],[candidate,after]]){put(directory+'/world-index.json',{parts:['geography/part.json']});put(directory+'/geography/part.json',{features:fsx});put(directory+'/hierarchy.json',units);}
 put(data+'/atlas.sqlite','original historical fixture');put(data+'/atlas.sqlite.previous','original archived historical fixture');put(data+'/hosted-catalog/index.json',{immutable:true});put(data+'/geographic-migration-archive.json.gz','original source archive');
 const oldOwner={version:2,footprints_sha256:footprintHash(features)},oldReference={version:2,types:[{attribute:'climate',valid_from:2026,valid_to:2027}],values:['oceanic']};put(data+'/ownership-history/index.json',oldOwner);put(data+'/ownership-history/original.json','old ownership payload');put(data+'/reference-attributes/index.json',oldReference);put(data+'/reference-attributes/original.json','old reference payload');put(data+'/ownership-runtime/index.json',{old:true});put(data+'/pixel-audit.json',{old:true});
 const sourceReceipt=dir+'/source-receipt.json',macroReceipt=dir+'/macro-receipt.json',gridAudit=dir+'/grid-audit.json',gridSourceAreas=dir+'/source-areas.json';const before=footprintHash(features),afterHash=footprintHash(after),hierarchy=hash(fs.readFileSync(candidate+'/hierarchy.json'));
 put(sourceReceipt,{before_footprints_sha256:before,after_footprints_sha256:afterHash,historical_claims_transferred:0,geometry_stage_validated:true,source_evidence:[{url:'https://example.org/fixture'}]});
 const counts={location:6,province:6,area:6,region:6,subcontinent:6,continent:6};put(macroReceipt,{historical_claims_transferred:false,source_repair_receipt_sha256:hash(fs.readFileSync(sourceReceipt)),unchanged_geometry_ids:after.map(f=>f.id),counts});
 const algHash=put(ownership+'/algorithms/fixture.py','# test-only source algorithm\n'),alg={path:'algorithms/fixture.py',sha256:algHash};const identity=zip(ownership+'/identities.json.gz',[]),part=zip(ownership+'/part.json.gz',after.map(f=>[f.id,[[1,100,0,0,0]]])),evidence=zip(ownership+'/evidence.json.gz',[[0,1,1,[],[],0]]),archive=zip(ownership+'/archive.json.gz',[]);
 put(ownership+'/archive-index.json',{original_index_sha256:hash(fs.readFileSync(data+'/ownership-history/index.json')),parts:[archive]});const ownerIndex={version:2,locations:6,footprints_sha256:afterHash,intervals:6,parts:[part],evidence_parts:[evidence],execution_algorithms:[alg],initial_execution:{algorithms:[alg]},incremental_preparation:{original_index_sha256:hash(fs.readFileSync(data+'/ownership-history/index.json')),migration_receipt_sha256:hash(fs.readFileSync(sourceReceipt)),wrapper:alg,identity_map:identity,archive_path:'archive-index.json'}};put(ownership+'/index.json',ownerIndex);
 const rp=zip(references+'/part.json.gz',after.map(f=>[f.id,[[0,0,1,1]]])),ra=zip(references+'/archive.json.gz',[]);const rr={original_index_sha256:hash(fs.readFileSync(data+'/reference-attributes/index.json')),after_footprints_sha256:afterHash,migration_receipt_sha256:hash(fs.readFileSync(sourceReceipt)),historical_claims_transferred:false,source_intervals_unchanged:true,source_dictionaries_prefix_preserved:true,archive:ra};put(references+'/incremental-receipt.json',rr);put(references+'/index.json',{version:2,locations:6,footprints_sha256:afterHash,parts:[rp.path],parts_sha256:{[rp.path]:rp.sha256},records:6,types:oldReference.types,values:oldReference.values,incremental_preparation:{receipt_sha256:hash(fs.readFileSync(references+'/incremental-receipt.json'))}});
 const rb=zip(runtime+'/bucket.json.gz',{});put(runtime+'/index.json',{source_index_sha256:hash(fs.readFileSync(ownership+'/index.json')),shared:{footprints_sha256:afterHash},footprints_sha256:afterHash,buckets:[rb]});
 const rows=Array.from({length:8},()=>new Uint32Array());rows[1]=new Uint32Array(after.flatMap((f,i)=>[i,i+1,i+1]));const packed=packOwnership({size:8,rows});const assets=['rows','runs'].map(kind=>{const bytes=Buffer.from(shuffleOwnershipBytes(packed[kind]));const name='ownership/'+kind+'.bin.gz';fs.mkdirSync(grid+'/ownership',{recursive:true});fs.writeFileSync(grid+'/'+name,gzipSync(bytes));return {kind,offset:0,words:packed[kind].length,path:name,encoding:'byte-shuffle',sha256:hash(fs.readFileSync(grid+'/'+name)),decoded_sha256:hash(Buffer.from(packed[kind].buffer))};});
 const provinces=after.map(f=>f.properties.parent_id),bounds=zip(grid+'/bounds.json.gz',after.map((f,i)=>({id:f.id,index:i+1,province_id:f.properties.parent_id,province_index:i+1,bounds:[i,1,i+1,2]})));const membership=new Uint32Array([0,1,2,3,4,5,6]);fs.writeFileSync(grid+'/membership.bin.gz',gzipSync(Buffer.from(membership.buffer)));put(grid+'/manifest.json',{version:2,coordinateBits:3,size:8,runWords:packed.runs.length,parts:assets,footprints_sha256:afterHash,hierarchy_sha256:hierarchy,stats:{locations:6},provinces,bounds,province_membership:{path:'membership.bin.gz',sha256:hash(fs.readFileSync(grid+'/membership.bin.gz'))}});
 put(gridAudit,{size:8,zoom:-5,footprints_sha256:afterHash,missing:[],represented:6,location_ids:after.map(f=>f.id),cell_counts:after.map(()=>1),grid_wgs84_area_m2:after.map(()=>1),covered_cells:6});put(gridSourceAreas,{footprints_sha256:afterHash,algorithms:[],areas:Object.fromEntries(after.map(f=>[f.id,1]))});
 const options={data,geography:candidate,ownership,runtime,references,grid,sourceReceipt,macroReceipt,gridAudit,gridSourceAreas};return {dir,options,after,features};}
function snapshot(directory){const result={};const visit=(dir,prefix='')=>{for(const e of fs.readdirSync(dir,{withFileTypes:true})){const name=prefix+e.name;if(e.isDirectory())visit(path.join(dir,e.name),name+'/');else result[name]=hash(fs.readFileSync(path.join(dir,e.name)));}};visit(directory);return result;}
test('dry run validates a whole generation without changing any live bytes',t=>{const f=fixture(t),before=snapshot(f.options.data),result=install(f.options);assert.equal(result.dry_run,true);assert.deepEqual(snapshot(f.options.data),before);assert.equal(result.grid.represented,6);assert.equal(result.grid.missing,0);assert.equal(result.sqlite_mutated,false);});
test('apply requires the exact dry-run hash and preserves database/catalog/history originals',t=>{const f=fixture(t);assert.throws(()=>install(f.options,{apply:true}),/explicit validated/);const before=snapshot(f.options.data),dry=install(f.options);const result=install({...f.options,expectedValidation:dry.validation_sha256},{apply:true});assert.equal(result.applied,true);for(const name of ['atlas.sqlite','atlas.sqlite.previous','hosted-catalog/index.json','geographic-migration-archive.json.gz'])assert.equal(snapshot(f.options.data)[name],before[name]);assert.equal(hash(fs.readFileSync(result.backup+'/ownership-history/index.json')),before['ownership-history/index.json']);assert.equal(JSON.parse(fs.readFileSync(f.options.data+'/publication-geography-receipt.json')).grid.missing,0);assert.ok(fs.existsSync(f.options.data+'/canonical-grid/manifest.json'));assert.ok(!fs.existsSync(f.options.data+'/.geography-install.lock'));});
test('failure during the multi-path commit restores every original live byte',t=>{const f=fixture(t),before=snapshot(f.options.data),dry=install(f.options);assert.throws(()=>install({...f.options,expectedValidation:dry.validation_sha256},{apply:true,failAfter:5}),/Injected transaction failure/);assert.deepEqual(snapshot(f.options.data),before);assert.ok(!fs.existsSync(f.options.data+'/.geography-install.lock'));});
test('stale runtime, prepared source hashes, province membership and grid counts fail before activation',t=>{for(const kind of ['runtime','reference-part','membership','counts','candidate-chain']){const f=fixture(t);let target; if(kind==='runtime'){target=f.options.runtime+'/index.json';const x=JSON.parse(fs.readFileSync(target));x.source_index_sha256='wrong';put(target,x);}else if(kind==='reference-part'){target=f.options.references+'/part.json.gz';fs.appendFileSync(target,'x');}else if(kind==='membership'){target=f.options.grid+'/membership.bin.gz';fs.appendFileSync(target,'x');}else if(kind==='counts'){target=f.options.gridAudit;const x=JSON.parse(fs.readFileSync(target));x.cell_counts[0]=2;put(target,x);}else{target=f.options.geography+'/geography/part.json';const x=JSON.parse(fs.readFileSync(target));x.features[0].properties.parent_id='area0';put(target,x);}const before=snapshot(f.options.data);assert.throws(()=>install(f.options));assert.deepEqual(snapshot(f.options.data),before);}});
test('approved hashes prevent changes between inspection and activation',t=>{const f=fixture(t),dry=install(f.options);put(f.options.grid+'/new-unreviewed-file.json',{unreviewed:true});assert.throws(()=>install({...f.options,expectedValidation:dry.validation_sha256},{apply:true}),/approved dry-run hash/);});
test('unexpected predecessor files or changed historical payload block approved activation',t=>{for(const kind of ['new-file','history']){const f=fixture(t),dry=install(f.options);put(f.options.data+(kind==='new-file'?'/unexpected.json':'/atlas.sqlite'),kind);const before=snapshot(f.options.data);assert.throws(()=>install({...f.options,expectedValidation:dry.validation_sha256},{apply:true}),/approved dry-run hash/);assert.deepEqual(snapshot(f.options.data),before);}});
test('path traversal and staging symlinks cannot replace unrelated files',t=>{const f=fixture(t);assert.throws(()=>safe(f.options.data,'../atlas.sqlite'),/escapes/);fs.symlinkSync(f.options.data+'/atlas.sqlite',f.options.grid+'/database-link');assert.throws(()=>install(f.options),/symlinks/);});
test('duplicate geographic identities and empty groups cannot pass as a complete hierarchy',t=>{const f=fixture(t),x=JSON.parse(fs.readFileSync(f.options.geography+'/hierarchy.json'));x.push({...x[0],id:'empty-province'});put(f.options.geography+'/hierarchy.json',x);assert.throws(()=>install(f.options),/Empty geographic group/);});

test('a genuine unknown-attribute creation installs reversibly without changing original history',t=>{
 const f=fixture(t),o=f.options,read=p=>JSON.parse(fs.readFileSync(p)),added={type:'Feature',id:'new-island',properties:{id:'new-island',name:'Synthetic island',parent_id:'prov0',reference_owner:null},geometry:{type:'Polygon',coordinates:[[[20,0],[21,0],[21,1],[20,1],[20,0]]]}},all=[...f.after,added],footprints=footprintHash(all);
 put(o.geography+'/geography/part.json',{features:all});const source={type:'Feature',id:'synthetic-island-source',properties:{name:'Synthetic island'},geometry:added.geometry},sourcePath=f.dir+'/creation-source.json';put(sourcePath,source);
 const receipt=read(o.sourceReceipt);receipt.after_footprints_sha256=footprints;receipt.creation_proofs=[{location_id:added.id,parent_chain:['prov0','area0','region0','sub0','continent0'],source:{path:'creation-source.json',sha256:hash(fs.readFileSync(sourcePath)),identity:source.id,url:'https://example.org/synthetic',license:'Synthetic test',attribution:'Synthetic fixture',supported_from:2026,supported_to:2027},identity_review:{status:'distinct-new-territory',evidence_url:'https://example.org/synthetic-identity',rationale:'Synthetic absent land'}}];put(o.sourceReceipt,receipt);
 const owner=read(o.ownership+'/index.json');owner.locations=7;owner.footprints_sha256=footprints;owner.parts=[zip(o.ownership+'/part.json.gz',[...f.after.map(v=>[v.id,[[1,100,0,0,0]]]),[added.id,[]]])];owner.incremental_preparation.migration_receipt_sha256=hash(fs.readFileSync(o.sourceReceipt));put(o.ownership+'/index.json',owner);
 const reference=read(o.references+'/index.json'),rr=read(o.references+'/incremental-receipt.json');rr.after_footprints_sha256=footprints;rr.migration_receipt_sha256=hash(fs.readFileSync(o.sourceReceipt));put(o.references+'/incremental-receipt.json',rr);reference.locations=7;reference.footprints_sha256=footprints;reference.incremental_preparation.receipt_sha256=hash(fs.readFileSync(o.references+'/incremental-receipt.json'));put(o.references+'/index.json',reference);
 const runtime=read(o.runtime+'/index.json');runtime.source_index_sha256=hash(fs.readFileSync(o.ownership+'/index.json'));runtime.footprints_sha256=runtime.shared.footprints_sha256=footprints;put(o.runtime+'/index.json',runtime);
 const macro=read(o.macroReceipt);macro.counts.location=7;macro.unchanged_geometry_ids=all.map(v=>v.id);macro.source_repair_receipt_sha256=hash(fs.readFileSync(o.sourceReceipt));put(o.macroReceipt,macro);
 const grid=read(o.grid+'/manifest.json'),rows=Array.from({length:8},()=>new Uint32Array());rows[1]=new Uint32Array(all.flatMap((v,i)=>[i,i+1,i+1]));const packed=packOwnership({size:8,rows});grid.runWords=packed.runs.length;
 for(const part of grid.parts){const words=packed[part.kind];fs.writeFileSync(o.grid+'/'+part.path,gzipSync(Buffer.from(shuffleOwnershipBytes(words))));part.words=words.length;part.sha256=hash(fs.readFileSync(o.grid+'/'+part.path));part.decoded_sha256=hash(Buffer.from(words.buffer));}
 grid.bounds=zip(o.grid+'/bounds.json.gz',all.map((v,i)=>({id:v.id,index:i+1,province_id:v.properties.parent_id,province_index:i<6?i+1:1,bounds:[i,1,i+1,2]})));fs.writeFileSync(o.grid+'/membership.bin.gz',gzipSync(Buffer.from(new Uint32Array([0,1,2,3,4,5,6,1]).buffer)));grid.province_membership.sha256=hash(fs.readFileSync(o.grid+'/membership.bin.gz'));grid.footprints_sha256=footprints;grid.stats.locations=7;put(o.grid+'/manifest.json',grid);
 const audit=read(o.gridAudit);audit.footprints_sha256=footprints;audit.represented=7;audit.location_ids.push(added.id);audit.cell_counts.push(1);audit.grid_wgs84_area_m2.push(1);audit.covered_cells=7;put(o.gridAudit,audit);const areas=read(o.gridSourceAreas);areas.footprints_sha256=footprints;areas.areas[added.id]=1;put(o.gridSourceAreas,areas);
 const before=snapshot(o.data),dry=install(o);assert.equal(dry.counts_after.location,7);assert.throws(()=>install({...o,expectedValidation:dry.validation_sha256},{apply:true,failAfter:5}),/Injected/);assert.deepEqual(snapshot(o.data),before);
 const actual=install({...o,expectedValidation:dry.validation_sha256},{apply:true});assert.equal(actual.counts_after.location,7);assert.equal(snapshot(o.data)['atlas.sqlite'],before['atlas.sqlite']);assert.equal(snapshot(o.data)['hosted-catalog/index.json'],before['hosted-catalog/index.json']);
});

function composedFixture(t){
 const f=fixture(t),units=JSON.parse(fs.readFileSync(f.options.data+'/hierarchy.json')),replacement=path.join(f.dir,'replacement-migration');fs.mkdirSync(replacement);
 const replacementReceipt={geometry_stage_validated:true,historical_claims_transferred:false,before_footprints_sha256:footprintHash(f.features),after_footprints_sha256:footprintHash(f.after),changed_ids:['loc0'],removed_ids:[],added_ids:[],reused_ids:f.features.slice(1).map(v=>v.id),archives:[{id:'loc0',feature:f.features[0]}],relationships:[{before_ids:['loc0'],after_ids:['loc0'],history_transfer:false}],source_evidence:[{url:'https://example.org/synthetic-replacement',source_sha256:'a'.repeat(64)}]};
 const receiptHash=put(replacement+'/migration-receipt.json',replacementReceipt),manifest={history_transfer:false,before_footprints_sha256:replacementReceipt.before_footprints_sha256,after_footprints_sha256:replacementReceipt.after_footprints_sha256,files:{'migration-receipt.json':{sha256:receiptHash}}};put(replacement+'/index.json',manifest);
 const added={type:'Feature',id:'new-island',properties:{id:'new-island',name:'Synthetic island',parent_id:'prov0',reference_owner:null},geometry:{type:'Polygon',coordinates:[[[20,0],[21,0],[21,1],[20,1],[20,0]]]}},next=[...f.after,added],candidate=f.dir+'/creation',source=f.dir+'/source.geojson',proofs=f.dir+'/proofs.json';
 put(candidate+'/hierarchy.json',units);put(candidate+'/world-index.json',{parts:['geography/part.json']});put(candidate+'/geography/part.json',{features:next});
 const sourceFeature={...added,id:'source-new-island'};put(source,sourceFeature);
 put(proofs,[{location_id:added.id,parent_chain:['prov0','area0','region0','sub0','continent0'],source:{path:'source.geojson',sha256:hash(fs.readFileSync(source)),identity:sourceFeature.id,url:'https://example.org/synthetic-island',license:'Synthetic fixture',attribution:'Synthetic test only',supported_from:2026,supported_to:2027},identity_review:{status:'distinct-new-territory',evidence_url:'https://example.org/synthetic-identity',rationale:'Synthetic distinct land'}}]);
 stageLandCreations({before:f.options.geography,after:candidate,proofs,output:f.dir+'/creation-migration'});
 const read=p=>JSON.parse(fs.readFileSync(p)),creation=read(f.dir+'/creation-migration/migration-receipt.json'),aggregate={...replacementReceipt,after_footprints_sha256:footprintHash(next),added_ids:[added.id],creation_proofs:creation.creation_proofs.map(p=>({...p,source:{...p.source,path:'creation-migration/'+p.source.path}}))};put(f.options.sourceReceipt,aggregate);
 const geometryProofs=f.dir+'/geometry-proofs.json',descriptor={version:1,before_footprints_sha256:footprintHash(f.features),after_footprints_sha256:footprintHash(next),manifests:['replacement-migration/index.json','creation-migration/index.json'].map(path=>({path,sha256:hash(fs.readFileSync(f.dir+'/'+path))})),metadata_receipts:[]};put(geometryProofs,descriptor);
 return {...f,units,next,aggregate,descriptor,current:{features:f.features,ids:new Set(f.features.map(f=>f.id)),units,footprints:footprintHash(f.features)},candidate:{features:next,ids:new Set(next.map(f=>f.id)),units,footprints:footprintHash(next)},opts:{...f.options,geometryProofs},read,refresh(){put(geometryProofs,descriptor);put(f.options.sourceReceipt,aggregate);}};
}
test('ordered replacement then pure creation validates exact current ancestry and pinned source bytes',t=>{
 const f=composedFixture(t),before=snapshot(f.options.data),proof=verifySourceGeometry(f.opts,f.current,f.candidate,f.aggregate);assert.deepEqual([...proof.chain.changedIds],['loc0']);assert.deepEqual([...proof.chain.addedIds],['new-island']);assert.ok(proof.files['creation-migration/sources/0.geojson']);assert.deepEqual(snapshot(f.options.data),before);
});
test('composed installer rejects skipped or reordered manifests, changed pins and unmatched creation inventories',t=>{
 const f=composedFixture(t);
 for(const kind of ['skip','order','pin','added','changed','proof','source','original','unreceipted-land']){
  const opts=structuredClone(f.opts),receipt=structuredClone(f.aggregate),next=structuredClone(f.candidate),descriptor=structuredClone(f.descriptor);next.ids=new Set(next.features.map(f=>f.id));
  if(kind==='skip')descriptor.manifests.shift();if(kind==='order')descriptor.manifests.reverse();if(kind==='pin')descriptor.manifests[1].sha256='0'.repeat(64);if(kind==='added')receipt.added_ids=[];if(kind==='changed')receipt.changed_ids=[];if(kind==='proof')receipt.creation_proofs=[];if(kind==='source')receipt.creation_proofs[0].source.sha256='0'.repeat(64);if(kind==='original')receipt.archives[0].feature.properties.name='Undocumented old identity';if(kind==='unreceipted-land')next.features[1].geometry.coordinates[0][1][0]+=.1;
  put(opts.geometryProofs,descriptor);assert.throws(()=>verifySourceGeometry(opts,f.current,next,receipt),undefined,kind);
 }
 f.refresh();
});
test('composed installer rejects child historical transfers and changed source archive bytes',t=>{
 const f=composedFixture(t),file=f.dir+'/replacement-migration/migration-receipt.json',receipt=f.read(file);receipt.relationships[0].history_transfer=true;put(file,receipt);const manifest=f.read(f.dir+'/replacement-migration/index.json');manifest.files['migration-receipt.json'].sha256=hash(fs.readFileSync(file));put(f.dir+'/replacement-migration/index.json',manifest);f.descriptor.manifests[0].sha256=hash(fs.readFileSync(f.dir+'/replacement-migration/index.json'));f.refresh();assert.throws(()=>verifySourceGeometry(f.opts,f.current,f.candidate,f.aggregate),/transfer/);
 const g=composedFixture(t);fs.appendFileSync(g.dir+'/creation-migration/sources/0.geojson',' ');assert.throws(()=>verifySourceGeometry(g.opts,g.current,g.candidate,g.aggregate),/archive hash mismatch/);
});
test('geometry evidence cannot silently authorize current source-name changes',t=>{
 const f=composedFixture(t);f.candidate.features[1].properties.name='Unverified renamed location';assert.throws(()=>verifySourceGeometry(f.opts,f.current,f.candidate,f.aggregate),/Unreceipted reference name/);
});

test('source-name correction requires pinned exact metadata before/after evidence',t=>{
 const f=composedFixture(t),before=structuredClone(f.current.features[1].properties);f.candidate.features[1].properties.name='Verified reference name';
 const metadata={reference_only:true,historical_claims_transferred:false,before_units:f.units,retired_units:[],group_changes:[],changed_location_properties:[{location_id:'loc1',before_properties:before,after_properties:structuredClone(f.candidate.features[1].properties)}],relationships:[],source_evidence:[{url:'https://example.org/synthetic-name-source',source_sha256:'c'.repeat(64)}]},file=f.dir+'/reference-receipt.json';
 const pin=put(file,metadata);f.descriptor.metadata_receipts=[{path:'reference-receipt.json',sha256:pin}];f.refresh();assert.doesNotThrow(()=>verifySourceGeometry(f.opts,f.current,f.candidate,f.aggregate));
 const proof=verifySourceGeometry(f.opts,f.current,f.candidate,f.aggregate);assert.equal(proof.files['reference-receipt.json'],pin);
 f.descriptor.metadata_receipts=[];f.refresh();assert.throws(()=>verifySourceGeometry(f.opts,f.current,f.candidate,f.aggregate),/Unreceipted reference name/);
 metadata.changed_location_properties[0].before_properties.name='Wrong original identity';const altered=put(file,metadata);f.descriptor.metadata_receipts=[{path:'reference-receipt.json',sha256:altered}];f.refresh();assert.throws(()=>verifySourceGeometry(f.opts,f.current,f.candidate,f.aggregate),/Metadata location before\/after evidence/);
});
test('installer summary pins geometry proof members and rejects altered evidence after approval',t=>{
 const f=composedFixture(t),o={...f.options,geometryProofs:f.opts.geometryProofs},receipt=f.read(f.dir+'/replacement-migration/migration-receipt.json');put(o.sourceReceipt,receipt);
 const descriptor={...f.descriptor,after_footprints_sha256:footprintHash(f.after),manifests:[f.descriptor.manifests[0]]};put(o.geometryProofs,descriptor);
 const sourceHash=hash(fs.readFileSync(o.sourceReceipt)),owner=f.read(o.ownership+'/index.json');owner.incremental_preparation.migration_receipt_sha256=sourceHash;put(o.ownership+'/index.json',owner);
 const macro=f.read(o.macroReceipt);macro.source_repair_receipt_sha256=sourceHash;put(o.macroReceipt,macro);
 const rr=f.read(o.references+'/incremental-receipt.json');rr.migration_receipt_sha256=sourceHash;put(o.references+'/incremental-receipt.json',rr);const reference=f.read(o.references+'/index.json');reference.incremental_preparation.receipt_sha256=hash(fs.readFileSync(o.references+'/incremental-receipt.json'));put(o.references+'/index.json',reference);
 const runtime=f.read(o.runtime+'/index.json');runtime.source_index_sha256=hash(fs.readFileSync(o.ownership+'/index.json'));put(o.runtime+'/index.json',runtime);
 const dry=install(o);assert.equal(dry.sources.geometryProofs['replacement-migration/migration-receipt.json'],hash(fs.readFileSync(f.dir+'/replacement-migration/migration-receipt.json')));
 const manifest=f.read(f.dir+'/replacement-migration/index.json');manifest.additional_inspection='New evidence after approval';put(f.dir+'/replacement-migration/index.json',manifest);descriptor.manifests[0].sha256=hash(fs.readFileSync(f.dir+'/replacement-migration/index.json'));put(o.geometryProofs,descriptor);
 assert.throws(()=>install({...o,expectedValidation:dry.validation_sha256},{apply:true}),/approved dry-run hash/);
});
