import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {createHash} from 'node:crypto';
import {stageLandCreations} from '../scripts/stage-land-creations.mjs';import {validateGeometryMigrations,prepareGeographicRelease} from '../scripts/prepare-geographic-release.mjs';import {footprintHash} from '../scripts/check-prepared.mjs';import {gzipSync} from 'node:zlib';import {DatabaseSync} from 'node:sqlite';
import {importBatch,attributesAt} from '../hosted/records.js';import {stageGeographicRelease,finalizeGeographicRelease,geographicRelease,geographicChangePage} from '../hosted/geographic-releases.js';
const sha=b=>createHash('sha256').update(b).digest('hex'),put=(p,d)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(d));};
function fixture(t){const folder=fs.mkdtempSync(path.join(os.tmpdir(),'atlas-land-create-'));t.after(()=>fs.rmSync(folder,{recursive:true,force:true}));
 const polygon=(x,y=0)=>({type:'Polygon',coordinates:[[[x,y],[x+1,y],[x+1,y+1],[x,y+1],[x,y]]]});
 const feature=(id,name,geometry)=>({type:'Feature',id,properties:{id,name,parent_id:'p',reference_owner:null},geometry});
 const old=[feature('original','Original',polygon(0))],added=feature('new','New island',polygon(40,60));
 const units=['province','area','region','subcontinent','continent'].map((level,i)=>({id:['p','a','r','s','c'][i],name:level,level,parent_id:['a','r','s','c',null][i]}));
 const before=path.join(folder,'before'),after=path.join(folder,'after'),output=path.join(folder,'evidence'),proofs=path.join(folder,'proofs.json'),source=path.join(folder,'source.geojson');
 for(const [dir,features] of [[before,old],[after,[...old,added]]]){put(path.join(dir,'world-index.json'),{parts:['geography/part.json']});put(path.join(dir,'geography/part.json'),{features});put(path.join(dir,'hierarchy.json'),units);}
 put(source,{type:'Feature',id:'source-island',properties:{name:'New island'},geometry:added.geometry});
 const proof={location_id:'new',parent_chain:['p','a','r','s','c'],source:{path:'source.geojson',sha256:sha(fs.readFileSync(source)),identity:'source-island',url:'https://example.org/synthetic-island',license:'Synthetic test-only',attribution:'Synthetic fixture',supported_from:2026,supported_to:2027},identity_review:{status:'distinct-new-territory',evidence_url:'https://example.org/synthetic-identity',rationale:'Synthetic separate island; no real historical evidence'}};put(proofs,[proof]);
 return {folder,before,after,output,proofs,source,proof,old,added,units,options:{before,after,output,proofs},refresh(){put(source,{type:'Feature',id:'source-island',properties:{name:'New island'},geometry:added.geometry});proof.source.sha256=sha(fs.readFileSync(source));put(proofs,[proof]);put(path.join(after,'geography/part.json'),{features:[...old,added]});}};
}
test('pure source-backed creation has a null predecessor and retains every original geometry',t=>{const f=fixture(t),beforeBytes=fs.readFileSync(path.join(f.before,'geography/part.json')),result=stageLandCreations(f.options);assert.deepEqual(result.added_ids,['new']);assert.equal(fs.readFileSync(path.join(f.before,'geography/part.json')).equals(beforeBytes),true);
 const receipt=JSON.parse(fs.readFileSync(path.join(f.output,'migration-receipt.json')));assert.deepEqual(receipt.relationships[0].before_ids,[]);assert.equal(receipt.historical_claims_transferred,false);
 const proof=validateGeometryMigrations({features:[...f.old,f.added],baselineIds:['original'],baselineFootprints:footprintHash(f.old),manifestFiles:[path.join(f.output,'index.json')],units:f.units});assert.equal(proof.pairs[0].old_entity_id,null);assert.equal(proof.pairs[0].change_type,'create');assert.deepEqual([...proof.addedIds],['new']);assert.equal(proof.changedIds.size,0);
 assert.throws(()=>stageLandCreations(f.options),/fresh/);
});
test('latitude and antimeridian creation uses actual narrow land, not a world-width polygon',t=>{const f=fixture(t);f.added.geometry={type:'Polygon',coordinates:[[[179,70],[-179,70],[-179,71],[179,71],[179,70]]]};f.refresh();const result=stageLandCreations(f.options);assert.equal(result.added_ids.length,1);});
test('reject existing identity, duplicate land and competing overlap without writing output',t=>{for(const kind of ['identity','duplicate-land','overlap','same-name','history']){const f=fixture(t);if(kind==='identity')f.added.id=f.added.properties.id='original';else if(kind==='duplicate-land')f.added.geometry=f.old[0].geometry;else if(kind==='overlap')f.added.geometry={type:'Polygon',coordinates:[[[.5,0],[1.5,0],[1.5,1],[.5,1],[.5,0]]]};else if(kind==='same-name')f.added.properties.name='Original';else f.added.properties.reference_owner='Invented modern owner';f.refresh();assert.throws(()=>stageLandCreations(f.options));assert.equal(fs.existsSync(f.output),false);}});
test('reject unsupported source, altered geometry, invalid coordinates, chain gaps and disguised rename',t=>{for(const kind of ['license','hash','interval','geometry','chain','rename','source-identity','ring']){const f=fixture(t);if(kind==='license')delete f.proof.source.license;else if(kind==='hash')f.proof.source.sha256='0'.repeat(64);else if(kind==='interval')f.proof.source.supported_from=0;else if(kind==='geometry')f.added.geometry.coordinates[0][1][0]+=1;else if(kind==='chain')f.proof.parent_chain[0]='other';else if(kind==='rename')f.proof.identity_review.status='rename';else if(kind==='source-identity'){f.proof.source.identity='original';const raw=JSON.parse(fs.readFileSync(f.source));raw.id='original';put(f.source,raw);f.proof.source.sha256=sha(fs.readFileSync(f.source));}else {const raw=JSON.parse(fs.readFileSync(f.source));raw.geometry.coordinates[0].pop();put(f.source,raw);f.proof.source.sha256=sha(fs.readFileSync(f.source));}put(f.proofs,[f.proof]);put(path.join(f.after,'geography/part.json'),{features:[...f.old,f.added]});assert.throws(()=>stageLandCreations(f.options));assert.equal(fs.existsSync(f.output),false);}});
test('a creation receipt cannot transfer history or add an unaccounted identity',t=>{const f=fixture(t);stageLandCreations(f.options);const file=path.join(f.output,'migration-receipt.json'),indexFile=path.join(f.output,'index.json'),r=JSON.parse(fs.readFileSync(file));r.relationships[0].history_transfer=true;put(file,r);const index=JSON.parse(fs.readFileSync(indexFile));index.files['migration-receipt.json'].sha256=sha(fs.readFileSync(file));put(indexFile,index);assert.throws(()=>validateGeometryMigrations({features:[...f.old,f.added],baselineIds:['original'],baselineFootprints:footprintHash(f.old),manifestFiles:[indexFile],units:f.units}),/transfer/);});

test('staged source creation compiles and publishes identical static/hosted crosswalks',async t=>{
 const f=fixture(t),initial=structuredClone(f.units);
 for(let i=1;i<6;i++){f.units.push(...initial.map(u=>({...u,id:u.id+i,parent_id:u.parent_id===null?null:u.parent_id+i})));const old=structuredClone(f.old[0]);old.id=old.properties.id='original'+i;old.properties.name='Original '+i;old.properties.parent_id='p'+i;old.geometry.coordinates[0]=old.geometry.coordinates[0].map(([x,y])=>[x+i*2,y]);f.old.push(old);}
 for(const [directory,features] of [[f.before,f.old],[f.after,[...f.old,f.added]]]){put(path.join(directory,'hierarchy.json'),f.units);put(path.join(directory,'geography/part.json'),{features});}
 const original=[...f.units.map(u=>({id:u.id,name:u.name,kind:u.level,parent_id:u.parent_id,active:1,source_id:'fixture-reference'})),...f.old.map(v=>({id:v.id,name:v.properties.name,kind:'location',parent_id:v.properties.parent_id,active:1,source_id:'fixture-reference'}))];
 const catalog=path.join(f.before,'hosted-catalog'),entitiesFile=path.join(catalog,'entities.json');put(entitiesFile,{entities:original});put(path.join(catalog,'index.json'),{archive_sha256:'a'.repeat(64),batches:[{kind:'entities',path:'entities.json',sha256:sha(fs.readFileSync(entitiesFile))}]});
 fs.writeFileSync(path.join(f.before,'geographic-decision-migration.json.gz'),gzipSync(JSON.stringify({before_units:f.units,group_changes:[],changes:[]})));put(path.join(f.before,'macro-corrections.json'),{footprints_sha256_before:footprintHash(f.old)});
 for(let i=0;i<6;i++)put(path.join(f.before,'geographic-decisions',i+'.json'),{decisions:[]});stageLandCreations(f.options);
 const output=path.join(f.folder,'release'),prepared=await prepareGeographicRelease({data:f.before,geographyData:f.after,geometryManifests:[path.join(f.output,'index.json')],metadataMigrations:[],output});
 assert.equal(prepared.new_entities,1);assert.equal(prepared.releases[1].expected_counts.continent,6);assert.equal(prepared.releases[1].expected_counts.location,7);
 const sqlite=new DatabaseSync(':memory:');t.after(()=>sqlite.close());sqlite.exec('PRAGMA foreign_keys=ON');for(const name of fs.readdirSync(new URL('../drizzle/',import.meta.url)).filter(n=>n.endsWith('.sql')).sort())sqlite.exec(fs.readFileSync(new URL('../drizzle/'+name,import.meta.url),'utf8'));
 const db={prepare(sql){let args=[];return {bind(...values){args=values;return this;},async first(){return sqlite.prepare(sql).get(...args)??null;},async all(){return {results:sqlite.prepare(sql).all(...args)};},run(){return {meta:{changes:Number(sqlite.prepare(sql).run(...args).changes)}};}};},async batch(statements){sqlite.exec('BEGIN IMMEDIATE');try{const result=statements.map(s=>s.run());sqlite.exec('COMMIT');return result;}catch(error){sqlite.exec('ROLLBACK');throw error;}}};
 await importBatch(db,JSON.parse(fs.readFileSync(new URL('../data/hosted-type-catalog.json',import.meta.url))));await importBatch(db,{sources:[{id:'fixture-reference',name:'Synthetic fixture',url:'https://example.org/test',license:'Synthetic fixture',supported_from:2026,supported_to:2027,status:'reference',vintage:'Synthetic2026'}],entities:original});
 for(const batch of prepared.batches){const payload=JSON.parse(fs.readFileSync(path.join(output,batch.path)));if(batch.route==='/api/records/import')await importBatch(db,payload);else await stageGeographicRelease(db,payload);}
 for(const release of prepared.releases)await finalizeGeographicRelease(db,release.id);
 const live=await geographicRelease(db);assert.equal(live.footprints_sha256,footprintHash([...f.old,f.added]));assert.equal(live.membership_sha256,prepared.releases[1].membership_sha256);assert.equal(live.changes_sha256,prepared.releases[1].changes_sha256);
 const changes=(await geographicChangePage(db,{releaseId:live.id})).records;assert.equal(changes.length,1);assert.equal(changes[0].old_entity_id,null);assert.equal(changes[0].evidence.geometry_creation.creation_proof.source.license,'Synthetic test-only');assert.equal((await attributesAt(db,1000,{locationIds:['new']})).records.length,0);
});

test('invalid source coordinates, competing new land and old group mutations are rejected',t=>{
 for(const kind of ['coordinates','self-intersection','competing','old-group']){const f=fixture(t);
  if(kind==='coordinates'){f.added.geometry.coordinates[0]=[[[40,91],[41,91],[41,92],[40,92],[40,91]]][0];f.refresh();}
  else if(kind==='self-intersection'){f.added.geometry.coordinates[0]=[[40,60],[41,61],[40,61],[41,60],[40,60]];f.refresh();}
  else if(kind==='old-group'){f.units[0].name='Unreviewed rename';put(path.join(f.after,'hierarchy.json'),f.units);}
  else{const other=structuredClone(f.added);other.id=other.properties.id='competing';other.properties.name='Another';const proof=structuredClone(f.proof);proof.location_id='competing';put(f.proofs,[f.proof,proof]);put(path.join(f.after,'geography/part.json'),{features:[...f.old,f.added,other]});}
  assert.throws(()=>stageLandCreations(f.options));assert.equal(fs.existsSync(f.output),false);
 }
});
