import test from'node:test';import assert from'node:assert/strict';import{replacementReceipt}from'../scripts/prepare-macro-restoration-proofs.mjs';
const feature=(id,x)=>({type:'Feature',id,properties:{id,name:id,parent_id:'province'},geometry:{type:'Polygon',coordinates:[[[x,0],[x+.1,0],[x+.1,.1],[x,.1],[x,0]]]}});
function fixture(){const before=Array.from({length:7},(_,i)=>feature('id'+i,i));const after=structuredClone(before);for(let i=0;i<6;i++)after[i].geometry.coordinates[0][1][0]+=.01;const composition={replacement_deltas:before.slice(0,6).map((f,i)=>({id:f.id,before_feature:f,after_feature:after[i]}))};return{before,after,composition,validation:{verified:true,history_transfer:false,source_evidence:[{url:'https://example.org/source',source_sha256:'a'.repeat(64)}]}};}
test('retained replacements archive all six exact originals without predecessor transfer',()=>{const f=fixture(),r=replacementReceipt(f);assert.equal(r.archives.length,6);assert.deepEqual(r.added_ids,[]);assert.deepEqual(r.removed_ids,[]);assert.deepEqual(r.reused_ids,['id6']);assert.deepEqual(r.archives[0].feature,f.before[0]);assert(r.relationships.every(x=>x.before_ids[0]===x.after_ids[0]&&x.history_transfer===false));});
test('an unrelated old feature mutation is rejected',()=>{const f=fixture();f.after[6].properties.name='silently renamed';assert.throws(()=>replacementReceipt(f),/Unreceipted/);});
test('exact changed feature archives cannot substitute modified originals',()=>{const f=fixture();f.composition.replacement_deltas[0].before_feature=feature('id0',22);assert.throws(()=>replacementReceipt(f),/Unreceipted/);});
test('duplicate or replaced stable identities are rejected',()=>{const f=fixture();f.after[6]=structuredClone(f.after[0]);assert.throws(()=>replacementReceipt(f),/inventory/);});
test('source proof cannot authorize historical transfer or missing independent validation',()=>{const f=fixture();f.validation.history_transfer=true;assert.throws(()=>replacementReceipt(f),/Independent/);f.validation.history_transfer=false;f.validation.verified=false;assert.throws(()=>replacementReceipt(f),/Independent/);});
import fs from'node:fs';import path from'node:path';import os from'node:os';import{execFileSync}from'node:child_process';import{fileURLToPath}from'node:url';
test('bounded replacement subprocess writes the same exact validated receipt',()=>{const f=fixture(),dir=fs.mkdtempSync(path.join(os.tmpdir(),'macro-proof-test-'));try{for(const[phase,rows]of[['reference',f.before],['replacement',f.after]]){fs.mkdirSync(path.join(dir,phase));fs.writeFileSync(path.join(dir,phase,'world-index.json'),JSON.stringify({parts:['features.json']}));fs.writeFileSync(path.join(dir,phase,'features.json'),JSON.stringify({type:'FeatureCollection',features:rows}));}fs.mkdirSync(path.join(dir,'replacement-migration'));fs.writeFileSync(path.join(dir,'composition.json'),JSON.stringify(f.composition));fs.writeFileSync(path.join(dir,'independent-validation.json'),JSON.stringify(f.validation));const script=fileURLToPath(new URL('../scripts/prepare-macro-restoration-proofs.mjs',import.meta.url));execFileSync(process.execPath,[script,'--stage',dir,'--replacement-only']);assert.deepEqual(JSON.parse(fs.readFileSync(path.join(dir,'replacement-migration/migration-receipt.json'))),replacementReceipt(f));}finally{fs.rmSync(dir,{recursive:true,force:true});}});
