import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {execFileSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
import {checkMarcusPolicy} from '../data/macro-improvements/marcus-restoration/check.mjs';
const root=path.resolve(fileURLToPath(new URL('..',import.meta.url))),folder=path.join(root,'data/macro-improvements/marcus-restoration'),proposal=JSON.parse(fs.readFileSync(path.join(folder,'proposal.json')));
test('finite Marcus routing is independent of sovereignty and retains provisional lower-tier roles',()=>{assert.doesNotThrow(()=>checkMarcusPolicy(proposal));assert.equal(proposal.parent_chain.length,5);assert.equal(proposal.source_geometry.supported_interval[0],2026);});
test('reject asymmetric Japan exclusion, alternate macro routing and invented readiness',()=>{
 for(const kind of ['exclusion','route','readiness','history','owner','exception','parent']){const p=structuredClone(proposal);if(kind==='exclusion')p.macro_amendment.reciprocal_exclusion.named_land=[];if(kind==='route')p.parent_chain[2]='framework:region:japan:d79de169a905';if(kind==='readiness')p.regional_interior_approval=true;if(kind==='history')p.history_transfer=true;if(kind==='owner')p.political_reference_context.Japan.automatic_attribute_assignment=true;if(kind==='parent')p.new_groups[1].parent_id='framework:region:japan:d79de169a905';if(kind==='exception')p.new_groups[0].metadata.coextensive_tier_exception='';assert.throws(()=>checkMarcusPolicy(p));}
});
test('original water-masked Marcus land reconstructs from exact OSM bytes',()=>{
 const script="import importlib.util,json,pathlib; f=pathlib.Path("+JSON.stringify(path.join(folder,'prepare.py'))+"); s=importlib.util.spec_from_file_location('marcus',f); m=importlib.util.module_from_spec(s); s.loader.exec_module(m); p=m.read(f.parent/'proposal.json'); dry,coast,water=m.reconstruct(p); assert len(dry.interiors)==1 and water.area>0 and coast.difference(water).equals(dry)";
 execFileSync('python3',['-c',script]);
});
test('removing the source water hole or changing the coastline is rejected',t=>{
 const temporary=fs.mkdtempSync(path.join(os.tmpdir(),'marcus-water-negative-'));t.after(()=>fs.rmSync(temporary,{recursive:true,force:true}));
 const script=`import importlib.util,json,pathlib,gzip,hashlib\nfrom shapely import from_wkb,to_wkb\nfrom shapely.geometry import Polygon\nf=pathlib.Path(${JSON.stringify(path.join(folder,'prepare.py'))}); s=importlib.util.spec_from_file_location('marcus',f);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);p=m.read(f.parent/'proposal.json');m.HERE=pathlib.Path(${JSON.stringify(temporary)})\nraw=(f.parent/'original-map.osm.xml.gz').read_bytes();(m.HERE/'original-map.osm.xml.gz').write_bytes(raw)\ndry=from_wkb(gzip.decompress((f.parent/'dry-land.wkb.gz').read_bytes()))\nfor kind in ['drop-water','move-land']:\n g=Polygon(dry.exterior) if kind=='drop-water' else __import__('shapely.affinity',fromlist=['translate']).translate(dry,xoff=.001)\n b=to_wkb(g);(m.HERE/'dry-land.wkb.gz').write_bytes(gzip.compress(b));p['source_geometry']['wkb_sha256']=hashlib.sha256(b).hexdigest()\n try:m.reconstruct(p)\n except ValueError as e:assert 'reconstruction' in str(e)\n else:raise AssertionError('Altered source land was accepted')\n`;
 execFileSync('python3',['-c',script]);
});
