import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {createLocalPostgres} from '../scripts/verify-postgres-schema.mjs';
import {importBatch} from '../hosted/records.js';
import {exportStorageMarker,exportStoragePage,storageExportCollections,storageExportColumns} from '../hosted/storage-export.js';
import {restorePostgresStorage} from '../scripts/restore-postgres-storage.mjs';
import {provisionPostgresRuntimeRole} from '../scripts/provision-postgres-runtime-role.mjs';
import {applyPostgresForwardMigrations,forwardMigrationDefinitions,validateForwardOperation,validateForwardMaintenance,runNeonForwardMigrations,verifyForwardRuntimeRole} from '../scripts/neon-forward-migrations.mjs';
const root=path.resolve(new URL('..',import.meta.url).pathname),hash=value=>createHash('sha256').update(value).digest('hex');
const migration={...forwardMigrationDefinitions[0],sha256:hash(fs.readFileSync(new URL('../postgres/migrations/0001_temporal_geography.sql',import.meta.url)))};
async function fixture(){const pg=await createLocalPostgres(),directory=fs.mkdtempSync(path.join(os.tmpdir(),'atlas-forward-test-')),owner={query:(query,params=[])=>pg.engine.query(query,params),runTransaction:callback=>pg.engine.transaction(tx=>callback({query:(query,params=[])=>tx.query(query,params)}))};try{
 await importBatch(pg.db,{sources:[{id:'retained-source',name:'Isolated forward fixture',url:'https://example.org/forward-test',license:'CC0',vintage:'2026',supported_from:-3000,supported_to:2027,status:'historical',metadata:{only:'synthetic testing'}}]});await provisionPostgresRuntimeRole({driver:owner,password:'isolated-fixture-password-for-test-only'});
 const marker={...await exportStorageMarker(pg.db),read_only:true},collections={};for(const collection of storageExportCollections){fs.mkdirSync(path.join(directory,collection));const page=await exportStoragePage(pg.db,collection),bytes=Buffer.from(JSON.stringify(page,null,2)+'\n'),file=`${collection}/part-000001.json`;fs.writeFileSync(path.join(directory,file),bytes);collections[collection]={count:page.records.length,columns:storageExportColumns[collection],parts:[{path:file,sha256:hash(bytes),bytes:bytes.length,rows:page.records.length,start_cursor:'',end_cursor:null}]};}
 fs.writeFileSync(path.join(directory,'index.json'),JSON.stringify({version:1,status:'complete',read_only:true,snapshot_consistent:true,source_backend:'postgres',snapshot_marker:marker,format:{json_text_preserved:true,ingestion_rowid_preserved:true,includes_archived_examples_withdrawals:true},collections}));
 const revision=marker.revision;await owner.runTransaction(tx=>tx.query(`ALTER SEQUENCE atlas_ingestions_rowid_seq RESTART WITH ${revision+1}`));const baseline=await restorePostgresStorage({directory,driver:owner,verifyOnly:true,receiptFile:null});return {pg,directory,owner,baseline,close:async()=>{await pg.close();fs.rmSync(directory,{recursive:true,force:true});}};
 }catch(error){await pg.close();fs.rmSync(directory,{recursive:true,force:true});throw error;}}

test('actual PostgreSQL forward DDL preserves every baseline byte and sequence, grants minimum runtime access, and retries idempotently',async()=>{const f=await fixture();try{const options={driver:f.owner,sourceDirectory:f.directory,migrations:[migration,{...forwardMigrationDefinitions[1],sha256:hash(fs.readFileSync(new URL('../postgres/migrations/0002_footprint_versions.sql',import.meta.url)))}],baselineTriggerHash:f.baseline.trigger_inventory_sha256,root},first=await applyPostgresForwardMigrations(options);assert.equal(first.status,'verified');assert.equal(first.atlas_fact_tables,23);assert.deepEqual(first.original_collections,f.baseline.collections);assert.equal(first.original_sequence_preserved,true);assert.equal(first.runtime.registry_access,false);const retry=await applyPostgresForwardMigrations(options);assert.equal(retry.migrations[0].status,'already-applied');const verified=await applyPostgresForwardMigrations({...options,verifyOnly:true});assert.equal(verified.read_only,true);
 await f.owner.query('SET ROLE worldatlas_app');try{await f.owner.query('SELECT * FROM atlas_temporal_geography_validations');for(const query of ['SELECT * FROM worldatlas_schema_migrations','UPDATE atlas_geographic_membership_records SET metadata=metadata','DELETE FROM atlas_geographic_existence_records','TRUNCATE atlas_temporal_geography_retirements','ALTER TABLE atlas_geographic_membership_records DISABLE TRIGGER ALL'])await assert.rejects(f.owner.query(query));}finally{await f.owner.query('RESET ROLE');}
 await assert.rejects(f.owner.query('DELETE FROM worldatlas_schema_migrations'));await assert.rejects(f.owner.query('TRUNCATE worldatlas_schema_migrations'));
 }finally{await f.close();}});

test('forward failure rolls back DDL, registry and grants without changing original bytes',async()=>{const f=await fixture();try{const driver={...f.owner,runTransaction:callback=>f.owner.runTransaction(tx=>callback({query:async(query,params)=>{if(query.startsWith('GRANT SELECT,INSERT ON TABLE public.atlas_geographic_existence_records'))throw Object.assign(Error('Synthetic private driver detail must not escape'),{code:'40001'});return tx.query(query,params);}}))};await assert.rejects(applyPostgresForwardMigrations({driver,sourceDirectory:f.directory,migrations:[migration],baselineTriggerHash:f.baseline.trigger_inventory_sha256,root}),error=>error.code==='forward-transaction-failed'&&error.sqlstate==='40001'&&!error.message.includes('private driver detail'));assert.equal((await f.owner.query("SELECT to_regclass('public.worldatlas_schema_migrations') IS NULL absent")).rows[0].absent,true);assert.equal((await f.owner.query("SELECT to_regclass('public.atlas_geographic_existence_records') IS NULL absent")).rows[0].absent,true);const after=await restorePostgresStorage({directory:f.directory,driver:f.owner,verifyOnly:true,receiptFile:null});assert.deepEqual(after.collections,f.baseline.collections);
 }finally{await f.close();}});

test('registered catalog tampering and unreviewed hashes reject instead of silently repairing a database',async()=>{const f=await fixture();try{const options={driver:f.owner,sourceDirectory:f.directory,migrations:[migration],baselineTriggerHash:f.baseline.trigger_inventory_sha256,root};await assert.rejects(applyPostgresForwardMigrations({...options,migrations:[{...migration,sha256:'f'.repeat(64)}]}),/hash/);await applyPostgresForwardMigrations(options);await f.owner.query('ALTER TABLE atlas_geographic_membership_records DISABLE TRIGGER atlas_10_temporal_contract');await assert.rejects(applyPostgresForwardMigrations(options),/guard-disabled/);await f.owner.query('ALTER TABLE atlas_geographic_membership_records ENABLE TRIGGER atlas_10_temporal_contract');await f.owner.query('GRANT SELECT ON worldatlas_schema_migrations TO worldatlas_app');await assert.rejects(verifyForwardRuntimeRole(f.owner,[forwardMigrationDefinitions[0]]),/unrelated/);
 }finally{await f.close();}});

test('missing reviewed rehearsal operation performs no management requests or database mutation',async()=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),'atlas-forward-skip-'));try{let requested=false;const receipt=await runNeonForwardMigrations({root:directory,fetchImpl:async()=>{requested=true;throw Error('must not call');}});assert.equal(receipt.status,'skipped');assert.equal(requested,false);assert.equal(receipt.credentials_logged,false);}finally{fs.rmSync(directory,{recursive:true,force:true});}});

test('reviewed forward operation requires an actual production baseline and exact ordered files',()=>{const operation={version:1};assert.throws(()=>validateForwardOperation(operation,{root,mode:'production'}),/reviewed-forward/);const workflow=fs.readFileSync(new URL('../.github/workflows/neon-forward-migrations.yml',import.meta.url),'utf8');assert.ok(!workflow.includes('| rg'));assert.ok(workflow.includes('[ \"$EVENT_NAME\" = workflow_dispatch ] || exit 1'));assert.ok(!/^  push:/m.test(workflow));assert.ok(workflow.includes('cancel-in-progress: false'));});

test('fresh hash-pinned private Site maintenance attestation rejects stale, writable and mismatched context',()=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),'atlas-maintenance-test-')),now=Date.now(),operation={site_origin:'https://example.org',site_backend:'d1',source_revision:1321,source_snapshot_fingerprint:'a'.repeat(64)};try{const receipt={version:1,verification_method:'root-private-site-authenticated-read',site_origin:operation.site_origin,backend:'d1',source_revision:1321,source_snapshot_fingerprint:operation.source_snapshot_fingerprint,read_only:true,verified_at_utc:new Date(now).toISOString(),deployment_id:'isolated-test-deployment',environment_revision:1},write=value=>{const bytes=Buffer.from(JSON.stringify(value));fs.writeFileSync(path.join(directory,'maintenance.json'),bytes);operation.maintenance={receipt_file:'maintenance.json',receipt_sha256:hash(bytes)};};write(receipt);assert.equal(validateForwardMaintenance(operation,{root:directory,now}).runner_observed_site,false);for(const change of [{read_only:false},{backend:'postgres'},{source_revision:1322},{verified_at_utc:new Date(now-3600001).toISOString()},{verified_at_utc:new Date(now+30001).toISOString()}]){write({...receipt,...change});assert.throws(()=>validateForwardMaintenance(operation,{root:directory,now}),/maintenance/);}write(receipt);fs.appendFileSync(path.join(directory,'maintenance.json'),' ');assert.throws(()=>validateForwardMaintenance(operation,{root:directory,now}),/bytes/);}finally{fs.rmSync(directory,{recursive:true,force:true});}});

test('management workflows require explicit manual dispatch and reject push selection',()=>{
 const directory=fs.mkdtempSync(path.join(os.tmpdir(),'atlas-manual-selector-'));
 try{
  for(const name of ['neon-forward-migrations.yml','neon-storage-migration.yml']){
   const workflow=fs.readFileSync(new URL('../.github/workflows/'+name,import.meta.url),'utf8'),body=workflow.match(/run: \|\n([\s\S]*?)\n      - name: Set up Node/)[1].split('\n').map(line=>line.replace(/^          /,'')).join('\n');
   assert.ok(!/^  push:/m.test(workflow));
   for(const [event,mode] of [['workflow_dispatch','production'],['workflow_dispatch','rehearsal'],['workflow_dispatch','verify-only'],['push','production'],['workflow_dispatch','invalid']]){
    const output=path.join(directory,'output');fs.writeFileSync(output,'');const result=spawnSync('bash',['-c',body],{env:{PATH:'/usr/bin:/bin',GITHUB_OUTPUT:output,EVENT_NAME:event,REQUESTED_MODE:mode},encoding:'utf8'});
    if(event==='push'||mode==='invalid'){assert.notEqual(result.status,0);assert.equal(fs.readFileSync(output,'utf8'),'');}
    else{assert.equal(result.status,0,result.stderr);assert.ok(fs.readFileSync(output,'utf8').includes('mode='+mode+'\n'));}
   }
  }
 }finally{fs.rmSync(directory,{recursive:true,force:true});}
});
