import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {createLocalPostgres,postgresSchemaInventory,exercisePostgresSmoke} from '../scripts/verify-postgres-schema.mjs';
import {importBatch,attributesAt,namesAt,entityProfile,evidenceHistory,registerMedia,retirementsAt} from '../hosted/records.js';
import {catalogPage,entityRelationshipsPage,entityMediaPage} from '../hosted/research-catalog.js';
import {mapSnapshotPage,hydrateMapSnapshotPage} from '../hosted/map-snapshots.js';
import {resolveAttributes} from '../src/attributes.js';
import {stageGeographicRelease,finalizeGeographicRelease,geographicRelease,geographicMembershipPage,geographicMembershipHash,geographicLocationIdsHash,geographicChangesHash} from '../hosted/geographic-releases.js';

const tiers=['continent','subcontinent','region','area','province','location'];
const source=(id='history',status='historical',from=1000,to=1100)=>({id,name:`Test-only ${id}`,url:'https://example.org/postgres-test-only',license:'CC0',vintage:'2026',supported_from:from,supported_to:to,status,metadata:{original_digest:'b'.repeat(64),original_wording:'Source evidence retained.'}});
const record=(id,attribute,value,extra={})=>({id,location_id:'location',attribute,value,valid_from:1000,valid_to:1100,source_id:'history',...extra});
const retirement=(id,target,replacement=null)=>({id,collection:'records',target_id:target,replacement_id:replacement,source_id:'history',reason:'Test-only sourced correction'});
const contractRejected=error=>[400,409].includes(error.status)&&!String(error.message).match(/\b42[A-Z0-9]{3}\b/);
async function fixture(){const value=await createLocalPostgres();try{await importBatch(value.db,JSON.parse(fs.readFileSync(new URL('../data/hosted-type-catalog.json',import.meta.url))));await importBatch(value.db,{sources:[source(),source('reference','reference',2026,2027),source('example','example'),source('estimate','estimate')],entities:tiers.map((kind,index)=>({id:kind,kind,name:`Original ${kind}`,parent_id:index?tiers[index-1]:null})),categories:['owner','culture','religion'].map(kind=>({id:`${kind}:a`,kind,name:`${kind} A`,source_id:'history'}))});return value;}catch(error){await value.close();throw error;}}
const withFixture=fn=>async()=>{const fixtureValue=await fixture();try{await fn(fixtureValue);}finally{await fixtureValue.close();}};
class FrozenD1 {
 constructor(){this.sqlite=new DatabaseSync(':memory:');this.sqlite.exec('PRAGMA foreign_keys=ON');for(const file of fs.readdirSync(new URL('../drizzle/',import.meta.url)).filter(file=>file.endsWith('.sql')).sort())this.sqlite.exec(fs.readFileSync(new URL(`../drizzle/${file}`,import.meta.url),'utf8'));}
 prepare(sql){const sqlite=this.sqlite;let args=[];return {bind(...values){args=values;return this;},async all(){return {results:sqlite.prepare(sql).all(...args)};},async first(){return sqlite.prepare(sql).get(...args)??null;},run(){return {meta:{changes:Number(sqlite.prepare(sql).run(...args).changes)}};}};}
 async batch(statements){this.sqlite.exec('BEGIN IMMEDIATE');try{const result=statements.map(statement=>statement.run());this.sqlite.exec('COMMIT');return result;}catch(error){this.sqlite.exec('ROLLBACK');throw error;}}
}

test('actual PostgreSQL applies all 14 tables and hosted smoke preserves original corrected evidence',async()=>{
 const value=await createLocalPostgres();try{const inventory=await postgresSchemaInventory(value.db);assert.equal(inventory.schema_complete,true);assert.equal(inventory.expected_tables,14);assert.match(inventory.postgres_version,/PostgreSQL/);const proof=await exercisePostgresSmoke(value.db);assert.equal(proof.retained_original_population,42);assert.equal(proof.resolved_population,43);assert.match(value.schema_sha256,/^[a-f0-9]{64}$/);}finally{await value.close();}
});
test('PostgreSQL claim/name readers preserve JSON bytes, stable identities, half-open dates, nulls and examples',withFixture(async({db,engine})=>{
 const metadata={original_wording:'Catholic sources; uncertain attribution',share:.61};const payload={ingestion_id:'claim-original',records:[record('owner-derived','owner','owner A',{category_id:'owner:a',method:'majority-area',metadata}),record('owner-direct-unknown','owner',null),record('population','population',42054),record('example-population','population',9,{source_id:'example',is_example:1})],names:[{id:'historical-name',entity_id:'location',name:'Historical place',language:'und',valid_from:1000,valid_to:1100,source_id:'history'}]};
 assert.equal((await importBatch(db,payload)).duplicate,false);assert.equal((await importBatch(db,payload)).duplicate,true);
 const active=(await attributesAt(db,1000)).records;assert.equal(active.length,3);assert.equal(active.find(row=>row.id==='owner-direct-unknown').value,null);assert.deepEqual(active.find(row=>row.id==='owner-derived').metadata,metadata);assert.equal((await attributesAt(db,1100)).records.length,0);assert.equal((await attributesAt(db,1000,{examples:true})).records.length,4);await assert.rejects(attributesAt(db,0),/year/);
 assert.equal((await namesAt(db,1000)).records[0].value,'Historical place');assert.equal((await entityProfile(db,'location',1000)).display_name,'Historical place');assert.equal((await entityProfile(db,'location',1100)).display_name,null);
 const raw=(await engine.query("SELECT value,metadata FROM atlas_attribute_records WHERE id='owner-derived'")).rows[0];assert.equal(raw.value,'"owner A"');assert.equal(raw.metadata,JSON.stringify({original_wording:metadata.original_wording,share:.61}));
 const resolved=resolveAttributes([{id:'location',properties:{}}],1000,{records:active}).get('location');assert.equal(resolved.owner,null);assert.equal(resolved.population,42054);
}));
test('PostgreSQL guards reject interval/source/classification/owner contradictions and roll back complete failed batches',withFixture(async({db,engine})=>{
 for(const row of [record('outside','population',1,{valid_from:999}),record('bad-reference','climate','climate:Cfb',{source_id:'reference'}),record('bad-estimate','population',1,{source_id:'estimate'}),record('unknown-known','population',1,{status:'unknown'}),record('invalid-env','vegetation','made-up-land-cover')])await assert.rejects(importBatch(db,{records:[row]}),contractRejected);
 await importBatch(db,{records:[record('original','population',10)]});await assert.rejects(importBatch(db,{ingestion_id:'failed-batch',sources:[source('must-rollback')],records:[record('original','population',20)]}),contractRejected);assert.equal((await engine.query("SELECT count(*)::int n FROM atlas_sources WHERE id='must-rollback'")).rows[0].n,0);assert.equal((await engine.query("SELECT count(*)::int n FROM atlas_ingestions WHERE id='failed-batch'")).rows[0].n,0);
 await assert.rejects(importBatch(db,{records:[record('overlap','population',30)]}),contractRejected);
 await assert.rejects(engine.query("UPDATE atlas_attribute_records SET value='11' WHERE id='original'"),/immutable|append-only/i);await assert.rejects(engine.query("DELETE FROM atlas_sources WHERE id='history'"),/retained|append-only/i);
 const rawInsert="INSERT INTO atlas_attribute_records(id,location_id,attribute,value,valid_from,valid_to,source_id,method,status,is_example,metadata) VALUES($1,'location',$2,$3,1000,1100,'history','direct',$4,0,'{}')";
 await assert.rejects(engine.query(rawInsert,['raw-invalid-env','vegetation','"made-up-land-cover"','sourced']),/classification|vegetation|environment/i);
 await assert.rejects(engine.query(rawInsert,['raw-invalid-unknown','climate','"climate:Cfb"','unknown']),/unresolved|unknown|null/i);
 await assert.rejects(engine.query("INSERT INTO atlas_attribute_records(id,location_id,attribute,value,valid_from,valid_to,source_id,method,status,is_example,metadata) VALUES('raw-outside','location','culture','null',999,1100,'history','direct','unknown',0,'{}')"),/source|supported|interval/i);
}));
test('PostgreSQL atomic correction retires overlap, retains old bytes and cannot resurrect immutable evidence',withFixture(async({db,engine})=>{
 const old=record('old','population',42,{metadata:{original:'retained bytes'}});await importBatch(db,{records:[old]});const correction={ingestion_id:'correction',retirements:[retirement('retire-old','old','replacement')],records:[record('replacement','population',43)]};await importBatch(db,correction);assert.equal((await importBatch(db,correction)).duplicate,true);assert.deepEqual((await attributesAt(db,1000)).records.map(row=>row.id),['replacement']);await importBatch(db,{records:[old]});assert.deepEqual((await attributesAt(db,1000)).records.map(row=>row.id),['replacement']);const retained=await evidenceHistory(db,'records','old');assert.equal(retained.claim.value,42);assert.equal(retained.claim.metadata.original,'retained bytes');assert.equal(retained.status,'superseded');assert.equal((await retirementsAt(db,1000,{mapOnly:true})).records[0].target_id,'old');
 await assert.rejects(importBatch(db,{retirements:[retirement('retire-replacement','replacement','invalid')],records:[record('invalid','population',44,{source_id:'missing'})]}));assert.equal((await engine.query("SELECT count(*)::int n FROM atlas_evidence_retirements WHERE id='retire-replacement'")).rows[0].n,0);assert.equal((await attributesAt(db,1000)).records[0].id,'replacement');
}));
test('PostgreSQL rank/habitation and fixed environment guards match literal-zero proof policy',withFixture(async({db})=>{
 await importBatch(db,{records:[record('estimated-zero','population',0,{method:'estimate',source_id:'estimate',metadata:{modeled:true}}),record('climate','climate','climate:Cfb'),record('vegetation','vegetation','vegetation:farmlands'),record('topography','topography','topography:flat')]});let resolved=resolveAttributes([{id:'location',properties:{}}],1000,{records:(await attributesAt(db,1000)).records}).get('location');assert.equal(resolved.rank,null);assert.equal(resolved.category_ids.climate,'climate:Cfb');
 await importBatch(db,{records:[record('literal-zero','population',0)]});resolved=resolveAttributes([{id:'location',properties:{}}],1000,{records:(await attributesAt(db,1000)).records}).get('location');assert.equal(resolved.rank,'unsettled');await assert.rejects(importBatch(db,{records:[record('contradict-city','rank','city')]}),contractRejected);
 await importBatch(db,{retirements:[retirement('retire-zero','literal-zero')],records:[record('now-city','rank','city'),record('positive','population',100)]});assert.equal(resolveAttributes([{id:'location',properties:{}}],1000,{records:(await attributesAt(db,1000)).records}).get('location').rank,'city');
}));
test('PostgreSQL catalogs/graph/media paging and compact map use actual hosted SQL with whole-location parity',withFixture(async({db})=>{
 await importBatch(db,{entities:[{id:'person',kind:'person',name:'Historical person'}],records:[record('pop','population',42),record('owner','owner','owner A',{category_id:'owner:a'})],relationships:[{id:'association',source_entity_id:'person',target_entity_id:'location',relationship_type:'associated_with',source_id:'history',valid_from:1000,valid_to:1100}],names:[{id:'location-name',entity_id:'location',name:'Dated location',source_id:'history',valid_from:1000,valid_to:1100}]});
 assert.equal((await catalogPage(db,'sources',{q:'history'})).records[0].id,'history');assert.equal((await catalogPage(db,'categories',{kind:'owner'})).records[0].id,'owner:a');assert.equal((await catalogPage(db,'entities',{kind:'location'})).records[0].id,'location');assert.equal((await entityRelationshipsPage(db,'location',1000)).records[0].source_entity_id,'person');assert.equal((await entityRelationshipsPage(db,'location',1100)).records.length,0);
 const sha='c'.repeat(64);await registerMedia(db,{id:'media',object_key:`media/${sha}`,sha256:sha,bytes:42,mime:'audio/wav',name:'Isolated sound',license:'CC0',attribution:'Test-only',source_id:'history'});await importBatch(db,{media_links:[{id:'media-link',media_id:'media',entity_id:'location',role:'reference-audio',source_id:'history'}]});assert.equal((await entityMediaPage(db,'location',1000)).records[0].sha256,sha);
 const compact=hydrateMapSnapshotPage(await mapSnapshotPage(db,1000,{limit:1000})),full=(await attributesAt(db,1000)).records;assert.equal(compact.entities.length,6);assert.equal(compact.names[0].value,'Dated location');assert.deepEqual(resolveAttributes([{id:'location',properties:{}}],1000,{records:compact.records}),resolveAttributes([{id:'location',properties:{}}],1000,{records:full}));
}));
test('PostgreSQL stages and publishes complete pinned reference geography without mutating registry/evidence',withFixture(async({db,engine})=>{
 const extra=Array.from({length:5},(_,continent)=>tiers.map((kind,index)=>({id:`${kind}-${continent}`,kind,name:`Test-only ${kind} ${continent}`,parent_id:index?`${tiers[index-1]}-${continent}`:null}))).flat();await importBatch(db,{entities:extra});
 const members=[...tiers.map((kind,index)=>({entity_id:kind,kind,parent_id:index?tiers[index-1]:null,reference_name:`Reference ${kind}`,active:1,source_id:'reference',evidence:{method:'pinned-test-reference'}})),...extra.map(entity=>({entity_id:entity.id,kind:entity.kind,parent_id:entity.parent_id,reference_name:entity.name,active:1,source_id:'reference',evidence:{method:'pinned-test-reference'}}))];
 const release={id:'postgres-release',version:1,source_id:'reference',reference_date:'2026-10-01',hierarchy_sha256:'a'.repeat(64),footprints_sha256:'b'.repeat(64),membership_sha256:await geographicMembershipHash(members),location_ids_sha256:await geographicLocationIdsHash(members),changes_sha256:await geographicChangesHash([]),expected_counts:Object.fromEntries(tiers.map(kind=>[kind,6])),metadata:{test_only:true}};
 await stageGeographicRelease(db,{release,memberships:members});assert.equal(await geographicRelease(db),null);assert.equal((await finalizeGeographicRelease(db,release.id)).status,'published');assert.equal((await finalizeGeographicRelease(db,release.id)).duplicate,true);assert.equal((await geographicMembershipPage(db,{parentId:'province'})).records[0].reference_name,'Reference location');assert.equal((await entityProfile(db,'location',1000)).name,'Reference location');assert.equal((await engine.query("SELECT name FROM atlas_entities WHERE id='location'")).rows[0].name,'Original location');await assert.rejects(engine.query("UPDATE atlas_geographic_memberships SET reference_name='mutation' WHERE entity_id='location'"),/immutable|append-only/i);await assert.rejects(engine.query("DELETE FROM atlas_geographic_releases WHERE id='postgres-release'"),/retained|append-only/i);
}));
test('actual PostgreSQL and frozen D1 produce identical evidence/source bytes and selected-year service values',async()=>{
 const pg=await createLocalPostgres(),sqlite=new FrozenD1();try{
  const collections=[JSON.parse(fs.readFileSync(new URL('../data/hosted-type-catalog.json',import.meta.url))),{sources:[source()],entities:tiers.map((kind,index)=>({id:kind,kind,name:`Original ${kind}`,parent_id:index?tiers[index-1]:null})),categories:[{id:'owner:a',kind:'owner',name:'owner A',source_id:'history'}]},{records:[record('parity-owner','owner','owner A',{category_id:'owner:a',metadata:{source_wording:'Distinct spelling retained',share:.63}}),record('parity-population','population',42054),record('parity-climate','climate','climate:Cfb')],names:[{id:'parity-name',entity_id:'location',name:'Historic name',language:'und',valid_from:1000,valid_to:1100,source_id:'history'}]}];
  for(const input of collections){await importBatch(pg.db,input);await importBatch(sqlite,input);}
  assert.deepEqual((await attributesAt(pg.db,1000)).records,(await attributesAt(sqlite,1000)).records);assert.deepEqual((await namesAt(pg.db,1000)).records,(await namesAt(sqlite,1000)).records);
  const pgClaims=(await pg.engine.query('SELECT id,value,metadata FROM atlas_attribute_records ORDER BY id')).rows,sqliteClaims=sqlite.sqlite.prepare('SELECT id,value,metadata FROM atlas_attribute_records ORDER BY id').all().map(row=>({...row}));assert.deepEqual(pgClaims,sqliteClaims);
  const pgSources=(await pg.engine.query('SELECT id,metadata FROM atlas_sources ORDER BY id')).rows,sqliteSources=sqlite.sqlite.prepare('SELECT id,metadata FROM atlas_sources ORDER BY id').all().map(row=>({...row}));assert.deepEqual(pgSources,sqliteSources);
 }finally{await pg.close();sqlite.sqlite.close();}
});
test('PostgreSQL compact metadata summaries retain zero-population proof semantics and evidence links',withFixture(async({db})=>{
 await importBatch(db,{records:[record('large-modeled-zero','population',0,{metadata:{details:'x'.repeat(2500),precision:'modeled and rounded estimate',modeled:true}})],sources:[{...source('large-source'),metadata:{details:'x'.repeat(3000)}}],names:[{id:'large-name',entity_id:'location',name:'Dated name',source_id:'large-source',valid_from:1000,valid_to:1100,metadata:{details:'x'.repeat(2500)}}]});
 const page=hydrateMapSnapshotPage(await mapSnapshotPage(db,1000)),claim=page.records.find(row=>row.id==='large-modeled-zero');assert.equal(claim.metadata_truncated,1);assert.equal(claim.metadata.modeled,1);assert.match(claim.evidence_url,/evidence\/records\/large-modeled-zero/);assert.equal(page.names[0].source_metadata_truncated,true);
 assert.equal(resolveAttributes([{id:'location',properties:{}}],1000,{records:page.records}).get('location').rank,null);assert.equal((await evidenceHistory(db,'records','large-modeled-zero')).claim.metadata.details.length,2500);
 await importBatch(db,{retirements:[retirement('withdraw-modeled','large-modeled-zero')],records:[record('large-literal-zero','population',0,{metadata:{details:'x'.repeat(2500),precision:{source:'literal observed zero'}}})]});
 const literal=hydrateMapSnapshotPage(await mapSnapshotPage(db,1000));assert.equal(resolveAttributes([{id:'location',properties:{}}],1000,{records:literal.records}).get('location').rank,'unsettled');
}));
test('PostgreSQL geographic transaction guards reject unpublished/stale hashes and retain pinned replay receipts',withFixture(async({db,engine})=>{
 const extras=Array.from({length:5},(_,c)=>tiers.map((kind,i)=>({id:`pin:${c}:${kind}`,kind,name:kind,parent_id:i?`pin:${c}:${tiers[i-1]}`:null}))).flat();await importBatch(db,{entities:extras});
 const members=[...tiers.map((kind,i)=>({entity_id:kind,kind,parent_id:i?tiers[i-1]:null})),...extras.map(row=>({entity_id:row.id,kind:row.kind,parent_id:row.parent_id}))].map(row=>({...row,active:1,source_id:'reference',evidence:{test_only:true}}));
 const manifest=async(id,version)=>({id,version,source_id:'reference',reference_date:'2026-10-02',hierarchy_sha256:'a'.repeat(64),footprints_sha256:'b'.repeat(64),membership_sha256:await geographicMembershipHash(members),location_ids_sha256:await geographicLocationIdsHash(members),changes_sha256:await geographicChangesHash([]),expected_counts:Object.fromEntries(tiers.map(kind=>[kind,6]))});
 const first=await manifest('pin:first',1),pin={release_id:first.id,hierarchy_sha256:first.hierarchy_sha256,footprints_sha256:first.footprints_sha256};await stageGeographicRelease(db,{release:first,memberships:members});
 await assert.rejects(importBatch(db,{expected_geography:pin,sources:[source('staged-must-rollback')]}),error=>error.status===409&&error.retryable);assert.equal((await engine.query("SELECT count(*)::int n FROM atlas_sources WHERE id='staged-must-rollback'")).rows[0].n,0);
 await finalizeGeographicRelease(db,first.id);const payload={ingestion_id:'pg:pinned',expected_geography:pin,records:[record('pg:pinned-pop','population',42)]},original=await importBatch(db,payload);assert.deepEqual(original.expected_geography,pin);
 const retained=(await engine.query("SELECT * FROM atlas_ingestions WHERE id='pg:pinned'")).rows[0];const second=await manifest('pin:second',2);await stageGeographicRelease(db,{release:second,memberships:members});await finalizeGeographicRelease(db,second.id);
 const replay=await importBatch(db,payload);assert.equal(replay.duplicate,true);assert.deepEqual(replay.expected_geography,pin);assert.deepEqual((await engine.query("SELECT * FROM atlas_ingestions WHERE id='pg:pinned'")).rows[0],retained);
 await assert.rejects(importBatch(db,{expected_geography:pin,sources:[source('stale-must-rollback')]}),error=>error.status===409&&error.retryable&&!/22P02|postgresql:\/\//.test(error.message));assert.equal((await engine.query("SELECT count(*)::int n FROM atlas_sources WHERE id='stale-must-rollback'")).rows[0].n,0);
 await assert.rejects(importBatch(db,{ingestion_id:payload.ingestion_id,records:payload.records}),error=>error.status===409);
 const current={...pin,release_id:second.id};await assert.rejects(importBatch(db,{expected_geography:{...current,footprints_sha256:'c'.repeat(64)},sources:[source('hash-mismatch')]}),error=>error.status===409);
 assert.deepEqual((await importBatch(db,{expected_geography:current,sources:[source('fresh-pinned-source')]})).expected_geography,current);
}));
