import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createLocalPostgres,exercisePostgresSmoke,postgresTables} from '../scripts/verify-postgres-schema.mjs';
import {provisionPostgresRuntimeRole,verifyPostgresRuntimeRole} from '../scripts/provision-postgres-runtime-role.mjs';
import {importBatch,attributesAt,evidenceHistory} from '../hosted/records.js';
import {catalogPage} from '../hosted/research-catalog.js';
import {mapSnapshotPage} from '../hosted/map-snapshots.js';
import {stageGeographicRelease,finalizeGeographicRelease,geographicMembershipHash,geographicLocationIdsHash,geographicChangesHash} from '../hosted/geographic-releases.js';

const password="test-only-private-password-'quoted'-\\-not-live-0123456789";
const administration=value=>({query:(sql,params)=>value.engine.query(sql,params),runTransaction:callback=>value.engine.transaction(tx=>callback({query:(sql,params)=>tx.query(sql,params)}))});
async function local(callback){const value=await createLocalPostgres();try{await callback(value,administration(value));}finally{await value.close();}}

test('actual restricted LOGIN runs hosted imports, corrections, idempotent retries and selected-year readers',()=>local(async(value,driver)=>{
 const before=(await value.engine.query("SELECT nspacl::text AS acl FROM pg_namespace WHERE nspname='public'")).rows[0].acl;
 const proof=await provisionPostgresRuntimeRole({driver,password});assert.equal(proof.password_action,'created');assert.equal(proof.permissions.length,14);assert.ok(!JSON.stringify(proof).includes(password));assert.equal((await value.engine.query("SELECT has_schema_privilege('worldatlas_app','public','CREATE') AS allowed")).rows[0].allowed,false);
 await value.engine.query('SET ROLE worldatlas_app');const smoke=await exercisePostgresSmoke(value.db);assert.equal(smoke.retained_original_population,42);assert.equal(smoke.resolved_population,43);const payload={ingestion_id:'app-idempotent',records:[{id:'app-climate',location_id:'pg-verification:location',attribute:'climate',value:'climate:Cfb',valid_from:1000,valid_to:1100,source_id:'pg-verification:source'}]};assert.equal((await importBatch(value.db,payload)).duplicate,false);assert.equal((await importBatch(value.db,payload)).duplicate,true);assert.equal((await attributesAt(value.db,1000)).records.find(row=>row.id==='app-climate').value,'climate:Cfb');assert.equal((await evidenceHistory(value.db,'records','pg-verification:old')).status,'superseded');assert.ok((await catalogPage(value.db,'sources')).records.length);assert.ok((await mapSnapshotPage(value.db,1000)).records.length);await value.engine.query('RESET ROLE');
 const checked=await verifyPostgresRuntimeRole(driver);assert.equal(checked.read_only,true);const after=(await value.engine.query("SELECT nspacl::text AS acl FROM pg_namespace WHERE nspname='public'")).rows[0].acl;assert.ok(after.includes('worldatlas_app=U/'));assert.ok(before===null||after.includes(before.slice(1,-1)),'Existing PUBLIC and owner schema privileges remain unchanged');
}));
test('runtime role cannot mutate facts, suppress guards, restore revisions or escalate privileges',()=>local(async(value,driver)=>{
 await provisionPostgresRuntimeRole({driver,password});await value.engine.query('SET SESSION AUTHORIZATION worldatlas_app');assert.deepEqual((await value.engine.query('SELECT current_user,session_user')).rows[0],{current_user:'worldatlas_app',session_user:'worldatlas_app'});await exercisePostgresSmoke(value.db);
 const denied=["UPDATE atlas_sources SET name='Changed' WHERE id='pg-verification:source'","DELETE FROM atlas_attribute_records","TRUNCATE atlas_names","ALTER TABLE atlas_sources DISABLE TRIGGER USER","SET session_replication_role='replica'","ALTER TABLE atlas_sources ADD COLUMN unauthorized text","DROP TABLE atlas_names","ALTER SEQUENCE atlas_ingestions_rowid_seq RESTART WITH 1","SELECT setval('atlas_ingestions_rowid_seq',1)","SELECT last_value FROM atlas_ingestions_rowid_seq","INSERT INTO atlas_ingestions(rowid,id,fingerprint,counts,created_at) VALUES(99,'unauthorized',repeat('a',64),'{}',1)","UPDATE atlas_geographic_releases SET hierarchy_sha256=repeat('b',64)","CREATE TABLE public.unauthorized(id text)","CREATE ROLE unauthorized LOGIN","GRANT worldatlas_app TO CURRENT_USER","SET ROLE postgres"];
 for(const sql of denied)await assert.rejects(value.engine.query(sql),error=>['42501','0LP01'].includes(error.code),sql);
 await value.engine.query("UPDATE atlas_geographic_releases SET status='published',published_at=1 WHERE id='absent' RETURNING *"); // Allowed columns need no table-level UPDATE grant.
 await value.engine.query('SET SESSION AUTHORIZATION postgres');assert.equal((await evidenceHistory(value.db,'records','pg-verification:old')).claim.value,42);
}));
test('restricted publication updates only validated status and publication columns',()=>local(async(value,driver)=>{
 await importBatch(value.db,JSON.parse(fs.readFileSync(new URL('../data/hosted-type-catalog.json',import.meta.url))));await provisionPostgresRuntimeRole({driver,password});await value.engine.query('SET ROLE worldatlas_app');
 const tiers=['continent','subcontinent','region','area','province','location'],entities=Array.from({length:6},(_,continent)=>tiers.map((kind,index)=>({id:`app:${kind}:${continent}`,kind,name:`Test ${kind}`,parent_id:index?`app:${tiers[index-1]}:${continent}`:null}))).flat();await importBatch(value.db,{sources:[{id:'app-reference',name:'Isolated reference',license:'CC0',vintage:'2026',supported_from:2026,supported_to:2027,status:'reference'}],entities});const memberships=entities.map(row=>({entity_id:row.id,kind:row.kind,parent_id:row.parent_id,reference_name:row.name,active:1,source_id:'app-reference',evidence:{method:'isolated-source'}}));const release={id:'app-release',source_id:'app-reference',version:1,reference_date:'2026-10-01',hierarchy_sha256:'a'.repeat(64),footprints_sha256:'b'.repeat(64),membership_sha256:await geographicMembershipHash(memberships),location_ids_sha256:await geographicLocationIdsHash(memberships),changes_sha256:await geographicChangesHash([]),expected_counts:Object.fromEntries(tiers.map(kind=>[kind,6]))};await stageGeographicRelease(value.db,{release,memberships});assert.equal((await finalizeGeographicRelease(value.db,'app-release')).status,'published');assert.equal((await finalizeGeographicRelease(value.db,'app-release')).duplicate,true);await assert.rejects(value.engine.query("UPDATE atlas_geographic_releases SET status='staged',published_at=null WHERE id='app-release'"),error=>error.code==='23514');await value.engine.query('RESET ROLE');
}));
test('idempotent maintenance preserves existing password and explicit rotation safely changes it',()=>local(async(value,driver)=>{
 await provisionPostgresRuntimeRole({driver,password});const original=(await value.engine.query("SELECT rolpassword FROM pg_authid WHERE rolname='worldatlas_app'")).rows[0].rolpassword;const repeated=await provisionPostgresRuntimeRole({driver,password:'different-private-password-never-applied-0123456789'});assert.equal(repeated.password_action,'preserved');assert.equal((await value.engine.query("SELECT rolpassword FROM pg_authid WHERE rolname='worldatlas_app'")).rows[0].rolpassword,original);const without=await provisionPostgresRuntimeRole({driver});assert.equal(without.password_action,'preserved');const rotated=await provisionPostgresRuntimeRole({driver,password:'explicit-rotation-private-password-0123456789',rotatePassword:true});assert.equal(rotated.password_action,'explicitly rotated');assert.notEqual((await value.engine.query("SELECT rolpassword FROM pg_authid WHERE rolname='worldatlas_app'")).rows[0].rolpassword,original);await assert.rejects(provisionPostgresRuntimeRole({driver,rotatePassword:true}));
}));
test('existing inherited, privileged, owning or broadly granted role is rejected without silent downgrade',async()=>{
 for(const setup of ["CREATE ROLE worldatlas_app LOGIN INHERIT","CREATE ROLE worldatlas_app LOGIN NOINHERIT CREATEDB","CREATE ROLE worldatlas_app LOGIN NOINHERIT; GRANT postgres TO worldatlas_app","CREATE ROLE worldatlas_app LOGIN NOINHERIT; ALTER TABLE atlas_sources OWNER TO worldatlas_app","CREATE ROLE worldatlas_app LOGIN NOINHERIT; GRANT DELETE ON atlas_sources TO worldatlas_app","CREATE ROLE worldatlas_app LOGIN NOINHERIT; GRANT INSERT ON atlas_ingestions TO worldatlas_app","CREATE ROLE worldatlas_app LOGIN NOINHERIT; GRANT UPDATE ON SEQUENCE atlas_ingestions_rowid_seq TO worldatlas_app","CREATE ROLE worldatlas_app LOGIN NOINHERIT; GRANT SET ON PARAMETER session_replication_role TO worldatlas_app","CREATE ROLE worldatlas_app LOGIN NOINHERIT; CREATE SCHEMA unrelated; GRANT CREATE ON SCHEMA unrelated TO worldatlas_app","CREATE ROLE worldatlas_app LOGIN NOINHERIT; GRANT REFERENCES(id) ON atlas_sources TO worldatlas_app"]){await local(async(value,driver)=>{await value.engine.exec(setup);await assert.rejects(provisionPostgresRuntimeRole({driver,password}),error=>error.code==='42501');assert.equal((await value.engine.query("SELECT has_table_privilege('worldatlas_app','atlas_names','SELECT') AS granted")).rows[0].granted,false);});}
});
test('weak credentials and inherited PUBLIC schema CREATE prevent reopening without weakening PUBLIC permissions',()=>local(async(value,driver)=>{
 await assert.rejects(provisionPostgresRuntimeRole({driver,password:'short'}),/Strong private/);await value.engine.query('GRANT CREATE ON SCHEMA public TO PUBLIC');await assert.rejects(provisionPostgresRuntimeRole({driver,password}),error=>error.code==='42501');assert.equal((await value.engine.query("SELECT count(*)::int n FROM pg_roles WHERE rolname='worldatlas_app'")).rows[0].n,0);assert.equal((await value.engine.query("SELECT has_schema_privilege('public','public','CREATE') AS allowed")).rows[0].allowed,true);
}));
test('non-superuser schema owner retains only automatic ADMIN-without-INHERIT-or-SET role management',()=>local(async(value,driver)=>{
 await value.engine.exec('CREATE ROLE fixture_owner LOGIN CREATEROLE NOINHERIT');const database=(await value.engine.query('SELECT current_database() AS name')).rows[0].name;assert.match(database,/^[a-z_]+$/);await value.engine.query(`ALTER DATABASE ${database} OWNER TO fixture_owner`);for(const table of postgresTables)await value.engine.query(`ALTER TABLE ${table} OWNER TO fixture_owner`);await value.engine.query('ALTER SEQUENCE atlas_ingestions_rowid_seq OWNER TO fixture_owner');await value.engine.query('SET SESSION AUTHORIZATION fixture_owner');
 const proof=await provisionPostgresRuntimeRole({driver,password});assert.equal(proof.owner_administration_membership,1);assert.equal(proof.memberships,0);assert.deepEqual((await value.engine.query("SELECT admin_option,inherit_option,set_option FROM pg_auth_members WHERE roleid=(SELECT oid FROM pg_roles WHERE rolname='worldatlas_app')")).rows,[{admin_option:true,inherit_option:false,set_option:false}]);assert.equal((await provisionPostgresRuntimeRole({driver})).password_action,'preserved');assert.equal((await provisionPostgresRuntimeRole({driver,password:'test-only-explicit-rotation-0123456789',rotatePassword:true})).password_action,'explicitly rotated');await assert.rejects(value.engine.query('SET ROLE worldatlas_app'),error=>error.code==='42501');
 await value.engine.query('SET SESSION AUTHORIZATION postgres');await value.engine.query('SET SESSION AUTHORIZATION worldatlas_app');assert.equal((await verifyPostgresRuntimeRole(driver)).owner_administration_membership,1);await exercisePostgresSmoke(value.db);await assert.rejects(value.engine.query('SET ROLE fixture_owner'),error=>error.code==='42501');await value.engine.query('SET SESSION AUTHORIZATION postgres');
 await value.engine.exec('CREATE ROLE unreviewed_admin NOINHERIT; GRANT worldatlas_app TO unreviewed_admin WITH ADMIN TRUE, INHERIT FALSE, SET FALSE');await assert.rejects(verifyPostgresRuntimeRole(driver),/membership/);await value.engine.query('SET SESSION AUTHORIZATION fixture_owner');await assert.rejects(provisionPostgresRuntimeRole({driver,password}),error=>error.code==='42501');await value.engine.query('SET SESSION AUTHORIZATION postgres');
}));
