import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {gzipSync,gunzipSync} from 'node:zlib';
import {DatabaseSync} from 'node:sqlite';
import {prepareEvidenceBundle} from '../scripts/prepare-evidence-bundle.mjs';
import {preparedEvidenceAt} from '../prepared-evidence.mjs';
import {preparedEvidencePartsAt,selectPreparedEvidence,verifyPreparedEvidencePart,verifyPreparedEvidenceIndexBytes,mergePreparedEvidence} from '../src/prepared-evidence.js';
import {resolveAttributes} from '../src/attributes.js';
import {resolveTemporal} from '../src/temporal.js';
import {importBatch,namesAt,attributesAt} from '../hosted/records.js';
const sha=b=>createHash('sha256').update(b).digest('hex');
const root=path.resolve(import.meta.dirname,'..');
const read=file=>JSON.parse(file.endsWith('.gz')?gunzipSync(fs.readFileSync(file)):fs.readFileSync(file));
const source=(id,status,from=2020,to=2021)=>({id,name:id,url:'https://example.org/test-only-source',license:'CC0',vintage:String(from),supported_from:from,supported_to:to,status,metadata:{sha256:'a'.repeat(64)}});
function fixture(){const folder=fs.mkdtempSync(path.join(os.tmpdir(),'atlas-prepared-evidence-'));const units=['continent','subcontinent','region','area','province'].map((level,i)=>({id:level,name:level,level,parent_id:i?['continent','subcontinent','region','area'][i-1]:null})),feature={id:'location',properties:{id:'location',name:'Reference territory',parent_id:'province'},geometry:{type:'Polygon',coordinates:[[[0,0],[1,0],[1,1],[0,1],[0,0]]]}};fs.mkdirSync(`${folder}/geography`);fs.writeFileSync(`${folder}/hierarchy.json`,JSON.stringify(units));fs.writeFileSync(`${folder}/world-index.json`,JSON.stringify({parts:['geography/part-0.json']}));fs.writeFileSync(`${folder}/geography/part-0.json`,JSON.stringify({features:[feature]}));const nameSource=source('names','reference'),populationSource=source('population','estimate'),religionSource=source('religion','historical',2021,2022);const names=[{id:'name:reference',entity_id:'location',name:'2020 attested name',language:'en',role:'preferred',valid_from:2020,valid_to:2021,source_id:nameSource.id,is_example:0,metadata:{snapshot_only:true}}],records=[{id:'population:estimate',location_id:'location',attribute:'population',value:0,category_id:null,valid_from:2020,valid_to:2021,source_id:populationSource.id,method:'estimate',status:'estimate',is_example:0,metadata:{estimate:true,rounded:true}},{id:'religion:derived',location_id:'location',attribute:'religion',value:'Christianity',category_id:'religion:Q5043',valid_from:2021,valid_to:2022,source_id:religionSource.id,method:'derived',status:'derived',is_example:0,metadata:{share:0.6,assignment_method:'population-share'}}];for(const [id,kind,rows,sources] of [['names','names',names,[nameSource]],['attributes','records',records,[populationSource,religionSource]]]){fs.mkdirSync(`${folder}/${id}`);fs.writeFileSync(`${folder}/${id}/rows.json.gz`,gzipSync(JSON.stringify(rows)));fs.writeFileSync(`${folder}/${id}/index.json`,JSON.stringify({version:1,sources,parts:[{path:'rows.json.gz',sha256:sha(fs.readFileSync(`${folder}/${id}/rows.json.gz`))}],records:rows.length,hierarchy_sha256:sha(fs.readFileSync(`${folder}/hierarchy.json`))}));}fs.writeFileSync(`${folder}/attributes/categories.json`,JSON.stringify([{id:'religion:Q5043',kind:'religion',name:'Christianity',source_id:'religion',metadata:{taxonomy:'Broad category'}}]));return {folder,units,feature,names,records,products:[{id:'names',kind:'names'},{id:'attributes',kind:'records'}]};}
const build=f=>prepareEvidenceBundle({data:f.folder,products:f.products});
const browserAt=async(f,index,year)=>{const parts=[];for(const p of preparedEvidencePartsAt(index,year)){const rows=read(`${f.folder}/prepared-evidence/${p.path}`);await verifyPreparedEvidencePart(p,rows);parts.push({path:p.path,rows});}return selectPreparedEvidence(index,parts,year);};
class D1{constructor(){this.sqlite=new DatabaseSync(':memory:');this.sqlite.exec('PRAGMA foreign_keys=ON');for(const name of fs.readdirSync(`${root}/drizzle`).filter(f=>f.endsWith('.sql')).sort())this.sqlite.exec(fs.readFileSync(`${root}/drizzle/${name}`,'utf8'));}prepare(sql){let args=[];const db=this.sqlite;return {bind(...v){args=v;return this;},async first(){return db.prepare(sql).get(...args)??null;},async all(){return {results:db.prepare(sql).all(...args)};},run(){return {meta:{changes:Number(db.prepare(sql).run(...args).changes)}};}};}async batch(parts){this.sqlite.exec('BEGIN');try{const r=parts.map(p=>p.run());this.sqlite.exec('COMMIT');return r;}catch(e){this.sqlite.exec('ROLLBACK');throw e;}}}

test('browser/server adapters agree, use only matching source intervals, and preserve complete provenance',async()=>{const f=fixture();try{const index=build(f);for(const year of [-3000,-1,1,1000,2020,2021,2022,2026])assert.deepEqual(await browserAt(f,index,year),preparedEvidenceAt(year,{directory:`${f.folder}/prepared-evidence`}));const at2020=await browserAt(f,index,2020);assert.equal(at2020.names[0].field,'name');assert.equal(at2020.names[0].value,'2020 attested name');assert.equal(at2020.names[0].name_role,'preferred');assert.equal(at2020.names[0].source_status,'reference');assert.equal(at2020.records[0].source_license,'CC0');assert.equal(at2020.records[0].source_from,2020);assert.equal(at2020.records[0].metadata.estimate,true);assert.deepEqual(preparedEvidencePartsAt(index,2026),[]);assert.throws(()=>preparedEvidencePartsAt(index,0),/Invalid selected year/);const resolved=resolveAttributes([f.feature],2020,{records:at2020.records});assert.equal(resolved.get('location').population,0);assert.equal(resolved.get('location').rank,null,'Estimated zero cannot infer Unsettled');assert.equal((await browserAt(f,index,2021)).records[0].value,'Christianity');}finally{fs.rmSync(f.folder,{recursive:true,force:true});}});

test('source bounds, producer byte hashes, current identity and geography proof failures block publication',()=>{for(const mutation of ['interval','producer-hash','hierarchy','identity','footprint']){const f=fixture();try{const indexFile=`${f.folder}/names/index.json`,index=read(indexFile);if(mutation==='interval'){const rows=read(`${f.folder}/names/rows.json.gz`);rows[0].valid_from=2019;fs.writeFileSync(`${f.folder}/names/rows.json.gz`,gzipSync(JSON.stringify(rows)));index.parts[0].sha256=sha(fs.readFileSync(`${f.folder}/names/rows.json.gz`));}if(mutation==='producer-hash')index.parts[0].sha256='0'.repeat(64);if(mutation==='hierarchy')index.hierarchy_sha256='0'.repeat(64);if(mutation==='footprint')index.footprints_sha256='0'.repeat(64);if(mutation==='identity'){const rows=read(`${f.folder}/names/rows.json.gz`);rows[0].entity_id='missing';fs.writeFileSync(`${f.folder}/names/rows.json.gz`,gzipSync(JSON.stringify(rows)));index.parts[0].sha256=sha(fs.readFileSync(`${f.folder}/names/rows.json.gz`));}fs.writeFileSync(indexFile,JSON.stringify(index));assert.throws(()=>build(f),/interval|hash|geography|identity/);assert.equal(fs.existsSync(`${f.folder}/prepared-evidence/index.json`),false);}finally{fs.rmSync(f.folder,{recursive:true,force:true});}}});

test('both runtime paths reject stale manifests and tampered prepared assets',async()=>{const f=fixture();try{const index=build(f),part=index.parts.find(p=>p.kind==='names');assert.throws(()=>selectPreparedEvidence(index,[],2020,{expected:{hierarchy_sha256:'0'.repeat(64)}}),/Stale/);const rows=read(`${f.folder}/prepared-evidence/${part.path}`);rows[0].name='Tampered';await assert.rejects(verifyPreparedEvidencePart(part,rows),/hash mismatch/);fs.writeFileSync(`${f.folder}/prepared-evidence/${part.path}`,gzipSync(JSON.stringify(rows)));assert.throws(()=>preparedEvidenceAt(2020,{directory:`${f.folder}/prepared-evidence`}),/asset hash mismatch/);fs.writeFileSync(`${f.folder}/hierarchy.json`,JSON.stringify([...f.units,{id:'new',level:'province',name:'New',parent_id:'area'}]));assert.throws(()=>preparedEvidenceAt(2026,{directory:`${f.folder}/prepared-evidence`}),/Stale/);}finally{fs.rmSync(f.folder,{recursive:true,force:true});}});

test('duplicate input identities are rejected and hosted duplicates retain imported evidence without dropping prepared metadata',async()=>{const f=fixture();try{const index=build(f),prepared=await browserAt(f,index,2020),hosted={...prepared.names[0],metadata:{direct_import:true},method:'direct',source_status:'historical'};const merged=mergePreparedEvidence([], [hosted],prepared);assert.equal(merged.names.length,1);assert.equal(merged.names[0].metadata.direct_import,true);assert.equal(merged.records[0].metadata.estimate,true);const manifest=read(`${f.folder}/names/index.json`),rows=read(`${f.folder}/names/rows.json.gz`);rows.push({...rows[0]});fs.writeFileSync(`${f.folder}/names/rows.json.gz`,gzipSync(JSON.stringify(rows)));manifest.parts[0].sha256=sha(fs.readFileSync(`${f.folder}/names/rows.json.gz`));fs.writeFileSync(`${f.folder}/names/index.json`,JSON.stringify(manifest));assert.throws(()=>build(f),/Duplicate prepared identity/);}finally{fs.rmSync(f.folder,{recursive:true,force:true});}});

test('bounded persistent batches import through actual hosted schema/service and are idempotent',async()=>{const f=fixture(),db=new D1();try{const index=build(f);await importBatch(db,read(`${root}/data/hosted-type-catalog.json`));await importBatch(db,{entities:[...f.units.map(u=>({...u,kind:u.level})),{id:'location',kind:'location',name:'Reference territory',parent_id:'province'}]});const imports=read(`${f.folder}/prepared-evidence/imports/index.json`);for(const p of imports.batches){const file=`${f.folder}/prepared-evidence/imports/${p.path}`,raw=fs.readFileSync(file);assert.equal(sha(raw),p.sha256);assert.ok(p.rows<=200);assert.ok(raw.length<=1048576);const payload=JSON.parse(raw);assert.equal((await importBatch(db,payload)).duplicate,false);assert.equal((await importBatch(db,payload)).duplicate,true);}const browser=await browserAt(f,index,2020),hostedNames=(await namesAt(db,2020)).records;assert.equal(hostedNames[0].value,browser.names[0].value);assert.deepEqual(hostedNames[0].source_metadata,browser.names[0].source_metadata);assert.equal((await attributesAt(db,2020)).records[0].value,browser.records[0].value);assert.deepEqual((await attributesAt(db,2020)).records[0].source_metadata,browser.records[0].source_metadata);assert.equal(db.sqlite.prepare("SELECT kind FROM atlas_entities WHERE id='religion:Q5043'").get().kind,'religion');assert.equal((await namesAt(db,2026)).records.length,0);assert.equal((await attributesAt(db,2026)).records.length,0);assert.equal(db.sqlite.prepare('PRAGMA foreign_key_check').all().length,0);}finally{db.sqlite.close();fs.rmSync(f.folder,{recursive:true,force:true});}});

test('prepared reference attestations retain direct historical name priority and aliases do not become preferred',async()=>{const f=fixture();try{const index=build(f),prepared=await browserAt(f,index,2020),direct={id:'direct-name',entity_id:'location',field:'name',value:'Historical source name',language:'und',name_role:'preferred',valid_from:2019,valid_to:2022,is_example:0,method:'direct',source_status:'historical'};const reference={units:f.units,features:[f.feature],temporal:{entities:[...f.units.map(u=>({...u,kind:u.level})),{id:'location',kind:'location',name:'Reference territory',parent_id:'province'}],history:[direct,...prepared.names],links:[]}};assert.equal(resolveTemporal(reference,2020).entities.get('location').display_name,'Historical source name');reference.temporal.history=[{...direct,name_role:'alias'},...prepared.names];assert.equal(resolveTemporal(reference,2020).entities.get('location').display_name,'2020 attested name');}finally{fs.rmSync(f.folder,{recursive:true,force:true});}});

test('retirement pages prevent every prepared fallback from resurrecting withdrawn names or attributes',async()=>{
 const f=fixture(),db=new D1();try{
  const index=build(f);await importBatch(db,read(`${root}/data/hosted-type-catalog.json`));await importBatch(db,{entities:[...f.units.map(u=>({...u,kind:u.level})),{id:'location',kind:'location',name:'Reference territory',parent_id:'province'}]});
  for(const p of read(`${f.folder}/prepared-evidence/imports/index.json`).batches)await importBatch(db,read(`${f.folder}/prepared-evidence/imports/${p.path}`));
  await importBatch(db,{sources:[source('correction','historical')],retirements:[{id:'retirement:name',collection:'names',target_id:'name:reference',source_id:'correction',reason:'Sourced correction'},{id:'retirement:population',collection:'records',target_id:'population:estimate',source_id:'correction',reason:'Sourced correction'}]});
  const {retirementsAt}=await import('../hosted/records.js'),first=await retirementsAt(db,2020,{mapOnly:true,limit:1}),second=await retirementsAt(db,2020,{mapOnly:true,limit:1,cursor:first.next_cursor});
  assert.equal(first.records.length,1);assert.equal(second.records.length,1);assert.equal(second.next_cursor,null);const retired=[...first.records,...second.records];
  assert.deepEqual(mergePreparedEvidence([],[],await browserAt(f,index,2020),{retirements:retired}),{records:[],names:[]});
  assert.deepEqual(mergePreparedEvidence([],[],{records:[{id:'population:estimate',method:'majority-area'}],names:[]},{retirements:retired}),{records:[],names:[]});
  assert.equal((await retirementsAt(db,2021,{mapOnly:true})).records.length,0);
  const worker=(await import('../hosted/worker.js')).default,response=await worker.fetch(new Request('https://example.org/api/retirements?year=2020&scope=map&limit=1'),{DB:db});assert.equal(response.status,200);assert.equal((await response.json()).records.length,1);
 }finally{db.sqlite.close();fs.rmSync(f.folder,{recursive:true,force:true});}
});

test('hosted duplicate enrichment keeps prepared provenance while preserving the imported claim',async()=>{
 const f=fixture();try{const index=build(f),prepared=await browserAt(f,index,2020),imported={...prepared.records[0]};delete imported.source_metadata;const merged=mergePreparedEvidence([imported],[],prepared);assert.deepEqual(merged.records[0].source_metadata,prepared.records[0].source_metadata);assert.equal(merged.records.length,1);}finally{fs.rmSync(f.folder,{recursive:true,force:true});}
});

test('completed real name and census products import persistently and resolve identically without gap filling',async()=>{
 const db=new D1();await importBatch(db,read(`${root}/data/hosted-type-catalog.json`));
 try{
  const index=read(`${root}/data/prepared-evidence/index.json`);assert.equal(index.names,3588);assert.equal(index.records,396);assert.ok(index.pending_products.some(p=>p.id==='population-ghsl'));
  const units=read(`${root}/data/hierarchy.json`),features=read(`${root}/data/world-index.json`).parts.flatMap(p=>read(`${root}/data/${p}`).features),all=new Map([...units.map(u=>[u.id,{id:u.id,kind:u.level,name:u.name,parent_id:u.parent_id}]),...features.map(f=>[f.id,{id:f.id,kind:'location',name:f.properties.name,parent_id:f.properties.parent_id}])]);
  const selected=new Set();for(const p of index.parts)for(const row of read(`${root}/data/prepared-evidence/${p.path}`)){let id=row.entity_id??row.location_id;while(id&&!selected.has(id)){selected.add(id);id=all.get(id)?.parent_id;}}
  for(const kind of ['continent','subcontinent','region','area','province','location']){const rows=[...selected].map(id=>all.get(id)).filter(r=>r?.kind===kind);for(let at=0;at<rows.length;at+=200)await importBatch(db,{entities:rows.slice(at,at+200)});}
  const imports=read(`${root}/data/prepared-evidence/imports/index.json`);for(const part of imports.batches){const payload=read(`${root}/data/prepared-evidence/imports/${part.path}`);assert.equal((await importBatch(db,payload)).duplicate,false);assert.equal((await importBatch(db,payload)).duplicate,true);}
  const getAll=async(fn,year)=>{const rows=[];let cursor='';do{const page=await fn(db,year,{cursor,limit:250});rows.push(...page.records);cursor=page.next_cursor;}while(cursor);return rows;};
  for(const year of [-3000,1000,2020,2021,2022,2026]){
   const prepared=preparedEvidenceAt(year),hosted={records:await getAll(attributesAt,year),names:await getAll(namesAt,year)},merged=mergePreparedEvidence(hosted.records,hosted.names,prepared);
   assert.equal(hosted.records.length,prepared.records.length);assert.equal(hosted.names.length,prepared.names.length);
   assert.deepEqual([...resolveAttributes(features,year,{records:prepared.records})].map(([id,r])=>[id,r.religion]),[...resolveAttributes(features,year,{records:merged.records})].map(([id,r])=>[id,r.religion]));
   for(const kind of ['names','records']){const expected=new Map(prepared[kind].map(r=>[r.id,r]));for(const row of merged[kind])for(const key of ['value','valid_from','valid_to','source_id','source','source_license','source_vintage','source_metadata','metadata'])assert.deepEqual(row[key],expected.get(row.id)[key],`${year}: ${row.id} ${key}`);}
  }
  assert.equal(db.sqlite.prepare('SELECT count(*) n FROM atlas_names').get().n,3588);assert.equal(db.sqlite.prepare('SELECT count(*) n FROM atlas_attribute_records').get().n,396);assert.equal(db.sqlite.prepare('PRAGMA foreign_key_check').all().length,0);
 }finally{db.sqlite.close();}
});


test('public manifest byte pin protects source provenance as well as record parts',async()=>{const f=fixture();try{build(f);const raw=fs.readFileSync(`${f.folder}/prepared-evidence/index.json`),expected={index_sha256:sha(raw)};assert.equal((await verifyPreparedEvidenceIndexBytes(raw,expected)).names,1);const changed=JSON.parse(raw);changed.sources[0].license='Invented license';await assert.rejects(verifyPreparedEvidenceIndexBytes(Buffer.from(JSON.stringify(changed)),expected),/index hash mismatch/);}finally{fs.rmSync(f.folder,{recursive:true,force:true});}});

test('record APIs reject pages whose ingestion revision changed during the read',async()=>{
 for(const name of ['attributesAt','namesAt','retirementsAt']){const db=new D1();try{
  const service=await import('../hosted/records.js'),original=db.prepare.bind(db);let changed=false;
  db.prepare=sql=>{const query=original(sql);if(sql.startsWith('SELECT r.*')||sql.startsWith('SELECT n.*')||sql.startsWith('SELECT t.*')){const all=query.all;query.all=async()=>{const result=await all.call(query);if(!changed){changed=true;db.sqlite.prepare("INSERT INTO atlas_ingestions(id,fingerprint,counts,created_at) VALUES('concurrent','aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa','{}',1)").run();}return result;};}return query;};
  await assert.rejects(service[name](db,2020),error=>error.status===409&&error.retryable===true);
 }finally{db.sqlite.close();}}
});

test('client retries complete map reads for mixed revisions, caps retries and obeys cancellation',async()=>{
 const file=`${root}/src/data-client.js`,sourceText=fs.readFileSync(file,'utf8').replace(/from '(\.\/[^']+)'/g,(_,p)=>`from '${new URL(p,new URL('file://'+file)).href}'`).replace("import.meta.env.VITE_STATIC_ATLAS === 'true'",'true').replace("import.meta.env.VITE_HOSTED_DATABASE === 'true'",'true')+'\nexport {loadHostedMapEvidence};';
 const loader=await import('data:text/javascript;base64,'+Buffer.from(sourceText).toString('base64')),prior=global.fetch;try{
  let calls=0;global.fetch=async(url,{signal}={})=>{signal?.throwIfAborted();const n=calls++;return Response.json({records:[{id:url.split('?')[0]}],next_cursor:null,revision:n<3?(n===1?2:1):3});};
  const good=await loader.loadHostedMapEvidence(2020,false);assert.equal(calls,6);assert.equal(good.attributes.revision,3);assert.equal(good.names.revision,3);assert.equal(good.retirements.revision,3);
  calls=0;global.fetch=async()=>{calls++;return Response.json({error:'Changed',retryable:true},{status:409});};const unstable=await loader.loadHostedMapEvidence(2020,false);assert.equal(calls,9);assert.equal(unstable.unstable,true);assert.equal(unstable.attributes.available,false);assert.deepEqual(unstable.names.records,[]);
  const abort=new AbortController();abort.abort();await assert.rejects(loader.loadHostedMapEvidence(2020,false,abort.signal),error=>error.name==='AbortError');assert.equal(calls,9);
  calls=0;global.fetch=async(url)=>{calls++;return Response.json({records:[],next_cursor:url.includes('cursor=')?null:'next',revision:url.includes('cursor=')?2:1});};const changedPages=await loader.loadHostedMapEvidence(2020,false);assert.equal(changedPages.unstable,true);assert.equal(calls,18);
 }finally{global.fetch=prior;}
});
