import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {createLocalPostgres} from '../scripts/verify-postgres-schema.mjs';
import {importBatch} from '../hosted/records.js';
import {hydrateHostedTemporalGeographyPage,hostedTemporalHistory,mergeHostedTemporalHistory} from '../src/hosted-temporal-geography.js';
import {stageGeographicRelease,finalizeGeographicRelease,geographicMembershipHash,geographicLocationIdsHash,geographicChangesHash} from '../hosted/geographic-releases.js';
import {importTemporalGeography,temporalGeographySnapshot,temporalGeographyPage,temporalWithdrawalsPage,temporalGeographyEvidence,temporalGeographySnapshotPage} from '../hosted/temporal-geography.js';
import {mapSnapshotPage} from '../hosted/map-snapshots.js';

class D1{constructor(){this.sqlite=new DatabaseSync(':memory:');this.sqlite.exec('PRAGMA foreign_keys=ON');for(const file of fs.readdirSync(new URL('../drizzle/',import.meta.url)).filter(x=>x.endsWith('.sql')).sort())this.sqlite.exec(fs.readFileSync(new URL(`../drizzle/${file}`,import.meta.url),'utf8'));}prepare(sql){const sqlite=this.sqlite;let values=[];return {bind(...args){values=args;return this;},async first(){return sqlite.prepare(sql).get(...values)??null;},async all(){return {results:sqlite.prepare(sql).all(...values)};},run(){return {meta:{changes:Number(sqlite.prepare(sql).run(...values).changes)}};}};}async batch(statements){this.sqlite.exec('BEGIN IMMEDIATE');try{const result=statements.map(row=>row.run());this.sqlite.exec('COMMIT');return result;}catch(error){this.sqlite.exec('ROLLBACK');throw error;}}}
const kinds=['continent','subcontinent','region','area','province','location'],pins={release_id:'reference-release',hierarchy_sha256:'a'.repeat(64),footprints_sha256:'b'.repeat(64)};
const source=(id,status)=>({id,name:`Isolated ${id}`,url:'https://example.org/temporal-test-only',license:'CC0',vintage:'2026',supported_from:status==='reference'?2026:-3000,supported_to:2027,status,metadata:{evidence:'synthetic testing only'}});
const membership=(id,parent='province-1',extra={})=>({id,entity_id:'location-0',parent_id:parent,valid_from:1000,valid_to:1100,source_id:'history',...extra});
const existence=(id,entity,value,extra={})=>({id,entity_id:entity,value,valid_from:1000,valid_to:1100,source_id:'history',...extra});
const payload=value=>({expected_geography:pins,...value});
async function fixture(backend,{lifetime=false,extraLocations=0}={}){
 const pg=backend==='postgres'?await createLocalPostgres():null,db=pg?.db??new D1();if(pg)await pg.engine.exec(fs.readFileSync(new URL('../postgres/migrations/0001_temporal_geography.sql',import.meta.url),'utf8'));
 try{await importBatch(db,JSON.parse(fs.readFileSync(new URL('../data/hosted-type-catalog.json',import.meta.url))));const entities=Array.from({length:6},(_,continent)=>kinds.map((kind,index)=>({id:`${kind}-${continent}`,kind,name:`Reference ${kind} ${continent}`,parent_id:index?`${kinds[index-1]}-${continent}`:null,...(lifetime&&kind==='location'&&continent===0?{valid_from:1000,valid_to:1100,source_id:'history'}:{})}))).flat();entities.push(...Array.from({length:extraLocations},(_,i)=>({id:`extra-location-${String(i).padStart(4,'0')}`,kind:'location',name:'Synthetic extra location',parent_id:'province-0'})));await importBatch(db,{sources:[source('history','historical'),source('reference','reference'),source('example','example')],entities:entities.slice(0,240)});for(let i=240;i<entities.length;i+=250)await importBatch(db,{entities:entities.slice(i,i+250)});const memberships=entities.map(row=>({entity_id:row.id,kind:row.kind,parent_id:row.parent_id,reference_name:row.name,active:1,source_id:'reference',evidence:{method:'isolated-reference'}}));await stageGeographicRelease(db,{release:{id:pins.release_id,source_id:'reference',version:1,reference_date:'2026-10-02',hierarchy_sha256:pins.hierarchy_sha256,footprints_sha256:pins.footprints_sha256,membership_sha256:await geographicMembershipHash(memberships),location_ids_sha256:await geographicLocationIdsHash(memberships),changes_sha256:await geographicChangesHash([]),expected_counts:Object.fromEntries(kinds.map(kind=>[kind,6+(kind==='location'?extraLocations:0)]))},memberships:memberships.slice(0,249)});for(let i=249;i<memberships.length;i+=250)await stageGeographicRelease(db,{release_id:pins.release_id,memberships:memberships.slice(i,i+250)});await finalizeGeographicRelease(db,pins.release_id);return {db,close:()=>pg?pg.close():db.sqlite.close()};}catch(error){await (pg?pg.close():Promise.resolve(db.sqlite.close()));throw error;}
}
async function both(callback,options){for(const backend of ['sqlite','postgres']){const f=await fixture(backend,options);try{await callback(f.db,backend);}finally{await f.close();}}}
const entity=(snapshot,id)=>snapshot.entities.find(row=>row.id===id);
const rejected=error=>error.status===400||error.status===409;

test('opt-in inline temporal pages retain exact standalone claims, permanent withdrawals, source and release pins',()=>both(async db=>{
 await importBatch(db,{records:[{id:'inline-population',location_id:'location-0',attribute:'population',value:42,valid_from:1000,valid_to:1100,source_id:'history'}]});
 await importTemporalGeography(db,payload({memberships:[membership('inline-membership'),membership('inline-withdrawn','province-1',{entity_id:'location-3'})],existence:[existence('inline-exclusion','location-2','not_exists')]}));
 await importTemporalGeography(db,payload({retirements:[{id:'inline-withdrawal',collection:'memberships',target_id:'inline-withdrawn',source_id:'history',reason:'Synthetic test withdrawal'}]}));
 const scalar=await mapSnapshotPage(db,1000,{evidenceOnly:true,limit:4096}),inline=await mapSnapshotPage(db,1000,{evidenceOnly:true,limit:4096,includeTemporal:true});
 const {temporal_geography,...sameScalar}=inline;assert.deepEqual(sameScalar,scalar);
 assert.deepEqual(temporal_geography.records,await temporalGeographySnapshotPage(db,1000));assert.deepEqual(temporal_geography.withdrawals,await temporalGeographySnapshotPage(db,1000,{stream:'withdrawals'}));
 assert.equal(temporal_geography.records.revision,inline.revision);assert.equal(temporal_geography.withdrawals.revision,inline.revision);
 assert.equal(temporal_geography.records.records.find(row=>row.id==='inline-exclusion').value,'not_exists');assert.equal(temporal_geography.withdrawals.withdrawals[0].target_id,'inline-withdrawn');
 assert.equal((await mapSnapshotPage(db,1000,{includeTemporal:true})).temporal_geography,undefined);
}));

test('a revision change between scalar and inline temporal reads rejects the complete response',()=>both(async db=>{
 const prepare=db.prepare.bind(db);let reads=0;
 db.prepare=sql=>{const statement=prepare(sql);if(/coalesce\(max\(rowid\),0\) revision/.test(sql)){const first=statement.first.bind(statement);statement.first=async()=>{const row=await first();reads++;return {...row,revision:row.revision+(reads>=3?1:0)};};}return statement;};
 await assert.rejects(mapSnapshotPage(db,1000,{evidenceOnly:true,includeTemporal:true}),error=>error.status===409&&error.retryable===true);
}));

test('incomplete bounded temporal streams stay on the ordinary paging protocol',()=>both(async db=>{
 const claims=Array.from({length:201},(_,i)=>existence(`paged-${i}`,`extra-location-${String(i).padStart(4,'0')}`,'unknown'));await importTemporalGeography(db,payload({existence:claims.slice(0,200)}));await importTemporalGeography(db,payload({existence:claims.slice(200)}));
 const first=await temporalGeographySnapshotPage(db,1000);assert.ok(first.next_cursor);assert.equal(first.records.length,200);
 const inline=await mapSnapshotPage(db,1000,{evidenceOnly:true,includeTemporal:true});assert.equal(inline.temporal_geography,undefined);
 const second=await temporalGeographySnapshotPage(db,1000,{cursor:first.next_cursor});assert.equal(second.records.length,1);assert.equal(second.next_cursor,null);assert.equal(second.revision,inline.revision);
},{extraLocations:201}));

test('inline geography never widens the total scalar response byte limit',()=>both(async db=>{
 await importBatch(db,{records:[{id:'large-source-scalar',location_id:'location-0',attribute:'population',value:42,valid_from:1000,valid_to:1100,source_id:'history'}]});
 const names=Array.from({length:1000},(_,i)=>({id:`byte-name-${i}`,entity_id:`extra-location-${String(i).padStart(4,'0')}`,name:'Synthetic historical name',language:'en',valid_from:1000,valid_to:1100,source_id:'history',metadata:{retained:'x'.repeat(900)}}));for(let i=0;i<names.length;i+=100)await importBatch(db,{names:names.slice(i,i+100)});
 await db.batch([db.prepare('INSERT INTO atlas_sources(id,name,url,license,vintage,supported_from,supported_to,status,metadata) VALUES(?,?,?,?,?,-3000,2027,?,?)').bind('inline-legacy-source','Synthetic legacy source','https://example.org/inline-byte-test','CC0','2026','historical',JSON.stringify({retained:'x'.repeat(7*1024*1024)}))]);
 await importTemporalGeography(db,payload({existence:[existence('large-source-geo','location-0','unknown',{source_id:'inline-legacy-source'})]}));
 const result=await mapSnapshotPage(db,1000,{evidenceOnly:true,limit:4096,includeTemporal:true});assert.equal(result.records.length,1);assert.equal(result.names.length,1000);assert.equal(result.temporal_geography,undefined);assert.ok(Buffer.byteLength(JSON.stringify(result))<=8*1024*1024);
 assert.equal((await temporalGeographySnapshotPage(db,1000)).records.length,1);
},{extraLocations:1000}));

test('complete reference chains remain labeled fallback; BC/AD, exclusive end and province-level changes resolve identically',()=>both(async db=>{
 const initial=await temporalGeographySnapshot(db,-3000);assert.equal(initial.entities.filter(row=>row.present).length,36);assert.equal(entity(initial,'location-0').parent_context,'reference');assert.equal(initial.capability.datedFootprints,0);
 await importTemporalGeography(db,payload({memberships:[membership('bc-parent','province-1',{valid_from:-1,valid_to:1}),membership('area-parent','area-1',{entity_id:'province-0'})]}));assert.equal(entity(await temporalGeographySnapshot(db,-1),'location-0').parent_id,'province-1');assert.equal(entity(await temporalGeographySnapshot(db,1),'location-0').parent_id,'province-0');assert.equal(entity(await temporalGeographySnapshot(db,1000),'province-0').parent_id,'area-1');assert.equal(entity(await temporalGeographySnapshot(db,1100),'province-0').parent_id,'area-0');await assert.rejects(temporalGeographySnapshot(db,0),/year/);await assert.rejects(temporalGeographySnapshot(db,2027),/year/);
}));
test('SQL source, tier, equal-precedence overlap, release and example guards reject atomic invalid imports',()=>both(async db=>{
 for(const row of [membership('zero','province-1',{valid_from:0}),membership('skip','area-1'),membership('reference-ancient','province-1',{source_id:'reference',method:'reference'}),membership('example-leak','province-1',{source_id:'example'}),membership('missing','missing'),membership('continent-parent','province-1',{entity_id:'continent-0'})])await assert.rejects(importTemporalGeography(db,payload({memberships:[row]})),rejected);
 await assert.rejects(importTemporalGeography(db,{...payload({memberships:[membership('wrong-pins')]}),expected_geography:{...pins,footprints_sha256:'f'.repeat(64)}}),rejected);await importTemporalGeography(db,payload({memberships:[membership('original')]}));await assert.rejects(importTemporalGeography(db,payload({memberships:[membership('overlap','province-2')]})),rejected);assert.equal((await temporalGeographySnapshot(db,1000)).claims.length,1);
}));
test('ancestor absence rejects disconnected descendants but permits atomic reparenting or existence suppression',()=>both(async db=>{
 await assert.rejects(importTemporalGeography(db,payload({existence:[existence('absent-area','area-0','not_exists')]})),rejected);assert.equal((await temporalGeographySnapshot(db,1000)).claims.length,0);
 await importTemporalGeography(db,payload({existence:[existence('absent-area','area-0','not_exists')],memberships:[membership('move-descendant','area-1',{entity_id:'province-0'})]}));const moved=await temporalGeographySnapshot(db,1000);assert.equal(entity(moved,'area-0').present,false);assert.equal(entity(moved,'province-0').parent_id,'area-1');assert.equal(entity(moved,'location-0').present,true);assert.equal(entity(await temporalGeographySnapshot(db,1100),'province-0').parent_id,'area-0');
 await importTemporalGeography(db,payload({existence:[existence('absent-province','province-2','not_exists'),existence('absent-location','location-2','not_exists')]}));assert.ok((await temporalGeographySnapshot(db,1000)).excluded_entity_ids.includes('location-2'));
}));
test('all overlapping ancestor transitions are validated, including interior absence outside child endpoints',()=>both(async db=>{
 await importTemporalGeography(db,payload({existence:[existence('parent-interior-off','province-1','not_exists',{valid_from:1005,valid_to:1006}),existence('child-interior-off','location-1','not_exists',{valid_from:1005,valid_to:1006})]}));await assert.rejects(importTemporalGeography(db,payload({memberships:[membership('parent-at-interior')]})),rejected);assert.equal(entity(await temporalGeographySnapshot(db,1005),'location-0').parent_id,'province-0');
}));
test('explicit unknown blocks weaker and opt-in examples while maintaining the complete reference chain',()=>both(async db=>{
 await importTemporalGeography(db,payload({memberships:[membership('derived','province-1',{method:'derived'}),membership('unknown-parent',null),membership('example-parent','province-2',{is_example:1,source_id:'example'})]}));for(const examples of [false,true]){const snapshot=await temporalGeographySnapshot(db,1000,{examples}),location=entity(snapshot,'location-0');assert.equal(location.parent_id,'province-0');assert.equal(location.reference_parent_id,'province-0');assert.equal(location.historical_parent_id,null);assert.equal(location.membership_status,'unknown');assert.equal(location.parent_context,'reference');assert.equal(location.membership_record.id,'unknown-parent');}
}));
test('atomic corrections preserve original JSON text, withdrawals, stable retries and missing-replacement rollback',()=>both(async db=>{
 await importTemporalGeography(db,payload({memberships:[membership('old-parent','province-1',{metadata:' { "original" : "retained bytes", "order" : 2 } '})]}));const correction=payload({ingestion_id:'geographic-correction',retirements:[{id:'withdraw-parent',collection:'memberships',target_id:'old-parent',replacement_id:'new-parent',source_id:'history',reason:'Isolated sourced correction'}],memberships:[membership('new-parent','province-2')]});const first=await importTemporalGeography(db,correction),second=await importTemporalGeography(db,correction);assert.equal(second.duplicate,true);assert.deepEqual(second.counts,first.counts);assert.equal(entity(await temporalGeographySnapshot(db,1000),'location-0').parent_id,'province-2');assert.equal((await temporalGeographyEvidence(db,'memberships','old-parent')).status,'superseded');assert.equal((await db.prepare('SELECT metadata FROM atlas_geographic_membership_records WHERE id=?').bind('old-parent').first()).metadata,' { "original" : "retained bytes", "order" : 2 } ');assert.equal((await temporalWithdrawalsPage(db)).records[0].target_id,'old-parent');
 await assert.rejects(importTemporalGeography(db,payload({retirements:[{id:'incomplete-withdrawal',collection:'memberships',target_id:'new-parent',replacement_id:'missing-replacement',source_id:'history',reason:'Incomplete correction'}]})),rejected);assert.equal(entity(await temporalGeographySnapshot(db,1000),'location-0').parent_id,'province-2');await assert.rejects(importTemporalGeography(db,{...correction,memberships:[membership('new-parent','province-3')]}),rejected);
}));
test('SQL independently prevents forged validation, dangling receipts and appending to a sealed receipt',()=>both(async db=>{
 const insert=(id,subject,value,validation)=>db.prepare('INSERT INTO atlas_geographic_existence_records(id,entity_id,value,valid_from,valid_to,source_id,method,status,is_example,release_id,validation_id,metadata) VALUES(?,?,?,1000,1100,?,\'direct\',\'sourced\',0,?,?,\'{}\')').bind(id,subject,value,'history',pins.release_id,validation);
 await assert.rejects(db.batch([insert('dangling','location-0','not_exists','missing-receipt')]));
 const fake='forged-validation',fingerprint='c'.repeat(64);await assert.rejects(db.batch([insert('forged-parent','province-0','not_exists',fake),db.prepare('INSERT INTO atlas_temporal_geography_validations(id,ingestion_id,release_id,hierarchy_sha256,footprints_sha256,fingerprint,created_at) VALUES(?,?,?,?,?,?,1)').bind(fake,fake,pins.release_id,pins.hierarchy_sha256,pins.footprints_sha256,fingerprint),db.prepare('INSERT INTO atlas_ingestions(id,fingerprint,counts,created_at) VALUES(?,?,?,1)').bind(fake,fingerprint,JSON.stringify({_temporal_geography_validation_id:fake}))]));assert.equal((await temporalGeographySnapshot(db,1000)).claims.length,0);
 await importTemporalGeography(db,payload({ingestion_id:'sealed',existence:[existence('sealed-claim','location-0','unknown')]}));await assert.rejects(db.batch([insert('append-to-sealed','location-0','not_exists','sealed')]));assert.equal(entity(await temporalGeographySnapshot(db,1000),'location-0').present,true);
}));
test('known identity lifetimes cannot be resurrected or widened by a dated claim',()=>both(async db=>{
 assert.equal(entity(await temporalGeographySnapshot(db,999),'location-0').present,false);assert.equal(entity(await temporalGeographySnapshot(db,1100),'location-0').present,false);await assert.rejects(importTemporalGeography(db,payload({existence:[existence('resurrection','location-0','exists',{valid_from:900,valid_to:1001})]})),rejected);await importTemporalGeography(db,payload({existence:[existence('supported-life','location-0','exists')]}));assert.equal(entity(await temporalGeographySnapshot(db,1000),'location-0').present,true);
},{lifetime:true}));
test('paged claims retain exclusions, provenance, release and one shared revision',()=>both(async db=>{
 await importTemporalGeography(db,payload({memberships:[membership('paged-membership')],existence:[existence('paged-exclusion','location-2','not_exists')]}));const first=await temporalGeographyPage(db,1000,{limit:1});assert.equal(first.records[0].collection,'existence');assert.ok(first.next_cursor);const second=await temporalGeographyPage(db,1000,{limit:1,cursor:first.next_cursor});assert.equal(second.records[0].collection,'memberships');assert.equal(second.revision,first.revision);assert.equal(second.records[0].source_from,-3000);assert.deepEqual(second.records[0].source_metadata,{evidence:'synthetic testing only'});assert.equal(first.records[0].value,'not_exists');assert.equal(second.next_cursor,null);
}));

test('bounded production pages skip the reference registry in source-free years and return only winners with deduplicated sources',()=>both(async db=>{
 const queries=[],prepare=db.prepare.bind(db);db.prepare=sql=>{queries.push(sql);return prepare(sql);};
 const empty=await temporalGeographySnapshotPage(db,1000);assert.deepEqual(empty.records,[]);assert.deepEqual(empty.sources,[]);assert.equal(empty.next_cursor,null);assert.ok(!queries.some(sql=>/FROM atlas_geographic_memberships\b/.test(sql)));
 await importTemporalGeography(db,payload({memberships:[membership('weaker','province-1',{method:'derived'}),membership('winner-unknown',null),membership('two-fields','province-1',{entity_id:'location-2'})],existence:[existence('bounded-exclusion','location-1','not_exists'),existence('two-fields-life','location-2','unknown')]}));
 const pages=[];let cursor='';do{const page=await temporalGeographySnapshotPage(db,1000,{limit:1,cursor});pages.push(page);cursor=page.next_cursor;}while(cursor);
 assert.equal(pages.length,3);assert.equal(pages[0].records[0].id,'winner-unknown');assert.equal(pages[0].records[0].effective_parent_id,'province-0');assert.equal(pages[0].records[0].parent_context,'reference');assert.equal(pages[0].records[0].membership_status,'unknown');assert.equal(pages[1].records[0].value,'not_exists');assert.equal(pages[2].records.length,2);
 for(const page of pages){assert.equal(page.revision,pages[0].revision);assert.equal(page.release_id,pins.release_id);assert.equal(page.hierarchy_sha256,pins.hierarchy_sha256);assert.equal(page.footprints_sha256,pins.footprints_sha256);assert.equal(page.sources.length,1);assert.equal(page.sources[0].id,'history');assert.equal(page.sources[0].supported_from,-3000);assert.ok(page.records.every(row=>!Object.hasOwn(row,'__winner')));assert.ok(page.records.every(row=>row.validation_id&&row.entity_kind==='location'));}
 assert.equal((await temporalGeographySnapshotPage(db,2026)).records.length,0);
}));

test('permanent withdrawal pages retain claims outside the selected year and share the pinned revision',()=>both(async db=>{
 await importTemporalGeography(db,payload({memberships:[membership('withdraw-outside-year','province-1',{entity_id:'location-3'}),membership('withdraw-outside-year-2','province-1',{entity_id:'location-4'})]}));await importTemporalGeography(db,payload({retirements:[{id:'withdraw-a',collection:'memberships',target_id:'withdraw-outside-year',source_id:'history',reason:'Sourced permanent withdrawal'},{id:'withdraw-b',collection:'memberships',target_id:'withdraw-outside-year-2',source_id:'history',reason:'Sourced permanent withdrawal'}]}));
 const first=await temporalGeographySnapshotPage(db,-3000,{stream:'withdrawals',limit:1}),second=await temporalGeographySnapshotPage(db,-3000,{stream:'withdrawals',limit:1,cursor:first.next_cursor});assert.equal(first.withdrawals[0].target_id,'withdraw-outside-year');assert.equal(second.withdrawals[0].target_id,'withdraw-outside-year-2');assert.equal(first.sources.length,1);assert.equal(second.revision,first.revision);assert.equal(second.next_cursor,null);assert.equal((await temporalGeographySnapshotPage(db,1000)).records.length,0);
 await assert.rejects(temporalGeographySnapshotPage(db,1000,{stream:'arbitrary'}),rejected);
}));

test('legacy source metadata is byte-preflighted before materialization and oversized pages fail with a bounded retry suggestion',()=>both(async db=>{
 const legacyMetadata=JSON.stringify({legacy:'x'.repeat(8*1024*1024)});await db.batch([db.prepare('INSERT INTO atlas_sources(id,name,url,license,vintage,supported_from,supported_to,status,metadata) VALUES(?,?,?,?,?,-3000,2027,?,?)').bind('large-legacy-source','Large isolated legacy metadata','https://example.org/isolated-large-source','CC0','2026','historical',legacyMetadata)]);
 await importTemporalGeography(db,payload({memberships:[membership('large-source-claim','province-1',{source_id:'large-legacy-source'})]}));const queries=[],prepare=db.prepare.bind(db);db.prepare=sql=>{queries.push(sql);return prepare(sql);};await assert.rejects(temporalGeographySnapshotPage(db,1000,{limit:200}),error=>error.status===413&&error.suggested_limit===100);assert.ok(queries.some(sql=>/sum\(/.test(sql)&&/FROM atlas_sources/.test(sql)));assert.ok(!queries.some(sql=>/^SELECT \* FROM atlas_sources/.test(sql)));assert.equal((await mapSnapshotPage(db,1000,{evidenceOnly:true,includeTemporal:true})).temporal_geography,undefined);
}));

test('raw SQL cannot store fractional years or alter retained temporal facts and receipts',()=>both(async(db,backend)=>{
 await importTemporalGeography(db,payload({ingestion_id:'retention-receipt',memberships:[membership('retained-fact')]}));
 await assert.rejects(db.batch([db.prepare('INSERT INTO atlas_geographic_existence_records(id,entity_id,value,valid_from,valid_to,source_id,method,status,is_example,release_id,validation_id,metadata) VALUES(?,?,?,1000.5,1100,?,\'direct\',\'sourced\',0,?,?,\'{}\')').bind('fractional-date','location-0','unknown','history',pins.release_id,'unsealed-fraction-receipt')]));
 for(const [table,column] of [['atlas_geographic_membership_records','metadata'],['atlas_temporal_geography_validations','fingerprint']]){await assert.rejects(db.batch([db.prepare(`UPDATE ${table} SET ${column}=?`).bind(column==='metadata'?'{}':'d'.repeat(64))]));await assert.rejects(db.batch([db.prepare(`DELETE FROM ${table}`).bind()]));if(backend==='postgres')await assert.rejects(db.batch([db.prepare(`TRUNCATE ${table} CASCADE`).bind()]));}
 assert.equal((await temporalGeographyEvidence(db,'memberships','retained-fact')).claim.id,'retained-fact');assert.equal((await db.prepare('SELECT fingerprint FROM atlas_temporal_geography_validations WHERE id=?').bind('retention-receipt').first()).fingerprint.length,64);
}));

test('actual hosted winner and withdrawal streams hydrate the browser resolver without full registry reads',()=>both(async db=>{
 await importTemporalGeography(db,payload({memberships:[membership('bridge-unknown',null),membership('bridge-retired','province-1',{entity_id:'location-3'})],existence:[existence('bridge-absent','location-1','not_exists')]}));await importTemporalGeography(db,payload({retirements:[{id:'bridge-withdrawal',collection:'memberships',target_id:'bridge-retired',source_id:'history',reason:'Sourced browser-integration withdrawal'}]}));
 const records=await temporalGeographySnapshotPage(db,1000),withdrawals=await temporalGeographySnapshotPage(db,1000,{stream:'withdrawals'});assert.equal(records.next_cursor,null);assert.equal(withdrawals.next_cursor,null);assert.equal(records.revision,withdrawals.revision);const options={year:1000,expectedGeography:pins},hydrated=hydrateHostedTemporalGeographyPage(records,options);assert.equal(hydrated.entities.length,2);assert.equal(hydrated.entities.find(row=>row.id==='location-0').historical_parent_id,null);assert.deepEqual(hydrated.excluded_entity_ids,['location-1']);
 const history=hostedTemporalHistory(records,options),parent=history.find(row=>row.field==='parent');assert.equal(parent.value,'province-0');assert.equal(parent.metadata.historical_membership_status,'unknown');assert.equal(parent.metadata.parent_context,'reference');assert.equal(parent.source_from,-3000);assert.equal(history.find(row=>row.field==='existence').value,'not_exists');
 const sources=[...new Map([...records.sources,...withdrawals.sources].map(source=>[source.id,source])).values()],complete={...records,withdrawals:withdrawals.withdrawals,sources},legacy=[{id:'weaker-static-parent',entity_id:'location-0',field:'parent',value:'province-1',valid_from:1000,valid_to:1100},{id:'bridge-retired',entity_id:'location-3',field:'parent',value:'province-1',valid_from:1000,valid_to:1100},{id:'independent-population',entity_id:'location-0',field:'population',value:42,valid_from:1000,valid_to:1100}];
 const merged=mergeHostedTemporalHistory(legacy,complete,{...options,complete:true});assert.ok(!merged.some(row=>['weaker-static-parent','bridge-retired'].includes(row.id)));assert.ok(merged.some(row=>row.id==='independent-population'));assert.ok(merged.some(row=>row.id==='bridge-unknown'));assert.throws(()=>mergeHostedTemporalHistory(legacy,complete,options),/complete/);assert.throws(()=>hydrateHostedTemporalGeographyPage({...records,hierarchy_sha256:'f'.repeat(64)},options),/mismatch/);
}));
