# Source research and geographic policy

EU5 counts are a rough scale reference, not quotas. No EU5 data is imported. Antarctica is excluded. Prepared counts and every active location are recorded in [the current audit](../data/granularity-audit.json).

## Administrative locations and granularity

See [the complete granularity policy](GRANULARITY.md) for country-specific source roles, coherent city territories, physical rural subdivisions, independent naming crosswalks, licenses and documented exceptions. The previous average-area selection rule is removed. Source ADM numbers are not globally equivalent. Counts follow reviewed source geography rather than quotas.

Roma is a metropolitan-district location under Lazio, not Lazio masquerading as a location; its footprint is not a claim about the city's built-up area. Hong Kong and Singapore each form one compact territory. Dated ranks, settlement history and names remain independent of these modern reference footprints.

## Country-independent geographic hierarchy

Upper groups use **R. K. Brummitt (2001), World Geographical Scheme for Recording Plant Distributions (WGSRPD), second edition**, published by TDWG / Royal Botanic Gardens, Kew. [Official GIS repository](https://github.com/tdwg/wgsrpd), pinned revision `52da7828aba9d461dd133c27b3bd7a4407161f54`. We derive region labels from level 2 and geographic areas from level 3. The source term “botanical countries” for level 3 does **not** define political ownership.

This is a published geographic distribution scheme, not a reconstruction of historical administrations. It is independent of the app's Owner field: the US and Russia span several regions, while Macau and Hong Kong share the China / China Southeast geographic groups with neighbouring locations. Geographic boundaries can coincide with administrative borders; they do not automatically change when ownership changes. Political mode colors and borders resolve ownership on complete location footprints; geographic group membership remains independent of the selected owner.

Six continents and atlas subcontinent macro-groups adapt WGSRPD's botanical continents. Central America and the Caribbean belong to North America, and Papuasia to Oceania. WGSRPD's subantarctic island grouping is split into continent-compatible Atlantic/Indian Ocean groups; excluding Antarctica does not discard the Falklands or Tristan da Cunha. These adaptations are explicit atlas groupings, not extra source-authored levels.

Each location is assigned by largest polygon overlap with a WGSRPD geographic area. The location is not geometrically cut by this classification. A named administrative province crossing multiple geographic areas is represented by explicitly tagged geographic portions, not new administrative units. Where the coarse historical GIS coastline misses a modern island, nearest-source geometry supplies a reference classification; the method and distance are recorded for review. The report lists assignments below 95% overlap and nearest-source assignments. These are complete provisional classifications, not claims of perfectly aligned source boundaries. `data/hierarchy-report.json` records the complete crosswalk and zero missing chains.

WGSRPD GIS attribution: RBG Kew, Justin Moat. The supplied GIS metadata specifies no use constraints and credits underlying administrative boundaries © 1992–1997 ESRI / GMi, used with permission. We publish derived location classifications, not the original GIS boundary files. Per-country gbOpen licenses remain in `data/administrative-sources.json`; Natural Earth is public domain. Pinning and SHA-256 hashes are recorded in source reports. Modern political labels remain those of the administrative source.

## Non-overlapping geography and pixel ownership

The source set mixes independently compiled boundaries and vintages. Duplicate collections (including Xianggang plus Hong Kong districts, country layers plus overseas territories, and Kosovo aliases) are retired globally. Shared interiors are partitioned using Natural Earth reference borders where supported, then the finer source polygon and stable ID. This is a cartographic display convention, not a sovereignty ruling. Shared pair coverage is preserved within a recorded numerical tolerance. A second global intersection pass repairs residual overlaps and checks the final serialized collection.

The final publication gate checks **every intersecting pair above 1e-10 square degrees** (approximately one square metre at the equator). Untouched input is cached; adjustments retain provenance. Existing SQLite locations are archived, not deleted; their imported history is preserved. Replacing a coarse unit with finer units does not transfer its historical population or names to the new units without evidence.

Rendering uses a fixed Web Mercator grid with **32,768 cells across the world**, about **1.22 km per cell at the equator**, smaller at higher latitude. This is four times coarser along each axis than the previous grid. A background worker compiles canonical cell centres into a world-wide integer location-ID grid once per geometry change, compressed as runs of equal IDs per row; zero means water or uncovered source coverage. Every covered cell has exactly one location ID and inherits one parent chain. Colors, hover and clicks use the same buffer. The WebGL2 renderer keeps these compressed ownership tables and color palettes on the GPU. Zoom, pan, and resize update view uniforms without rebuilding cell buffers, border paths, or textures. Cells shrink naturally below screen-pixel size at distant zoom; their geographic dimensions never change and no four-screen-pixel minimum is imposed. The existing canvas scales during zoom animation. CPU hit-testing reads the same canonical ownership tables, independent of zoom. Border thickness is specified in screen pixels separately from cell resolution. A cached Canvas fallback supports devices without WebGL2. Only changed location geometry requires a new cached geographic grid; changing the year or owner values updates the location color palette. Source political geometry is processed during data preparation and never recompiles the grid during navigation.

Thin location borders disappear below zoom 7. Province borders remain stronger. Political mode additionally outlines ownership/polity changes; geographic modes outline their selected geographic groups. Very small features can disappear at this resolution but remain searchable source polygons. Coarse pixels do not guarantee every island has a visible cell or fill gaps in source coverage.

## Temporal identity and evidence

Stable entity IDs are independent of names, attributes and ownership. Dated names, aliases, membership, existence and attributes apply at every hierarchy level. Settlements are separate entities associated with a map location; municipal incorporation is not automatically settlement founding. Renames retain an ID. Reconstitutions, splits and mergers use new IDs and explicit predecessor/successor links; dated lifetimes and boundary records specify the actual map transition.

Missing names show **Historical name unknown**, with a separate present-day reference label. Undated ancestor names are explicitly reference context. Search indexes modern names and imported historical aliases, respecting the examples toggle. Rank, population and habitation are never inferred from a modern city name. “Unknown” is distinct from explicitly uninhabited or a sourced population of zero. Dated parent changes update the complete chain, geographic colors and province borders. Dated local boundaries reassign the fixed grid; higher boundaries follow their members.

The importer enforces adjacent parent levels, non-overlapping preferred records per language/example class, sourced intervals and parent existence at temporal events. Geographic boundary imports require separate GIS topology review; structural GeoJSON validation is not a geometric overlap audit. Existing source geography is still modern reference unless a dated override supplies evidence. The bundled temporal-name and settlement demonstration is **opt-in and illustrative**; it is not newly researched ancient Shenzhen history.

## Selected historical political layer

**Bennett et al. (2025), [Cliopatria: a dataset of world-wide polities from 3400 BCE to 2024 CE](https://doi.org/10.1038/s41597-025-04516-9)**, from the [Seshat Global History Databank](https://github.com/Seshat-Global-History-Databank/cliopatria), is the best fit among sources reviewed for broad temporal coverage and explicit dated territory records. Used release: `v0.2.0-duplicate`; license: [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/). The supplied map is adapted through filtering, simplification, validity repair, and interval normalization.

The app includes 13,378 POLITY records intersecting 3000 BC–2024 AD. RELATION composites are omitted to avoid duplicating their members. Source dates are inclusive; app dates have exclusive ends. Source year-zero endpoints are normalized without changing membership for valid nonzero calendar years. Original endpoint fields remain available.

These are reconstructed, often coarse territories, not cadastral boundaries or complete annual observations. Resolution and certainty vary by place and period. Preparation clips source polygons to each location, unions polygons of the same stable polity, and measures WGS84 land-area overlap. A derived owner requires more than half of the entire applicable location land footprint; competing overlapping claims, ties and insufficient coverage remain unresolved. Source IDs, winning share, competing coverage and supported intervals are retained separately from the resolved scalar. Direct dated location evidence takes precedence. Normal Political mode fills every location once from these records; original source geometries remain optional evidence. Gaps mean missing ownership evidence, not uninhabited or unclaimed land. The source has no 2025–2026 political reconstruction; 2026 uses the clearly labeled modern reference only where its polity is resolved. It supplies none of the requested local demographic, cultural, religious, terrain, or rank attributes.

The compact ownership preparation contains 6,834,664 supported dated intervals: 5,664,901 majority-derived assignments, 222,473 intervals without a majority, and 947,290 disputed intervals. The latter two resolve explicitly to unknown ownership. These are source/geometry-change intervals, not 6.8 million independent historical observations. The merged environmental preparation contains 346,293 records across 49,596 locations with at least one reference record, including 16 explicit unknown source-biome entries; per-attribute coverage remains distinct.

## Other sources evaluated

| Source | Strength | Decision / limit |
|---|---|---|
| [CShapes 2.0](https://icr.ethz.ch/data/cshapes/) | Documented modern political boundaries, global 1886–2019 and Europe back to 1816 | Valuable later supplement; short time range and CC BY-NC-SA 4.0 terms compared with selected source |
| [Historical Basemaps](https://github.com/aourednik/historical-basemaps) | Broad historical world snapshots | Snapshot granularity, GPL-3.0, author advises verification; not primary dated layer |
| [CHGIS](https://chgis.fas.harvard.edu/) | Historical Chinese places and administrative geography | Academic-use and redistribution restrictions require checking the actual release; no files imported |
| [HydroBASINS](https://www.hydrosheds.org/products/hydrobasins) | Twelve nested watershed levels with physical meaning | Useful physical hierarchy, but not a replacement for named historical/admin locations |
| [HYDE 3.2](https://essd.copernicus.org/articles/9/927/2017/) | Long-run gridded population and land-use estimates | Candidate for explicitly estimated population; not imported or converted into local observed counts |

No reviewed source supplies the entire requested hierarchy and all attributes for every year. Real historical local boundaries, historically meaningful upper groupings, population estimates with uncertainty, and dated culture/religion evidence remain substantial research work. Unknown fields stay unknown; opt-in examples are labeled illustrative.


## Prepared environmental references and settlement estimates

Beck et al. (2023) [Köppen–Geiger climate maps](https://doi.org/10.1038/s41597-023-02549-6), CC BY 4.0, supply four 1 km climatology periods: 1901–1930, 1931–1960, 1961–1990 and 1991–2020. Latitude-weighted native cells summarize each location's land footprint; a summary requires supported coverage rather than nearest-point sampling. Each period covers 49,483 current locations. The latest normal can also appear at 2026 as explicitly marked reference context; it is not an observation of 2026 weather.

[RESOLVE Ecoregions 2017](https://www.arcgis.com/home/item.html?id=37ea320eebb647c6838c23f72abae5ef), CC BY 4.0, supplies 49,280 known dominant potential-natural biome references, plus 16 explicit unknown source classes by WGS84 area. The numerical re-preparation scanned all 49,614 locations with precise WGS84 ellipsoid integration, unioned source polygons within each biome, and measured coverage against the entire land footprint. It preserved all categories and support results, including 318 unsupported locations. Its [per-location receipt](../data/vegetation-numerical-review/index.json) records source-class overlaps in 5,793 locations; competing source shares are evidence, not exclusive population proportions. The winning share uses the unique covered-land union as denominator. This reference does not establish observed farmland, urban land cover or historical vegetation. The two environmental preparations contain 296,711 climate/biome records across 49,525 locations with at least one value. Unsupported locations and dates remain unknown.

Natural Earth's public-domain populated-place table embeds attributed UN urban-agglomeration estimates and projections. The preparation preserves 582 distinct settlements and 9,301 supported five-year population estimates from 1950–2025. Source values in thousands become persons while retaining their stated precision and estimate/projection status. Each value applies only at its published source year. These are settlement populations; they do not become the surrounding location's population or establish rank, ancient name, founding or continuous habitation. Eight candidate settlement series lack a unique supported host footprint and remain unassigned.

EarthEnv / Amatulli et al. (2018) [topographic variables](https://doi.org/10.1038/sdata.2018.40), CC BY 4.0, adds 49,582 modern location summaries from the published 1 km majority-geomorphon grid. The source metadata records compilation in 2016 from GMTED2010 median elevation, with a 56°S–84°N extent. Native landform codes are verified against the paper and GRASS documentation: flat, peak, ridge, shoulder, spur, slope, hollow, footslope, valley and pit. We use those published categories directly rather than invent hills/mountains thresholds. Latitude-weighted native-cell dominance requires at least 50% supported sampled land coverage; 32 sub-cell footprints remain unknown. The 2026 display interval denotes a relatively stable physical reference, not a 2026 observation or ancient measurement. Source URL, SHA-256, class counts, supported coverage and every missing location are recorded in `data/topography-reference/index.json`.

## Historical expansion and worldwide evidence limits

The [machine-readable source inventory](../data/source-inventory.json) records source status, inspected documentation, licenses, supported dates, import paths and blockers. The [historical coverage research](HISTORICAL_COVERAGE_RESEARCH.md) distinguishes immediately usable source formats from evidence that cannot resolve atlas attributes. In particular, Pleiades is CC BY 3.0 and has dated Name resources; World Historical Gazetteer's aggregation license does not override each contributor's terms; GeoNames historical alias dates are optional. Ethnic polygons and language points do not establish primary culture, and country religion percentages do not establish each location's religion.

Source assessment is separate from semantic approval. The global top-down audit must cover continent → subcontinent → region → area → province → location, recording the decision and open evidence at every branch. A complete parent chain or a botanical scheme citation does not certify a continent boundary or every descendant grouping. Source inventory candidates cover all six continents, but they do not mark hundreds of geographic groups as reviewed or close unsupported historical years.
