import assert from 'node:assert/strict';
import {caseIndex,inspect} from './compile.mjs';
import {GRID_WIDTH} from '../../../src/pixel-grid.js';
const lonlat=(x,y)=>[(x/GRID_WIDTH)*360-180,Math.atan(Math.sinh(Math.PI*(1-2*y/GRID_WIDTH)))*180/Math.PI];
const feature=(id,a,b,c,d)=>({type:'Feature',id,properties:{id,parent_id:'fixed'},geometry:{type:'Polygon',coordinates:[[lonlat(a,b),lonlat(c,b),lonlat(c,d),lonlat(a,d),lonlat(a,b)]]}});
const original=[feature('IRN',100,100,101,101),feature('PAK',103,100,104,101)];
const candidate=[feature('IRN',100,100,102,101),feature('PAK',102,100,104,101)];
const indices={IRN:17500,PAK:30123};
const staged={size:GRID_WIDTH,bbox:{x:99,y:99,width:6,height:4,stride:1},subject_ids:['IRN','PAK'],baseline:original,candidate,owner_indices:indices,
              component:feature('component',101,100,103,101),stored_bounds:Object.fromEntries(caseIndex(original,indices).map(v=>[v.feature.id,v.bounds]))};
const checks=[];
const result=inspect(staged);
assert.equal(result.baseline.counts.component_uncovered,2);
assert.equal(result.candidate.counts.component_uncovered,0);
assert.equal(result.candidate.counts.component_single,2);
assert.equal(result.change_counts.outside_component_mask,0);
assert.equal(result.change_counts.lost_previously_owned_cells,0);
checks.push('known source masks fill exactly two missing component cells preserving outside and original coverage');
for(const category of ['baseline','candidate'])for(const metric of ['raster_compiler_mismatch','packed_sample_mismatch','packed_pick_mismatch'])assert.equal(result[category].counts[metric],0);
assert.deepEqual(result.owner_indices,indices);
checks.push('raster compiler and shuffled packed sample/picking agree with full-width high owner indices');
assert.equal(result.installation_ready,false);assert.equal(result.geographic_approval,'unapproved');
checks.push('positive rendering evidence never grants installation or geographic authority');
assert.throws(()=>inspect({...staged,size:GRID_WIDTH-1}),/width differs/);
checks.push('rounded wrong grid size rejected');
assert.throws(()=>inspect({...staged,owner_indices:{IRN:17500}}),/inventory/);
checks.push('missing exact neighbor owner index rejected');
assert.throws(()=>inspect({...staged,candidate:[candidate[0]]}),/inventory/);
checks.push('missing unchanged or changed neighbor rejected');
assert.throws(()=>inspect({...staged,stored_bounds:{...staged.stored_bounds,IRN:[0,0,1,1]}}),/Stored bounds differ/);
checks.push('stale stored geometry bounds rejected');
assert.throws(()=>inspect({...staged,bbox:{x:0,y:0,width:4001,height:4001}}),/Unbounded/);
checks.push('oversized domain rejected rather than dense world allocation');
const overlapped=inspect({...staged,candidate:[feature('IRN',100,100,102.6,101),candidate[1]]});
assert.equal(overlapped.candidate.counts.component_multiple,1);
assert.equal(overlapped.change_counts.new_multiple_cells,1);
checks.push('new source overlap detected independently of deterministic owner tie rule');
const negative=checks.filter(v=>v.includes('rejected')||v.includes('overlap detected'));
console.log(JSON.stringify({method_id:'bounded-application-compilation',kind:'positive-control',outcome:'passed',check_count:checks.length,checks,negative_checks:negative}));
