-- Fixed environmental classification guards: generated from src/environment-classifications.js.
-- Retained legacy claims are not rewritten. Identical-ID retries continue through
-- the existing byte-exact collision guard; genuinely new values use this registry.
CREATE TRIGGER atlas_environment_classification BEFORE INSERT ON atlas_attribute_records
WHEN NOT EXISTS(SELECT 1 FROM atlas_attribute_records WHERE id=NEW.id)
BEGIN
 SELECT RAISE(ABORT,'Invalid fixed topography classification') WHERE NEW.attribute='topography' AND json_type(NEW.value)='text' AND length(trim(json_extract(NEW.value,'$'),char(9,10,11,12,13,32,160,5760,8192,8193,8194,8195,8196,8197,8198,8199,8200,8201,8202,8232,8233,8239,8287,12288,65279)))>0 AND json_extract(NEW.value,'$') IS NOT NULL AND json_extract(NEW.value,'$') NOT IN ('topography:flat','Flatland','flat','flatland','topography:peak','Peak','peak','topography:ridge','Ridge','ridge','topography:shoulder','Shoulder','shoulder','topography:spur','Spur','spur','topography:slope','Slope','slope','topography:hollow','Hollow','hollow','topography:footslope','Footslope','footslope','topography:valley','Valley','valley','topography:pit','Pit','pit','topography:hills','Hills','hills','topography:mountains','Mountains','mountains');
 SELECT RAISE(ABORT,'Invalid fixed vegetation classification') WHERE NEW.attribute='vegetation' AND json_type(NEW.value)='text' AND length(trim(json_extract(NEW.value,'$'),char(9,10,11,12,13,32,160,5760,8192,8193,8194,8195,8196,8197,8198,8199,8200,8201,8202,8232,8233,8239,8287,12288,65279)))>0 AND json_extract(NEW.value,'$') IS NOT NULL AND json_extract(NEW.value,'$') NOT IN ('vegetation:tropical-moist-broadleaf-forest','Tropical & Subtropical Moist Broadleaf Forests','vegetation:tropical-dry-broadleaf-forest','Tropical & Subtropical Dry Broadleaf Forests','vegetation:tropical-conifer-forest','Tropical & Subtropical Coniferous Forests','vegetation:temperate-broadleaf-mixed-forest','Temperate Broadleaf & Mixed Forests','vegetation:temperate-conifer-forest','Temperate Conifer Forests','vegetation:boreal-forest','Boreal Forests/Taiga','vegetation:tropical-grassland-savanna-shrubland','Tropical & Subtropical Grasslands, Savannas & Shrublands','vegetation:temperate-grassland-savanna-shrubland','Temperate Grasslands, Savannas & Shrublands','vegetation:flooded-grassland-savanna','Flooded Grasslands & Savannas','vegetation:montane-grassland-shrubland','Montane Grasslands & Shrublands','vegetation:tundra','Tundra','tundra','vegetation:mediterranean-forest-woodland-scrub','Mediterranean Forests, Woodlands & Scrub','vegetation:desert-xeric-shrubland','Deserts & Xeric Shrublands','vegetation:mangroves','Mangroves','mangroves','vegetation:farmlands','Farmlands','farmlands','vegetation:woodlands','Woodlands','woodlands');
 SELECT RAISE(ABORT,'Invalid fixed climate classification') WHERE NEW.attribute='climate' AND json_type(NEW.value)='text' AND length(trim(json_extract(NEW.value,'$'),char(9,10,11,12,13,32,160,5760,8192,8193,8194,8195,8196,8197,8198,8199,8200,8201,8202,8232,8233,8239,8287,12288,65279)))>0 AND json_extract(NEW.value,'$') IS NOT NULL AND json_extract(NEW.value,'$') NOT IN ('climate:Af','Af tropical rainforest','Af','climate:Am','Am tropical monsoon','Am','climate:Aw','Aw tropical savanna','Aw','climate:BWh','BWh hot desert','BWh','climate:BWk','BWk cold desert','BWk','climate:BSh','BSh hot steppe','BSh','climate:BSk','BSk cold steppe','BSk','climate:Csa','Csa hot-summer Mediterranean','Csa','climate:Csb','Csb warm-summer Mediterranean','Csb','climate:Csc','Csc cold-summer Mediterranean','Csc','climate:Cwa','Cwa dry-winter humid subtropical','Cwa','climate:Cwb','Cwb subtropical highland','Cwb','climate:Cwc','Cwc cold subtropical highland','Cwc','climate:Cfa','Cfa humid subtropical','Cfa','climate:Cfb','Cfb oceanic','Cfb','climate:Cfc','Cfc subpolar oceanic','Cfc','climate:Dsa','Dsa hot dry-summer continental','Dsa','climate:Dsb','Dsb warm dry-summer continental','Dsb','climate:Dsc','Dsc cold dry-summer continental','Dsc','climate:Dsd','Dsd very cold dry-summer continental','Dsd','climate:Dwa','Dwa hot dry-winter continental','Dwa','climate:Dwb','Dwb warm dry-winter continental','Dwb','climate:Dwc','Dwc dry-winter subarctic','Dwc','climate:Dwd','Dwd very cold dry-winter subarctic','Dwd','climate:Dfa','Dfa hot humid continental','Dfa','climate:Dfb','Dfb warm humid continental','Dfb','climate:Dfc','Dfc subarctic','Dfc','climate:Dfd','Dfd very cold subarctic','Dfd','climate:ET','ET tundra','ET','climate:EF','EF ice cap','EF','climate:oceanic','Oceanic','oceanic','climate:mediterranean','Mediterranean','mediterranean');
END;
