"""Bind the bounded ordinary package; this does not execute geometry or declare approval."""
import pathlib,json,hashlib,gzip,subprocess,argparse
CASE=pathlib.Path(__file__).resolve().parent;ROOT=CASE.parents[2]
parser=argparse.ArgumentParser();parser.add_argument('--producer-commit',required=True);args=parser.parse_args();PRODUCER=args.producer_commit;assert len(PRODUCER)==40 and all(c in '0123456789abcdef'for c in PRODUCER)
def canon(v):return(json.dumps(v,sort_keys=True,ensure_ascii=False,separators=(',',':'),allow_nan=False)+'\n').encode()
def sha(b):return hashlib.sha256(b).hexdigest()
def desc(p):
 b=p.read_bytes();d={'path':str(p.relative_to(ROOT)),'bytes':len(b),'sha256':sha(b),'hash_kind':'file-bytes'}
 if b[:2]==b'\x1f\x8b':raw=gzip.decompress(b);d.update(uncompressed_bytes=len(raw),uncompressed_sha256=sha(raw));assert len(raw)<=32*1024*1024
 assert len(b)<=32*1024*1024;return d
scope=json.loads((CASE/'scope.json').read_bytes());catalogue=json.loads((CASE/'source-catalogue.json').read_bytes());aliases=json.loads((CASE/'input-aliases.json').read_bytes());alias_map={(v['original_commit'],v['original_path']):v['owned_path']for v in aliases['aliases']};config={'source_products':[v for v in catalogue['products']if v['key']in scope['source_ids']],'scope_sha256':sha((CASE/'scope.json').read_bytes())};base='0c2da56ad29dae452e6feb287cabdff5a83bbefa'
pinpaths={'original_administrative_registry':'data/administrative-sources.json','original_physical_inventory':'coordination/engineering/worldwide-inventory-1164-20261006/run-one/report.json','existing_lossless_codec':'scripts/evidence/immutable.py'}
pins={'original_administrative_registry':'ed0051d2956271c72f8917e7da0c6f53e5dfb595bee5920cac489a65a747d633','original_physical_inventory':'a5423b1e62b5a0793b83999d87d1f6d50916db482cf2ec74973f75555c2bda6c','existing_lossless_codec':'b7ff607b7774595788396e94f08fc29d750e4032624eb93732a5735c1ddcf7fd'}
baseline=[]
for key,path in pinpaths.items():
 b=subprocess.check_output(['git','show',base+':'+path],cwd=ROOT);assert sha(b)==pins[key];baseline.append({'path':path,'bytes':len(b),'sha256':sha(b),'hash_kind':'file-bytes','role':'original-source'})
sources=[];source_paths=set()
for product in config['source_products']:
 license_terms=product['recorded_license']+'; original source metadata and attribution retained through source catalogue and feature bindings.'
 if product['key']=='gb:OMN:ADM2':
  terms=desc(CASE/'CITATION-AND-USE-geoBoundaries-original.txt');assert terms['bytes']==4316 and terms['sha256']=='f6ea7572bea6036c4cdcacf8c0ca7bf09098d4e600d19546d7432533e9a290d5'
  license_terms='geoBoundaries derivative product: CC BY 4.0 with attribution, as stated in retained '+terms['path']+' (whole SHA '+terms['sha256']+'). Original underlying government metadata reports Other - Direct Permission; permission details remain unverified. Original metadata, source attribution and uncertainty are retained unchanged.'
 files=[desc(CASE/alias_map[('1c4b606d35614bd7c4990bb9da1098fa181c7fe8',p['path'])])for p in product['parts']];source_paths.update(f['path']for f in files)
 sources.append({'id':product['key'],'url':product['recorded_consumed_url'],'role':'Complete original consumed input geometry, not dated physical land/water or legal authority','vintage':'Original consumed whole SHA '+product['original_sha256']+'; advertised represented year '+str(product['source_represented_year_claim']),'retrieved_at':'2026-10-06 immutable accepted capsule readback; historical retrieval time remains unknown','license':{'status':'redistributable','terms':license_terms},'retention':'retained','verification':'unverified','temporal_status':'reference','files':files,'limit':'Whole source bytes verified, source date/physical water/legal meaning not independently approved.'})
manifest_path=str((CASE/'evidence-quality.json').relative_to(ROOT));outputs=[]
for p in sorted(CASE.rglob('*')):
 if not p.is_file()or p.name=='evidence-quality.json':continue
 assert not p.is_symlink();d=desc(p)
 if d['path']not in source_paths:outputs.append(d)
methods=[{'id':'immutable-preparation','kind':'generator','helper_version':'worldatlas-evidence-preparation-v1','description':'Exact ordinary gzip/source-part aliases, full raw source concatenation and hash checks, complete family membership, original whole-file/ordinal row equality and lossless full-pointset union-object retention. Numerical producer/input closure was frozen before both complete executions. Retain-run is separate byte transport only.','software':'Python 3.12.14; standard JSON/gzip; immutable producer '+PRODUCER,'units':'whole file bytes, canonical records, exact full pointsets, complete member counts'},{'id':'literal-source-intersections','kind':'measurement','description':'Complete source-product bbox queries and every literal GEOS source intersection/covers operation, whole candidate union/intersection/difference, zero-area contacts and explicit numerical consistency diagnostics. No rounding epsilon, snapping, wrapping, normalization or repair.','software':'Python 3.12.14; Shapely 2.1.2; GEOS 3.13.1','units':'literal longitude/latitude coordinate-unit squared areas and coordinate-unit lengths; not ellipsoidal m² or metres'}]
report_path=str((CASE/'verification/run-one-receipt.json.gz').relative_to(ROOT));report=json.loads(gzip.decompress((ROOT/report_path).read_bytes()));report_descriptor=next(p for p in outputs if p['path']==report_path)
metrics=[];bindings=[]
for key,unit in [('complete_components','components'),('complete_families','complete source families')]:
 metrics.append({'id':key,'value':report[key],'unit':unit,'vintage':'archived','evaluation_commit':PRODUCER,'input_sha256':report_descriptor['sha256']});bindings.append({'metric_id':key,'path':report_path,'json_pointer':'/'+key})
key='one-compatible-recorded-subject-uniquely-covers-component';metrics.append({'id':'unique_source_geometry_witnesses','value':report['counts'][key],'unit':'unapproved geometry witnesses','vintage':'archived','evaluation_commit':PRODUCER,'input_sha256':report_descriptor['sha256']});bindings.append({'metric_id':'unique_source_geometry_witnesses','path':report_path,'json_pointer':'/counts/'+key})
validation=[]
for method in methods:
 for kind in ['positive-control','negative-control']+(['reproducibility']if method['kind']=='generator'else[]):validation.append({'method_id':method['id'],'kind':kind,'outcome':'passed','evidence_path':str((CASE/'verification'/ (method['id']+'-'+kind+'.json')).relative_to(ROOT))})
allpaths=sorted({d['path']for d in outputs}|source_paths|{manifest_path})
manifest={'version':1,'issue':1246,'lane':'engineering','worker_id':'01a10893-2a57-72e0-aa08-5c36088d5206','subject_ids':[],'subject_ids_sha256':sha(b'[]'),'baseline':{'commit':base,'files':baseline,'pins':pins,'pin_files':pinpaths},'sources':sources,'outputs':outputs,'methods':methods,'validation':validation,'metrics':metrics,'metric_bindings':bindings,'summaries':[{'metric_id':m['id'],'value':m['value'],'unit':m['unit']}for m in metrics],'conclusions':[{'text':f'The complete {report["complete_families"]}-family / {report["complete_components"]}-component package reproduces every bound historical full row and preserves {report["complete_witnesses"]} unapproved source-geometry witnesses and {report["complete_operation_unknowns"]} numerical-consistency unknowns. This is package1; the full global goal remains unfinished.','status':'supported','source_ids':[v['key']for v in config['source_products']]},{'text':'Source coverage does not prove dated land, water, administrative ownership, the original processing cause, or a safe repair. Complete global remainder 6,023 families / 37,388 components remains separately retained; durable full plan is retained in this package.','status':'unresolved','source_ids':[]}],'stages':{'research':'complete','implementation':'implemented','geographic_approval':'unapproved'},'commands':[f'Run producer.py twice with immutable --producer-commit {PRODUCER} and distinct exclusive output directories using the pinned read-only Python runtime. Both actual commands and observed execution times/outcomes are retained.','Run controls.py, verify.py over each complete run, compare full verified scientific hashes over both actual complete trees, then retain-run.py for each complete run. Byte retention/readback is not a third scientific execution.'],'change_receipts':[{'path':p,'status':'added'}for p in allpaths],'package_scope':{'package':1,'scope_sha256':config['scope_sha256'],'complete_components':report['complete_components'],'complete_families':report['complete_families'],'source_vintages':'Original consumed geometries and accepted archived current-component successor, not production geography approval.'}}
(CASE/'evidence-quality.json').write_bytes(canon(manifest));total=sum(p['bytes']for p in baseline+outputs+[f for s in sources for f in s['files']]);count=len(baseline)+len(outputs)+sum(len(s['files'])for s in sources);assert total<=256*1024*1024 and count<=512,(total,count);print(json.dumps({'total_encoded_bytes':total,'descriptors':count,'headroom':256*1024*1024-total}))
