import sys,json,gzip,pathlib,hashlib,subprocess,time,resource
START=time.monotonic();ROOT=pathlib.Path(__file__).resolve().parents[3];OWN='research/geography/ukraine-original-singleton-source-fit-20261010/';COMMIT='c28077da970ae39550e5edea790a266b060d3de5';sys.path.insert(0,str(ROOT/'scripts'))
from evidence.immutable import Baseline,NewVintage,descriptor,canonical_json
from shapely.geometry import shape
import shapely
sha=lambda b:hashlib.sha256(b).hexdigest();paths=['scripts/evidence/immutable.py','data/geography/part-10.json','data/geography/part-25.json','coordination/engineering/physical-gap-components-1005-20261005-local19/custody-v1/payloads/541236815314006fd30cd216a42cd7aaca78fa7eb50423515ca8b96bc0b87014.bin'];pins=[descriptor(p,subprocess.check_output(['git','-C',str(ROOT),'show',COMMIT+':'+p])) for p in paths];base=Baseline(ROOT,COMMIT,pins);dest=NewVintage(base,OWN,'current-target-probe-001',['result.json'])
b=gzip.decompress(base.pinned_bytes(paths[-1]));base.admit('decoded-components-004',len(b));cf=next(f for f in json.loads(b)['features'] if f['id']=='physical-component:6fd25496ae4a7635eef229d0cfd1eb8dc7d9c10c252d3255fe8d42d186e706d1');assert sha(canonical_json(cf))=='acd61551d2dbc9b6925e6d8c2d17cb210a6dcf6f3d80bbbadb64951660e3b746'
ids=['gb:HUN:ADM2:29324351B39716599464162','gb:UKR:ADM2:74538382B77535249747568'];features=[]
for path,id in zip(paths[1:3],ids):
 fs=json.loads(base.pinned_bytes(path))['features'];m=[(i,f) for i,f in enumerate(fs) if f['properties']['id']==id];assert len(m)==1;features.append(m[0][1])
hf,tf=features;assert sha(canonical_json(hf))=='080637bfa265438fe0c2778853c6ff8f2cb40e868e548f409803311e55963e69';assert sha(canonical_json(tf))=='2be466947ed68b5372851bf0b737ed3fcbba1eb6e01cd7d21cb1a90cbaa7f6c7'
c,t,h=map(shape,[cf['geometry'],tf['geometry'],hf['geometry']]);assert c.is_valid and t.is_valid and h.is_valid
a=t.union(c);gain=a.difference(t);loss=t.difference(a);conservation=gain.symmetric_difference(c);neighbor=h.intersection(c);overlap=t.intersection(c)
def g(x):return {'type':x.geom_type,'empty':x.is_empty,'valid':x.is_valid,'area_coordinate_units_squared':x.area,'geometry':x.__geo_interface__}
r={'issue':1693,'component':cf['id'],'baseline':COMMIT,'target':{'feature_sha256':sha(canonical_json(tf)),'properties':tf['properties']},'neighbor':{'feature_sha256':sha(canonical_json(hf)),'properties':hf['properties']},'conditions':{'target_already_covers_candidate':t.covers(c),'target_candidate_overlap_empty':overlap.is_empty,'target_candidate_overlap_zero_area':overlap.area==0,'union_valid':a.is_valid,'loss_empty':loss.is_empty,'gain_equals_candidate_literal_empty_symmetric_difference':conservation.is_empty,'gain_equals_candidate_zero_area_symmetric_difference':conservation.area==0,'named_HUN_neighbor_positive_overlap_absent':neighbor.area==0},'gain':g(gain),'loss':g(loss),'candidate_gain_symmetric_difference':g(conservation),'named_HUN_neighbor_intersection':g(neighbor),'prior_target_intersection':g(overlap),'consumed_input_pins':pins,'producer_sha256':sha(pathlib.Path(__file__).read_bytes()),'elapsed_seconds':time.monotonic()-START,'peak_rss_bytes':resource.getrusage(resource.RUSAGE_SELF).ru_maxrss*1024,'input_logical_bytes':sum(base.consumed.values()),'shapely':shapely.__version__,'geos':shapely.geos_version_string,'limits':['Literal current base features only; selected added primitives/full current exclusion certificate not checked','No source-relative fit approval or native/continuous delivery claimed']};assert r['peak_rss_bytes']<1024**3;print(json.dumps(dest.publish({'result.json':r})));print(json.dumps({k:r[k] for k in ['conditions','gain','candidate_gain_symmetric_difference','peak_rss_bytes','elapsed_seconds']}))
