import fs from 'node:fs';import assert from 'node:assert/strict';import {candidateBudget} from '../../WorldAtlas/scripts/native-ownership/native-preparation-guards.mjs';
const D=new URL('./',import.meta.url),s=fs.readFileSync(new URL('caller-proposed.mjs',D),'utf8'),base=fs.readFileSync(new URL('base.mjs',D),'utf8');const demand=(x,m)=>{if(!x)throw Error(m);},equal=(a,b)=>JSON.stringify(a)===JSON.stringify(b),pinCost=p=>[{bytes:p.bytes},...(p.uncompressed_bytes===undefined?[]:[{bytes:p.uncompressed_bytes}])];
const hs=s.indexOf('function administrativeLifetimeBudget('),he=s.indexOf('\nfunction administrativeBatchProposalStage(',hs),helper=new Function('candidateBudget','demand',s.slice(hs,he)+';return administrativeLifetimeBudget;')(candidateBudget,demand);
const start=s.indexOf('  // SEA318\'s case view parses'),end=s.indexOf('  const manifest=json(spec.manifest_path)',start),block=s.slice(start,end);let checks=[];
function run({missing=false,changed=false}={}){const pins=[['corpus',80],['physical',50],['metadata',20],['bindings',22],['query',100],['bounds',40],['targets',30],['latitude',16],['owner',12],['facts',10]].map(([path,bytes])=>({path,bytes,sha256:path}));const spec={inputs:pins,manifest_path:'facts',bounds_path:'bounds',latitudes_path:'latitude',facts_path:'facts',owner_parts:[{path:'owner'}]},issued={source_rule:{family_roster_path:'family',target_banks:['targets'],original_query_metadata_path:'metadata',target_canonical_bindings_path:'bindings',inputs:pins.map(p=>({...p}))}},sourceRows=[{source_case:{source:pins[0]},original_record:missing?{}:{source:pins[1]}}];if(changed)issued.source_rule.inputs.find(p=>p.path==='physical').sha256='changed';const inputs=new Map(pins.map(pin=>[pin.path,{pin,body:Buffer.alloc(pin.bytes)}])),authenticatedPins=new Map(pins.map(pin=>[pin.path,pin])),releasedPaths=new Set(),accessedPaths=new Set(['facts']),get=name=>{demand(!releasedPaths.has(name),'released');const e=inputs.get(name);demand(e,'missing');return e;},getPin=name=>({pin:authenticatedPins.get(name)}),budget=helper(pins.flatMap(pinCost),{runtimeBytes:1,outputReserve:100});budget.nativeStageCostStart=0;
new Function('spec','issued','sourceRows','inputs','releasedPaths','accessedPaths','get','budget','demand','pinCost','equal',block)(spec,issued,sourceRows,inputs,releasedPaths,accessedPaths,get,budget,demand,pinCost,equal);return {inputs,get,getPin,releasedPaths,budget};}
const r=run();for(const path of ['physical','metadata','bindings','corpus'])assert(r.get(path).body instanceof Buffer);assert(r.releasedPaths.has('query'));assert.throws(()=>r.get('query'));assert.equal(r.getPin('query').pin.sha256,'query');const charges=r.budget.snapshot().lifetime.retained_closure_charges;for(const path of ['physical','metadata','bindings'])assert(charges.some(p=>p.path===path&&p.role==='whole-SEA318-physical-and-metadata-parsed-closure'));assert.throws(()=>run({missing:true}),/Missing\/changed/);assert.throws(()=>run({changed:true}),/Missing\/changed/);checks.push('Actual native release block protects physical/copy-metadata/binding bodies and charges all parsed closures','Query raw removed; authenticated full descriptor remains; ordinary reopen refused','Missing physical source or changed source descriptor refused before release');
const a=s.indexOf('function administrative318SourceScope('),b=s.indexOf('\nfunction administrative318SourcePremiseStage(',a),scope=new Function('demand','retainedAdministrative318CaseView',s.slice(a,b)+';return administrative318SourceScope;')(demand,x=>x),query={path:'query',bytes:5,sha256:'q',uncompressed_bytes:10,uncompressed_sha256:'qd'},q={case_file:'physical',case_file_bytes:2,case_file_sha256:'p',case_file_uncompressed_sha256:'pd',complete_query_source_pointsets:[{source_file:'query',...query}],complete_original_query_source_ids:[1]},fit={cases:[{component_id:'id',original_physical_query_custody:q}]},rule={original_query_metadata_path:'metadata',target_canonical_bindings_path:'bindings'};let typed=0;const get=n=>{assert.notEqual(n,'query');return {pin:n==='physical'?{bytes:2,sha256:'p',uncompressed_sha256:'pd'}:{},body:Buffer.from(n==='metadata'?'[{"source_id":1}]':n==='bindings'?'[]':'{}')};},getPin=n=>{typed++;assert.equal(n,'query');return {pin:query};};assert.equal(scope(fit,get,rule,'id',getPin).querySources[0].source_id,1);assert.equal(typed,1);assert.throws(()=>scope(fit,get,rule,'id',()=>({pin:{...query,uncompressed_sha256:'drift'}})));checks.push('Actual SEA native scope uses typed query custody with unchanged byte/hash/decoded checks');
assert(s.includes('administrative318SourceScope(rawScope,get,issued.source_rule,selected.component_id,getPin)'));
for(const name of ['administrative318SourcePremiseStage','retainedAdministrative318CaseView','retainedAdministrativeSourcePremises','validateAdministrativeNativeCase','administrativeSourceLifetimeBudget']){const at=base.indexOf('function '+name+'(');assert(at>=0);const extract=x=>{const i=x.indexOf('function '+name+'(');return x.slice(i,x.indexOf('\n}',i)+2);};assert.equal(extract(s),extract(base));}checks.push('SOURCE parse-order fix and original scientific/source predicates byte-for-byte unchanged');
const result={kind:'cache-only-SEA318-native-live-path-controls',operators_executed:false,actual_native_admission:false,checks:checks.map(name=>({name,pass:true}))};fs.writeFileSync(new URL('focused-controls.json',D),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));
