<?xml version="1.0" encoding="utf-8" ?>
<xsd:schema xmlns:INSPIRE_AM_WaterBodyForWFD_WFDRiver="https://inspire.apambiente.pt/arcgis/services/INSPIRE/AM_WaterBodyForWFD_WFDRiver/MapServer/WFSServer" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:gml="http://www.opengis.net/gml/3.2" targetNamespace="https://inspire.apambiente.pt/arcgis/services/INSPIRE/AM_WaterBodyForWFD_WFDRiver/MapServer/WFSServer" elementFormDefault="qualified" attributeFormDefault="unqualified">
<xsd:import namespace="http://www.opengis.net/gml/3.2" schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd"/>
<xsd:element name="AM.WaterBodyForWFD" type="INSPIRE_AM_WaterBodyForWFD_WFDRiver:AM.WaterBodyForWFDFeatureType" substitutionGroup="gml:AbstractFeature"/>
<xsd:complexType name="AM.WaterBodyForWFDFeatureType">
  <xsd:complexContent>
    <xsd:extension base="gml:AbstractFeatureType">
      <xsd:sequence>
        <xsd:element minOccurs="0" maxOccurs="1" name="objectid" type="xsd:int"/>
        <xsd:element minOccurs="0" maxOccurs="1" name="codigo" nillable="true">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:maxLength value="42"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element minOccurs="0" maxOccurs="1" name="nome" nillable="true">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:maxLength value="255"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element minOccurs="0" maxOccurs="1" name="categoria" nillable="true">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:maxLength value="255"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element minOccurs="0" maxOccurs="1" name="regiao_hid" nillable="true">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:maxLength value="42"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element minOccurs="0" maxOccurs="1" name="regiao_name" nillable="true">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:maxLength value="255"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element minOccurs="0" maxOccurs="1" name="natur_fm_art" nillable="true">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:maxLength value="255"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element minOccurs="0" maxOccurs="1" name="tipologia" nillable="true">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:maxLength value="255"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element minOccurs="0" maxOccurs="1" name="transfronteirica" nillable="true">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:maxLength value="255"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element minOccurs="0" maxOccurs="1" name="est_pot_ecol" nillable="true">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:maxLength value="255"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element minOccurs="0" maxOccurs="1" name="objetivo_eco" nillable="true">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:maxLength value="255"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element minOccurs="0" maxOccurs="1" name="estado_quim" nillable="true">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:maxLength value="255"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element minOccurs="0" maxOccurs="1" name="objetivo_quim" nillable="true">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:maxLength value="255"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element minOccurs="0" maxOccurs="1" name="estado_global" nillable="true">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:maxLength value="255"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element minOccurs="0" maxOccurs="1" name="shape" nillable="true" type="gml:MultiCurvePropertyType"/>
        <xsd:element minOccurs="0" maxOccurs="1" name="st_length_shape_" type="xsd:double"/>
      </xsd:sequence>
    </xsd:extension>
  </xsd:complexContent>
</xsd:complexType>
</xsd:schema>
