"""Extract complete original operands for one admitted numerical cohort.

This is acquisition only. Exhaustive campaign joins precede these jobs; the
cohort selector is an authenticated product of those joins, not a CLI ID list.
Every containing body is consumed whole and every selected object is compared
with its previously authenticated canonical bytes. No numerical operator runs.
"""
import json


def rows(phase, pin, expected, acquisition):
    """Read a complete ordinary containing file, rejecting duplicate identities."""
    values = {}
    for ordinal, line in enumerate(phase.read(pin).splitlines()):
        row = json.loads(line)
        identity = row.get(expected)
        acquisition.require(type(identity) is str and identity not in values,
                          'Duplicate/nonstring whole containing identity')
        values[identity] = (ordinal, line + b'\n', row)
    return values


def extract(phase, selector_pin, *, acquisition, canonical_json):
    """Return only a publication receipt; no global dictionary crosses stages.

    Selector rows carry the complete component alias/containing-table pin and
    physical/diagnosis indices, plus the authenticated routing row. They must
    be generated by the complete campaign join and declared as a real input.
    All selected operands remain full bodies, including unresolved evidence.
    """
    selected = json.loads(phase.read(selector_pin))
    acquisition.require(type(selected) is dict and selected.get('kind') ==
                        'complete-original-numerical-cohort-selector', 'Wrong cohort selector')
    items = acquisition.exact_ids(selected['rows'], 'id')
    join = selected['campaign_join']
    inventory = acquisition.completed_inventory(phase, join['publication'], join['inventory'])
    facts = inventory['facts']
    acquisition.require(selected['campaign_join_sha256'] == join['inventory']['sha256'] and
                        facts.get('operation') in ('complete-original-physical-query-join',
                                                  'complete-original-physical-query-join-via-membership-v1') and
                        facts.get('complete') == 95173 and facts.get('mismatches') == 1294 and
                        facts.get('ordered_queries') == 10419,
                        'Missing/changed complete campaign join binding')
    physical = {}; diagnoses = {}; operands = []; wanted = set(); ordered_queries = 0
    for identity, item in sorted(items.items()):
        candidate = acquisition.resolve(phase, item['candidate_alias'],
                                        item['candidate_containing_table'], canonical_json)
        routing = item['routing']['row']
        acquisition.require(item['routing']['id'] == identity and
                            item['routing']['selected'] is True and candidate['id'] == identity and
                            acquisition.sha(canonical_json(candidate)) == routing['current_feature_sha256'] and
                            acquisition.sha(canonical_json(candidate['geometry'])) == routing['current_geometry_sha256'],
                            'Actual complete candidate/routing bytes differ')
        physical_index = item['physical_index']; physical_pin = item['physical_containing_pin']
        key = phase.key(physical_pin)
        if key not in physical:
            physical[key] = rows(phase, physical_pin, 'component_id', acquisition)
        acquisition.require(identity in physical[key], 'Missing complete original physical row')
        ordinal, raw, body = physical[key][identity]
        acquisition.require(physical_index['id'] == identity and
                            ordinal == physical_index['row_ordinal'] and
                            acquisition.sha(raw) == physical_index['restored_whole_row_sha256'] and
                            physical_index['original_path'] == routing['whole_physical_containing_file'] and
                            physical_index['packed_whole_row_sha256'] == routing['whole_physical_row_sha256'],
                            'Whole original physical containing/ordinal/bytes binding differs')
        diagnosis_index = item['diagnosis_index']; diagnosis_pin = diagnosis_index['input']
        key = phase.key(diagnosis_pin)
        if key not in diagnoses:
            diagnoses[key] = rows(phase, diagnosis_pin, 'component_id', acquisition)
        acquisition.require(identity in diagnoses[key], 'Missing complete original diagnosis row')
        diagnosis_ordinal, diagnosis_raw, diagnosis = diagnoses[key][identity]
        acquisition.require(diagnosis_index['id'] == identity and
                            diagnosis_ordinal == diagnosis_index['row_ordinal'] and
                            acquisition.sha(diagnosis_raw) == diagnosis_index['whole_row_sha256'] and
                            diagnosis['status'] == diagnosis_index['status'] == 'original-replay-mismatch',
                            'Actual original mismatch diagnosis binding differs')
        queries = body['query_relations']
        acquisition.require(type(queries) is list and len(queries) == physical_index['query_count'],
                            'Complete original ordered query count differs')
        for query in queries:
            acquisition.require(type(query['source_id']) is int,
                                'Wrong original native query identity type')
            wanted.add(query['source_id'])
        ordered_queries += len(queries)
        alias = dict(path=item['packed_containing_path'],
                     original_path=physical_index['original_path'], row_ordinal=ordinal,
                     whole_delivered_packed_row_sha256=physical_index['packed_whole_row_sha256'],
                     packed_row_hash_domain='complete-delivered-packed-canonical-row',
                     restored_whole_row_sha256=physical_index['restored_whole_row_sha256'],
                     restored_row_hash_domain='original104-scientific-row-with-current-context-fields-restored',
                     complete_current_feature_sha256=routing['current_feature_sha256'])
        operands.append(dict(id=identity, candidate=candidate, physical=body,
                             physical_alias=alias, diagnosis=diagnosis, routing=routing))
    acquisition.require(ordered_queries == selected['ordered_queries'] and
                        len(items) == selected['components'] and
                        sorted(wanted) == selected['wanted_native_ids'],
                        'Complete actual cohort query/subject/native inventory differs')
    phase.rows('complete-cohort-operands', operands)
    del physical, diagnoses, operands
    return phase.finish(dict(operation='complete-original-numerical-cohort-acquisition',
                             component_ids=sorted(items), ordered_queries=ordered_queries,
                             wanted_native_ids=sorted(wanted),
                             campaign_join_sha256=selected['campaign_join_sha256']))
