import {sql} from 'drizzle-orm';
import {sqliteTable,text,integer,index,uniqueIndex,primaryKey,check,type AnySQLiteColumn} from 'drizzle-orm/sqlite-core';

const object=(column:AnySQLiteColumn)=>sql`json_valid(${column}) AND json_type(${column})='object'`;
const date=(column:AnySQLiteColumn,end=false)=>sql`typeof(${column})='integer' AND ${column} BETWEEN ${sql.raw(end?'-2999':'-3000')} AND ${sql.raw(end?'2027':'2026')} AND ${column}!=0`;
export const atlasSources=sqliteTable('atlas_sources',{
 id:text('id').primaryKey().notNull(),name:text('name').notNull(),url:text('url'),license:text('license').notNull(),vintage:text('vintage').notNull(),
 supportedFrom:integer('supported_from').notNull(),supportedTo:integer('supported_to').notNull(),status:text('status').notNull(),metadata:text('metadata').notNull().default('{}'),
},t=>[check('source_text',sql`length(trim(${t.id}))>0 AND length(trim(${t.name}))>0 AND length(trim(${t.license}))>0 AND length(trim(${t.vintage}))>0`),check('source_dates',sql`${date(t.supportedFrom)} AND ${date(t.supportedTo,true)} AND ${t.supportedTo}>${t.supportedFrom}`),check('source_status',sql`${t.status} IN ('historical','reference','estimate','example')`),check('source_metadata',object(t.metadata))]);
export const atlasEntityTypes=sqliteTable('atlas_entity_types',{
 id:text('id').primaryKey().notNull(),name:text('name').notNull(),geographicLevel:integer('geographic_level'),metadata:text('metadata').notNull().default('{}'),
},t=>[check('entity_type_text',sql`length(trim(${t.id}))>0 AND length(trim(${t.name}))>0`),check('entity_type_level',sql`(${t.id} IN ('location','province','area','region','subcontinent','continent') AND ${t.geographicLevel} IS NOT NULL AND ${t.geographicLevel}=CASE ${t.id} WHEN 'location' THEN 0 WHEN 'province' THEN 1 WHEN 'area' THEN 2 WHEN 'region' THEN 3 WHEN 'subcontinent' THEN 4 WHEN 'continent' THEN 5 END) OR (${t.id} NOT IN ('location','province','area','region','subcontinent','continent') AND ${t.geographicLevel} IS NULL)`),check('entity_type_metadata',object(t.metadata))]);
export const atlasEntities=sqliteTable('atlas_entities',{
 id:text('id').primaryKey().notNull(),kind:text('kind').notNull().references(()=>atlasEntityTypes.id),name:text('name').notNull(),parentId:text('parent_id').references(():AnySQLiteColumn=>atlasEntities.id),
 validFrom:integer('valid_from'),validTo:integer('valid_to'),sourceId:text('source_id').references(()=>atlasSources.id),referenceOwner:text('reference_owner'),isExample:integer('is_example').notNull().default(0),active:integer('active').notNull().default(1),metadata:text('metadata').notNull().default('{}'),
},t=>[index('entities_kind_id').on(t.kind,t.active,t.id),index('entities_parent').on(t.parentId),check('entity_text',sql`length(trim(${t.id}))>0 AND length(trim(${t.name}))>0`),check('entity_dates',sql`(${t.validFrom} IS NULL OR ${date(t.validFrom)}) AND (${t.validTo} IS NULL OR ${date(t.validTo,true)}) AND (${t.validFrom} IS NULL OR ${t.validTo} IS NULL OR ${t.validTo}>${t.validFrom}) AND ((${t.validFrom} IS NULL AND ${t.validTo} IS NULL) OR ${t.sourceId} IS NOT NULL)`),check('entity_example',sql`${t.isExample} IN (0,1)`),check('entity_active',sql`${t.active} IN (0,1)`),check('entity_metadata',object(t.metadata))]);
export const atlasCategories=sqliteTable('atlas_categories',{
 id:text('id').primaryKey().notNull().references(()=>atlasEntities.id),kind:text('kind').notNull(),name:text('name').notNull(),sourceId:text('source_id').notNull().references(()=>atlasSources.id),metadata:text('metadata').notNull().default('{}'),
},t=>[check('category_text',sql`length(trim(${t.id}))>0 AND length(trim(${t.name}))>0`),check('category_kind',sql`${t.kind} IN ('owner','culture','religion')`),check('category_metadata',object(t.metadata))]);
export const atlasAttributeRecords=sqliteTable('atlas_attribute_records',{
 id:text('id').primaryKey().notNull(),locationId:text('location_id').notNull().references(()=>atlasEntities.id),attribute:text('attribute').notNull(),value:text('value').notNull(),categoryId:text('category_id').references(()=>atlasCategories.id),
 validFrom:integer('valid_from').notNull(),validTo:integer('valid_to').notNull(),method:text('method').notNull(),status:text('status').notNull(),sourceId:text('source_id').notNull().references(()=>atlasSources.id),isExample:integer('is_example').notNull().default(0),metadata:text('metadata').notNull().default('{}'),
},t=>[index('attributes_location_dates').on(t.locationId,t.attribute,t.validFrom,t.validTo),index('attributes_date_id').on(t.validFrom,t.validTo,t.id),check('attribute_names',sql`${t.attribute} IN ('owner','population','culture','religion','rank','topography','vegetation','climate','habitation')`),check('attribute_dates',sql`${date(t.validFrom)} AND ${date(t.validTo,true)} AND ${t.validTo}>${t.validFrom}`),check('attribute_value',sql`json_valid(${t.value}) AND (json_type(${t.value})='null' OR (${t.attribute}='population' AND json_type(${t.value})='integer' AND json_extract(${t.value},'$') BETWEEN 0 AND 9007199254740991) OR (${t.attribute}!='population' AND json_type(${t.value})='text' AND length(trim(json_extract(${t.value},'$')))>0))`),check('attribute_category',sql`(${t.attribute} NOT IN ('owner','culture','religion') OR json_type(${t.value})='null' OR ${t.categoryId} IS NOT NULL) AND (${t.categoryId} IS NULL OR (${t.attribute} IN ('owner','culture','religion') AND json_type(${t.value})='text'))`),check('attribute_rank',sql`${t.attribute}!='rank' OR json_type(${t.value})='null' OR json_extract(${t.value},'$') IN ('unsettled','rural settlement','town','city','metropolis')`),check('attribute_habitation',sql`${t.attribute}!='habitation' OR json_type(${t.value})='null' OR json_extract(${t.value},'$') IN ('inhabited','uninhabited','unknown')`),check('attribute_method',sql`${t.method} IN ('direct','majority-area','derived','reference','estimate')`),check('attribute_status',sql`${t.status} IN ('sourced','derived','reference','estimate','unknown','disputed','no-majority','example')`),check('attribute_example',sql`${t.isExample} IN (0,1)`),check('attribute_metadata',object(t.metadata))]);
export const atlasNames=sqliteTable('atlas_names',{
 id:text('id').primaryKey().notNull(),entityId:text('entity_id').notNull().references(()=>atlasEntities.id),name:text('name').notNull(),language:text('language').notNull().default('und'),role:text('role').notNull().default('preferred'),validFrom:integer('valid_from').notNull(),validTo:integer('valid_to').notNull(),sourceId:text('source_id').notNull().references(()=>atlasSources.id),isExample:integer('is_example').notNull().default(0),metadata:text('metadata').notNull().default('{}'),
},t=>[index('names_entity_dates').on(t.entityId,t.validFrom,t.validTo),check('name_text',sql`length(trim(${t.name}))>0 AND length(trim(${t.language}))>0`),check('name_role',sql`${t.role} IN ('preferred','alias')`),check('name_dates',sql`${date(t.validFrom)} AND ${date(t.validTo,true)} AND ${t.validTo}>${t.validFrom}`),check('name_example',sql`${t.isExample} IN (0,1)`),check('name_metadata',object(t.metadata))]);
export const atlasRelationships=sqliteTable('atlas_relationships',{
 id:text('id').primaryKey().notNull(),sourceEntityId:text('source_entity_id').notNull().references(()=>atlasEntities.id),targetEntityId:text('target_entity_id').notNull().references(()=>atlasEntities.id),relationshipType:text('relationship_type').notNull(),validFrom:integer('valid_from'),validTo:integer('valid_to'),sourceId:text('source_id').notNull().references(()=>atlasSources.id),isExample:integer('is_example').notNull().default(0),metadata:text('metadata').notNull().default('{}'),
},t=>[index('relationships_source_dates').on(t.sourceEntityId,t.validFrom,t.validTo),index('relationships_target_dates').on(t.targetEntityId,t.validFrom,t.validTo),check('relationship_text',sql`length(trim(${t.relationshipType}))>0`),check('relationship_dates',sql`(${t.validFrom} IS NULL AND ${t.validTo} IS NULL) OR (${t.validFrom} IS NOT NULL AND ${t.validTo} IS NOT NULL AND ${date(t.validFrom)} AND ${date(t.validTo,true)} AND ${t.validTo}>${t.validFrom})`),check('relationship_example',sql`${t.isExample} IN (0,1)`),check('relationship_metadata',object(t.metadata))]);
export const atlasMedia=sqliteTable('atlas_media',{
 id:text('id').primaryKey().notNull(),objectKey:text('object_key').notNull().unique(),sha256:text('sha256').notNull(),bytes:integer('bytes').notNull(),mime:text('mime').notNull(),name:text('name').notNull(),license:text('license').notNull(),attribution:text('attribution').notNull(),sourceId:text('source_id').notNull().references(()=>atlasSources.id),status:text('status').notNull().default('ready'),metadata:text('metadata').notNull().default('{}'),
},t=>[check('media_digest',sql`length(${t.sha256})=64 AND ${t.sha256} NOT GLOB '*[^0-9a-f]*' AND ${t.objectKey}='media/'||${t.sha256}`),check('media_bytes',sql`typeof(${t.bytes})='integer' AND ${t.bytes}>=0 AND ${t.bytes}<=9007199254740991`),check('media_text',sql`length(trim(${t.objectKey}))>0 AND length(trim(${t.mime}))>0 AND length(trim(${t.name}))>0 AND length(trim(${t.license}))>0 AND length(trim(${t.attribution}))>0`),check('media_status',sql`${t.status} IN ('pending','ready','published')`),check('media_metadata',object(t.metadata))]);
export const atlasMediaLinks=sqliteTable('atlas_media_links',{
 id:text('id').primaryKey().notNull(),mediaId:text('media_id').notNull().references(()=>atlasMedia.id),entityId:text('entity_id').notNull().references(()=>atlasEntities.id),role:text('role').notNull(),caption:text('caption'),sourceId:text('source_id').notNull().references(()=>atlasSources.id),isExample:integer('is_example').notNull().default(0),validFrom:integer('valid_from'),validTo:integer('valid_to'),metadata:text('metadata').notNull().default('{}'),
},t=>[index('media_links_entity').on(t.entityId),check('media_link_example',sql`${t.isExample} IN (0,1)`),check('media_link_role',sql`length(trim(${t.role}))>0`),check('media_link_dates',sql`(${t.validFrom} IS NULL AND ${t.validTo} IS NULL) OR (${t.validFrom} IS NOT NULL AND ${t.validTo} IS NOT NULL AND ${date(t.validFrom)} AND ${date(t.validTo,true)} AND ${t.validTo}>${t.validFrom})`),check('media_link_metadata',object(t.metadata))]);
export const atlasIngestions=sqliteTable('atlas_ingestions',{
 id:text('id').primaryKey().notNull(),fingerprint:text('fingerprint').notNull(),counts:text('counts').notNull(),createdAt:integer('created_at').notNull(),
},t=>[check('ingestion_counts',object(t.counts)),check('ingestion_fingerprint',sql`length(${t.fingerprint})=64`)]);

// Withdraw claims without changing their original values, identities or sources.
export const atlasEvidenceRetirements=sqliteTable('atlas_evidence_retirements',{
 id:text('id').primaryKey().notNull(),collection:text('collection').notNull(),targetId:text('target_id').notNull(),sourceId:text('source_id').notNull().references(()=>atlasSources.id),reason:text('reason').notNull(),replacementId:text('replacement_id'),metadata:text('metadata').notNull().default('{}'),
},t=>[uniqueIndex('retirements_target').on(t.collection,t.targetId),check('retirement_collection',sql`${t.collection} IN ('records','names','relationships','media_links')`),check('retirement_text',sql`length(trim(${t.id}))>0 AND length(trim(${t.targetId}))>0 AND length(trim(${t.reason}))>0`),check('retirement_replacement',sql`${t.replacementId} IS NULL OR (length(trim(${t.replacementId}))>0 AND ${t.replacementId}!=${t.targetId})`),check('retirement_metadata',object(t.metadata))]);

// Publication/reference versions are independent of historical membership claims.
const digest=(column:AnySQLiteColumn)=>sql`length(${column})=64 AND ${column} NOT GLOB '*[^0-9a-f]*'`;
export const atlasGeographicReleases=sqliteTable('atlas_geographic_releases',{
 id:text('id').primaryKey().notNull(),sourceId:text('source_id').notNull().references(()=>atlasSources.id),version:integer('version').notNull(),referenceDate:text('reference_date').notNull(),status:text('status').notNull().default('staged'),
 hierarchySha256:text('hierarchy_sha256').notNull(),footprintsSha256:text('footprints_sha256').notNull(),membershipSha256:text('membership_sha256').notNull(),locationIdsSha256:text('location_ids_sha256').notNull(),changesSha256:text('changes_sha256').notNull(),expectedCounts:text('expected_counts').notNull(),metadata:text('metadata').notNull().default('{}'),publishedAt:integer('published_at'),
},t=>[uniqueIndex('geographic_releases_version').on(t.version),index('geographic_releases_published').on(t.status,t.version),check('geographic_release_text',sql`length(trim(${t.id}))>0 AND length(trim(${t.referenceDate}))>0`),check('geographic_release_version',sql`typeof(${t.version})='integer' AND ${t.version}>0`),check('geographic_release_status',sql`(${t.status}='staged' AND ${t.publishedAt} IS NULL) OR (${t.status}='published' AND typeof(${t.publishedAt})='integer' AND ${t.publishedAt}>0)`),check('geographic_release_hashes',sql`${digest(t.hierarchySha256)} AND ${digest(t.footprintsSha256)} AND ${digest(t.membershipSha256)} AND ${digest(t.locationIdsSha256)} AND ${digest(t.changesSha256)}`),check('geographic_release_counts',object(t.expectedCounts)),check('geographic_release_metadata',object(t.metadata))]);
export const atlasGeographicMemberships=sqliteTable('atlas_geographic_memberships',{
 releaseId:text('release_id').notNull().references(()=>atlasGeographicReleases.id),entityId:text('entity_id').notNull().references(()=>atlasEntities.id),parentId:text('parent_id').references(()=>atlasEntities.id),referenceName:text('reference_name'),active:integer('active').notNull().default(1),sourceId:text('source_id').notNull().references(()=>atlasSources.id),evidence:text('evidence').notNull().default('{}'),
},t=>[primaryKey({columns:[t.releaseId,t.entityId]}),index('geographic_membership_parent').on(t.releaseId,t.active,t.parentId,t.entityId),index('geographic_membership_page').on(t.releaseId,t.active,t.entityId),check('geographic_membership_active',sql`${t.active} IN (0,1)`),check('geographic_membership_name',sql`${t.referenceName} IS NULL OR length(trim(${t.referenceName}))>0`),check('geographic_membership_evidence',object(t.evidence))]);
export const atlasGeographicChanges=sqliteTable('atlas_geographic_changes',{
 id:text('id').primaryKey().notNull(),releaseId:text('release_id').notNull().references(()=>atlasGeographicReleases.id),oldEntityId:text('old_entity_id').references(()=>atlasEntities.id),newEntityId:text('new_entity_id').references(()=>atlasEntities.id),changeType:text('change_type').notNull(),sourceId:text('source_id').notNull().references(()=>atlasSources.id),evidence:text('evidence').notNull(),
},t=>[index('geographic_changes_page').on(t.releaseId,t.id),index('geographic_changes_old').on(t.oldEntityId,t.releaseId),check('geographic_change_text',sql`length(trim(${t.id}))>0`),check('geographic_change_kind',sql`${t.changeType} IN ('retain','rename','reparent','merge','split','replace','retire','create')`),check('geographic_change_endpoints',sql`(${t.changeType}='create' AND ${t.oldEntityId} IS NULL AND ${t.newEntityId} IS NOT NULL) OR (${t.changeType}='retire' AND ${t.oldEntityId} IS NOT NULL AND ${t.newEntityId} IS NULL) OR (${t.changeType} IN ('retain','rename','reparent') AND ${t.oldEntityId} IS NOT NULL AND ${t.oldEntityId}=${t.newEntityId}) OR (${t.changeType} IN ('merge','split','replace') AND ${t.oldEntityId} IS NOT NULL AND ${t.newEntityId} IS NOT NULL AND ${t.oldEntityId}!=${t.newEntityId})`),check('geographic_change_evidence',object(t.evidence))]);
