import assert from 'node:assert/strict';
import {gzipSync} from 'node:zlib';
import {createHash} from 'node:crypto';
import {packOwnership} from '../../../src/pixel-ownership.js';
import {shuffleOwnershipBytes} from '../../../src/ownership-codec.js';
import {loadOwnershipAssets} from '../../../src/ownership-assets.js';
import {validateRuns,differences} from './reproduce.mjs';
const hash=b=>createHash('sha256').update(b).digest('hex');
const grid=packOwnership({size:8,rows:[new Uint32Array(),Uint32Array.from([1,3,120000]),...Array.from({length:6},()=>new Uint32Array())]});
assert.deepEqual(validateRuns(grid,120000),{rows:8,runs:1,owned_cells:2,decoded_bytes:72});
const raw=new Map(),parts=['rows','runs'].map(kind=>{const words=grid[kind],bytes=gzipSync(shuffleOwnershipBytes(words));raw.set(kind,bytes);return{kind,path:kind,offset:0,words:words.length,encoding:'byte-shuffle',sha256:hash(bytes),decoded_sha256:hash(Buffer.from(words.buffer))};});
const manifest={version:2,size:8,coordinateBits:3,runWords:2,parts};
const fetcher=async url=>new Response(raw.get(url.slice(2)));
const decoded=await loadOwnershipAssets(manifest,fetcher);
assert.deepEqual(decoded.rows,grid.rows);assert.deepEqual(decoded.runs,grid.runs);
assert.deepEqual(differences(Uint32Array.from([0,0,4,0,0,0]),Uint32Array.from([2,2,4,2,2,2]),{x:10,y:20,width:3,height:2}),{cells:5,runs:[{y:20,start:10,end:12,original_owner:0,reconstructed_owner:2},{y:21,start:10,end:13,original_owner:0,reconstructed_owner:2}]});
const altered={...grid,rows:grid.rows.slice()};altered.rows[4]=0;assert.throws(()=>validateRuns(altered,120000),/Row offset/);
assert.throws(()=>validateRuns(grid,119999),/coordinate\/owner/);
const bad={...grid,runs:grid.runs.slice()};bad.runs[0]=(grid.runs[0]>>>3)*8+3;assert.throws(()=>validateRuns(bad,120000),/coordinate\/owner/);
await assert.rejects(loadOwnershipAssets({...manifest,parts:parts.slice(0,1)},fetcher),/Incomplete/);
await assert.rejects(loadOwnershipAssets({...manifest,parts:parts.map(p=>({...p,sha256:'0'.repeat(64)}))},fetcher),/checksum/);
await assert.rejects(loadOwnershipAssets({...manifest,parts:parts.map(p=>({...p,decoded_sha256:'0'.repeat(64)}))},fetcher),/checksum/);
console.log(JSON.stringify({method_id:'original-encoded-baseline-parity',positive_controls:3,negative_controls:6,outcome:'passed'}));
